// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aicc.sql

package sqlc

import (
	"context"
	"time"

	null "github.com/guregu/null/v5"
)

const attachAICCLeadValuesToLead = `-- name: AttachAICCLeadValuesToLead :exec
UPDATE aicc_lead_values
SET lead_id = ?, lead_org_id = ?
WHERE session_id = ? AND org_id = ?
`

type AttachAICCLeadValuesToLeadParams struct {
	LeadID    null.String `db:"lead_id" json:"lead_id"`
	LeadOrgID null.String `db:"lead_org_id" json:"lead_org_id"`
	SessionID string      `db:"session_id" json:"session_id"`
	OrgID     string      `db:"org_id" json:"org_id"`
}

func (q *Queries) AttachAICCLeadValuesToLead(ctx context.Context, arg AttachAICCLeadValuesToLeadParams) error {
	_, err := q.db.ExecContext(ctx, attachAICCLeadValuesToLead,
		arg.LeadID,
		arg.LeadOrgID,
		arg.SessionID,
		arg.OrgID,
	)
	return err
}

const clearAICCLeadLatestSession = `-- name: ClearAICCLeadLatestSession :exec
UPDATE aicc_leads
SET latest_session_id = NULL, updated_at = now()
WHERE latest_session_id = ?
`

func (q *Queries) ClearAICCLeadLatestSession(ctx context.Context, latestSessionID null.String) error {
	_, err := q.db.ExecContext(ctx, clearAICCLeadLatestSession, latestSessionID)
	return err
}

const countAICCAgentsByOrg = `-- name: CountAICCAgentsByOrg :one
SELECT COUNT(*)
FROM aicc_agents
WHERE org_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountAICCAgentsByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAICCAgentsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAICCTodaySessions = `-- name: CountAICCTodaySessions :one
SELECT COUNT(*)
FROM aicc_sessions
WHERE org_id = ? AND created_at >= CURRENT_DATE()
`

func (q *Queries) CountAICCTodaySessions(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAICCTodaySessions, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAICCUnreadLeads = `-- name: CountAICCUnreadLeads :one
SELECT COUNT(*)
FROM aicc_leads
WHERE org_id = ? AND unread = TRUE
`

func (q *Queries) CountAICCUnreadLeads(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAICCUnreadLeads, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAICCAgent = `-- name: CreateAICCAgent :exec
INSERT INTO aicc_agents (
    id, org_id, app_id, name, status, scenario, greeting, answer_boundary,
    privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json,
    public_token, widget_token
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCAgentParams struct {
	ID                 string      `db:"id" json:"id"`
	OrgID              string      `db:"org_id" json:"org_id"`
	AppID              string      `db:"app_id" json:"app_id"`
	Name               string      `db:"name" json:"name"`
	Status             string      `db:"status" json:"status"`
	Scenario           null.String `db:"scenario" json:"scenario"`
	Greeting           null.String `db:"greeting" json:"greeting"`
	AnswerBoundary     null.String `db:"answer_boundary" json:"answer_boundary"`
	PrivacyMode        string      `db:"privacy_mode" json:"privacy_mode"`
	PrivacyText        null.String `db:"privacy_text" json:"privacy_text"`
	RetentionDays      int32       `db:"retention_days" json:"retention_days"`
	ThemeJson          []byte      `db:"theme_json" json:"theme_json"`
	AllowedDomainsJson []byte      `db:"allowed_domains_json" json:"allowed_domains_json"`
	PublicToken        string      `db:"public_token" json:"public_token"`
	WidgetToken        string      `db:"widget_token" json:"widget_token"`
}

func (q *Queries) CreateAICCAgent(ctx context.Context, arg CreateAICCAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAICCAgent,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Name,
		arg.Status,
		arg.Scenario,
		arg.Greeting,
		arg.AnswerBoundary,
		arg.PrivacyMode,
		arg.PrivacyText,
		arg.RetentionDays,
		arg.ThemeJson,
		arg.AllowedDomainsJson,
		arg.PublicToken,
		arg.WidgetToken,
	)
	return err
}

const createAICCImage = `-- name: CreateAICCImage :exec
INSERT INTO aicc_images (
    id, session_id, agent_id, org_id, object_key, mime, size_bytes, filename
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCImageParams struct {
	ID        string `db:"id" json:"id"`
	SessionID string `db:"session_id" json:"session_id"`
	AgentID   string `db:"agent_id" json:"agent_id"`
	OrgID     string `db:"org_id" json:"org_id"`
	ObjectKey string `db:"object_key" json:"object_key"`
	Mime      string `db:"mime" json:"mime"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
	Filename  string `db:"filename" json:"filename"`
}

func (q *Queries) CreateAICCImage(ctx context.Context, arg CreateAICCImageParams) error {
	_, err := q.db.ExecContext(ctx, createAICCImage,
		arg.ID,
		arg.SessionID,
		arg.AgentID,
		arg.OrgID,
		arg.ObjectKey,
		arg.Mime,
		arg.SizeBytes,
		arg.Filename,
	)
	return err
}

const createAICCMessage = `-- name: CreateAICCMessage :exec
INSERT INTO aicc_messages (
    id, session_id, agent_id, direction, content_type, text_content,
    image_object_key, image_mime, image_size_bytes, hermes_message_id,
    is_fallback, is_refusal, error_summary
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCMessageParams struct {
	ID              string      `db:"id" json:"id"`
	SessionID       string      `db:"session_id" json:"session_id"`
	AgentID         string      `db:"agent_id" json:"agent_id"`
	Direction       string      `db:"direction" json:"direction"`
	ContentType     string      `db:"content_type" json:"content_type"`
	TextContent     null.String `db:"text_content" json:"text_content"`
	ImageObjectKey  null.String `db:"image_object_key" json:"image_object_key"`
	ImageMime       null.String `db:"image_mime" json:"image_mime"`
	ImageSizeBytes  null.Int    `db:"image_size_bytes" json:"image_size_bytes"`
	HermesMessageID null.String `db:"hermes_message_id" json:"hermes_message_id"`
	IsFallback      bool        `db:"is_fallback" json:"is_fallback"`
	IsRefusal       bool        `db:"is_refusal" json:"is_refusal"`
	ErrorSummary    null.String `db:"error_summary" json:"error_summary"`
}

func (q *Queries) CreateAICCMessage(ctx context.Context, arg CreateAICCMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAICCMessage,
		arg.ID,
		arg.SessionID,
		arg.AgentID,
		arg.Direction,
		arg.ContentType,
		arg.TextContent,
		arg.ImageObjectKey,
		arg.ImageMime,
		arg.ImageSizeBytes,
		arg.HermesMessageID,
		arg.IsFallback,
		arg.IsRefusal,
		arg.ErrorSummary,
	)
	return err
}

const createAICCSession = `-- name: CreateAICCSession :exec
INSERT INTO aicc_sessions (
    id, agent_id, org_id, session_token, channel, source_url, referrer, region,
    ip_hash, user_agent_hash, privacy_notice_shown, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCSessionParams struct {
	ID                 string      `db:"id" json:"id"`
	AgentID            string      `db:"agent_id" json:"agent_id"`
	OrgID              string      `db:"org_id" json:"org_id"`
	SessionToken       string      `db:"session_token" json:"session_token"`
	Channel            string      `db:"channel" json:"channel"`
	SourceUrl          null.String `db:"source_url" json:"source_url"`
	Referrer           null.String `db:"referrer" json:"referrer"`
	Region             null.String `db:"region" json:"region"`
	IpHash             null.String `db:"ip_hash" json:"ip_hash"`
	UserAgentHash      null.String `db:"user_agent_hash" json:"user_agent_hash"`
	PrivacyNoticeShown bool        `db:"privacy_notice_shown" json:"privacy_notice_shown"`
	ExpiresAt          time.Time   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAICCSession(ctx context.Context, arg CreateAICCSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAICCSession,
		arg.ID,
		arg.AgentID,
		arg.OrgID,
		arg.SessionToken,
		arg.Channel,
		arg.SourceUrl,
		arg.Referrer,
		arg.Region,
		arg.IpHash,
		arg.UserAgentHash,
		arg.PrivacyNoticeShown,
		arg.ExpiresAt,
	)
	return err
}

const deactivateAICCLeadFieldsByAgent = `-- name: DeactivateAICCLeadFieldsByAgent :exec
UPDATE aicc_lead_fields
SET deleted_at = now(), updated_at = now()
WHERE agent_id = ? AND deleted_at IS NULL
`

func (q *Queries) DeactivateAICCLeadFieldsByAgent(ctx context.Context, agentID string) error {
	_, err := q.db.ExecContext(ctx, deactivateAICCLeadFieldsByAgent, agentID)
	return err
}

const deleteAICCSession = `-- name: DeleteAICCSession :exec
DELETE FROM aicc_sessions
WHERE id = ?
`

func (q *Queries) DeleteAICCSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAICCSession, id)
	return err
}

const getAICCAgent = `-- name: GetAICCAgent :one
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAICCAgent(ctx context.Context, id string) (AiccAgent, error) {
	row := q.db.QueryRowContext(ctx, getAICCAgent, id)
	var i AiccAgent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.Status,
		&i.Scenario,
		&i.Greeting,
		&i.AnswerBoundary,
		&i.PrivacyMode,
		&i.PrivacyText,
		&i.RetentionDays,
		&i.ThemeJson,
		&i.AllowedDomainsJson,
		&i.PublicToken,
		&i.WidgetToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAICCAgentByPublicToken = `-- name: GetAICCAgentByPublicToken :one
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE public_token = ? AND status = 'active' AND deleted_at IS NULL
`

func (q *Queries) GetAICCAgentByPublicToken(ctx context.Context, publicToken string) (AiccAgent, error) {
	row := q.db.QueryRowContext(ctx, getAICCAgentByPublicToken, publicToken)
	var i AiccAgent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.Status,
		&i.Scenario,
		&i.Greeting,
		&i.AnswerBoundary,
		&i.PrivacyMode,
		&i.PrivacyText,
		&i.RetentionDays,
		&i.ThemeJson,
		&i.AllowedDomainsJson,
		&i.PublicToken,
		&i.WidgetToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAICCAssistantMessageForFeedback = `-- name: GetAICCAssistantMessageForFeedback :one
SELECT m.id, m.session_id, m.agent_id, m.direction, m.content_type, m.text_content, m.image_object_key, m.image_mime, m.image_size_bytes, m.hermes_message_id, m.is_fallback, m.is_refusal, m.error_summary, m.created_at
FROM aicc_messages m
JOIN aicc_sessions s ON s.id = m.session_id
WHERE m.id = ? AND s.session_token = ? AND m.direction = 'assistant' AND s.expires_at > now()
`

type GetAICCAssistantMessageForFeedbackParams struct {
	ID           string `db:"id" json:"id"`
	SessionToken string `db:"session_token" json:"session_token"`
}

func (q *Queries) GetAICCAssistantMessageForFeedback(ctx context.Context, arg GetAICCAssistantMessageForFeedbackParams) (AiccMessage, error) {
	row := q.db.QueryRowContext(ctx, getAICCAssistantMessageForFeedback, arg.ID, arg.SessionToken)
	var i AiccMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Direction,
		&i.ContentType,
		&i.TextContent,
		&i.ImageObjectKey,
		&i.ImageMime,
		&i.ImageSizeBytes,
		&i.HermesMessageID,
		&i.IsFallback,
		&i.IsRefusal,
		&i.ErrorSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getAICCImageBySession = `-- name: GetAICCImageBySession :one
SELECT id, session_id, agent_id, org_id, object_key, mime, size_bytes, filename, created_at
FROM aicc_images
WHERE id = ? AND session_id = ?
`

type GetAICCImageBySessionParams struct {
	ID        string `db:"id" json:"id"`
	SessionID string `db:"session_id" json:"session_id"`
}

func (q *Queries) GetAICCImageBySession(ctx context.Context, arg GetAICCImageBySessionParams) (AiccImage, error) {
	row := q.db.QueryRowContext(ctx, getAICCImageBySession, arg.ID, arg.SessionID)
	var i AiccImage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.OrgID,
		&i.ObjectKey,
		&i.Mime,
		&i.SizeBytes,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getAICCLeadByContact = `-- name: GetAICCLeadByContact :one
SELECT id, org_id, primary_contact_hash, display_name, unread, latest_session_id, latest_session_org_id, created_at, updated_at
FROM aicc_leads
WHERE org_id = ? AND primary_contact_hash = ?
`

type GetAICCLeadByContactParams struct {
	OrgID              string `db:"org_id" json:"org_id"`
	PrimaryContactHash string `db:"primary_contact_hash" json:"primary_contact_hash"`
}

func (q *Queries) GetAICCLeadByContact(ctx context.Context, arg GetAICCLeadByContactParams) (AiccLead, error) {
	row := q.db.QueryRowContext(ctx, getAICCLeadByContact, arg.OrgID, arg.PrimaryContactHash)
	var i AiccLead
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PrimaryContactHash,
		&i.DisplayName,
		&i.Unread,
		&i.LatestSessionID,
		&i.LatestSessionOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAICCSession = `-- name: GetAICCSession :one
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE id = ?
`

func (q *Queries) GetAICCSession(ctx context.Context, id string) (AiccSession, error) {
	row := q.db.QueryRowContext(ctx, getAICCSession, id)
	var i AiccSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OrgID,
		&i.SessionToken,
		&i.Channel,
		&i.SourceUrl,
		&i.Referrer,
		&i.Region,
		&i.IpHash,
		&i.UserAgentHash,
		&i.PrivacyNoticeShown,
		&i.PrivacyConsentedAt,
		&i.ResolutionStatus,
		&i.LeadStatus,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAICCSessionByToken = `-- name: GetAICCSessionByToken :one
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE session_token = ? AND expires_at > now()
`

func (q *Queries) GetAICCSessionByToken(ctx context.Context, sessionToken string) (AiccSession, error) {
	row := q.db.QueryRowContext(ctx, getAICCSessionByToken, sessionToken)
	var i AiccSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OrgID,
		&i.SessionToken,
		&i.Channel,
		&i.SourceUrl,
		&i.Referrer,
		&i.Region,
		&i.IpHash,
		&i.UserAgentHash,
		&i.PrivacyNoticeShown,
		&i.PrivacyConsentedAt,
		&i.ResolutionStatus,
		&i.LeadStatus,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAICCAgentsByOrg = `-- name: ListAICCAgentsByOrg :many
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE org_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAICCAgentsByOrgParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAICCAgentsByOrg(ctx context.Context, arg ListAICCAgentsByOrgParams) ([]AiccAgent, error) {
	rows, err := q.db.QueryContext(ctx, listAICCAgentsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccAgent{}
	for rows.Next() {
		var i AiccAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Name,
			&i.Status,
			&i.Scenario,
			&i.Greeting,
			&i.AnswerBoundary,
			&i.PrivacyMode,
			&i.PrivacyText,
			&i.RetentionDays,
			&i.ThemeJson,
			&i.AllowedDomainsJson,
			&i.PublicToken,
			&i.WidgetToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCImageObjectKeysBySession = `-- name: ListAICCImageObjectKeysBySession :many
SELECT object_key
FROM aicc_images
WHERE session_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAICCImageObjectKeysBySession(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAICCImageObjectKeysBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCLeadFieldsByAgent = `-- name: ListAICCLeadFieldsByAgent :many
SELECT id, agent_id, field_key, label, field_type, required, prompt_text, sort_order, created_at, updated_at, deleted_at
FROM aicc_lead_fields
WHERE agent_id = ? AND deleted_at IS NULL
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListAICCLeadFieldsByAgent(ctx context.Context, agentID string) ([]AiccLeadField, error) {
	rows, err := q.db.QueryContext(ctx, listAICCLeadFieldsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccLeadField{}
	for rows.Next() {
		var i AiccLeadField
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.FieldKey,
			&i.Label,
			&i.FieldType,
			&i.Required,
			&i.PromptText,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCLeadsByOrg = `-- name: ListAICCLeadsByOrg :many
SELECT id, org_id, primary_contact_hash, display_name, unread, latest_session_id, latest_session_org_id, created_at, updated_at
FROM aicc_leads
WHERE org_id = ?
ORDER BY unread DESC, updated_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAICCLeadsByOrgParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAICCLeadsByOrg(ctx context.Context, arg ListAICCLeadsByOrgParams) ([]AiccLead, error) {
	rows, err := q.db.QueryContext(ctx, listAICCLeadsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccLead{}
	for rows.Next() {
		var i AiccLead
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PrimaryContactHash,
			&i.DisplayName,
			&i.Unread,
			&i.LatestSessionID,
			&i.LatestSessionOrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCMessagesBySession = `-- name: ListAICCMessagesBySession :many
SELECT id, session_id, agent_id, direction, content_type, text_content, image_object_key, image_mime, image_size_bytes, hermes_message_id, is_fallback, is_refusal, error_summary, created_at
FROM aicc_messages
WHERE session_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAICCMessagesBySession(ctx context.Context, sessionID string) ([]AiccMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAICCMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccMessage{}
	for rows.Next() {
		var i AiccMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Direction,
			&i.ContentType,
			&i.TextContent,
			&i.ImageObjectKey,
			&i.ImageMime,
			&i.ImageSizeBytes,
			&i.HermesMessageID,
			&i.IsFallback,
			&i.IsRefusal,
			&i.ErrorSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCSessionsByAgent = `-- name: ListAICCSessionsByAgent :many
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE agent_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAICCSessionsByAgentParams struct {
	AgentID string `db:"agent_id" json:"agent_id"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAICCSessionsByAgent(ctx context.Context, arg ListAICCSessionsByAgentParams) ([]AiccSession, error) {
	rows, err := q.db.QueryContext(ctx, listAICCSessionsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccSession{}
	for rows.Next() {
		var i AiccSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OrgID,
			&i.SessionToken,
			&i.Channel,
			&i.SourceUrl,
			&i.Referrer,
			&i.Region,
			&i.IpHash,
			&i.UserAgentHash,
			&i.PrivacyNoticeShown,
			&i.PrivacyConsentedAt,
			&i.ResolutionStatus,
			&i.LeadStatus,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAICCLeadsByOrg = `-- name: ListAllAICCLeadsByOrg :many
SELECT id, org_id, primary_contact_hash, display_name, unread, latest_session_id, latest_session_org_id, created_at, updated_at
FROM aicc_leads
WHERE org_id = ?
ORDER BY unread DESC, updated_at DESC, id DESC
LIMIT ?
`

type ListAllAICCLeadsByOrgParams struct {
	OrgID string `db:"org_id" json:"org_id"`
	Limit int32  `db:"limit" json:"limit"`
}

func (q *Queries) ListAllAICCLeadsByOrg(ctx context.Context, arg ListAllAICCLeadsByOrgParams) ([]AiccLead, error) {
	rows, err := q.db.QueryContext(ctx, listAllAICCLeadsByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccLead{}
	for rows.Next() {
		var i AiccLead
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PrimaryContactHash,
			&i.DisplayName,
			&i.Unread,
			&i.LatestSessionID,
			&i.LatestSessionOrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAICCSessions = `-- name: ListExpiredAICCSessions :many
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE expires_at < now()
ORDER BY expires_at ASC, id ASC
LIMIT ?
`

func (q *Queries) ListExpiredAICCSessions(ctx context.Context, limit int32) ([]AiccSession, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredAICCSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccSession{}
	for rows.Next() {
		var i AiccSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OrgID,
			&i.SessionToken,
			&i.Channel,
			&i.SourceUrl,
			&i.Referrer,
			&i.Region,
			&i.IpHash,
			&i.UserAgentHash,
			&i.PrivacyNoticeShown,
			&i.PrivacyConsentedAt,
			&i.ResolutionStatus,
			&i.LeadStatus,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequiredAICCLeadFieldsMissing = `-- name: ListRequiredAICCLeadFieldsMissing :many
SELECT f.id, f.agent_id, f.field_key, f.label, f.field_type, f.required, f.prompt_text, f.sort_order, f.created_at, f.updated_at, f.deleted_at
FROM aicc_lead_fields f
JOIN aicc_sessions s ON s.agent_id = f.agent_id
LEFT JOIN aicc_lead_values v ON v.session_id = s.id AND v.field_id = f.id
WHERE s.id = ? AND f.required = TRUE AND v.id IS NULL
ORDER BY f.sort_order ASC, f.id ASC
`

func (q *Queries) ListRequiredAICCLeadFieldsMissing(ctx context.Context, id string) ([]AiccLeadField, error) {
	rows, err := q.db.QueryContext(ctx, listRequiredAICCLeadFieldsMissing, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccLeadField{}
	for rows.Next() {
		var i AiccLeadField
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.FieldKey,
			&i.Label,
			&i.FieldType,
			&i.Required,
			&i.PromptText,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAICCLeadRead = `-- name: MarkAICCLeadRead :execrows
UPDATE aicc_leads
SET unread = FALSE, updated_at = now()
WHERE id = ? AND org_id = ?
`

type MarkAICCLeadReadParams struct {
	ID    string `db:"id" json:"id"`
	OrgID string `db:"org_id" json:"org_id"`
}

func (q *Queries) MarkAICCLeadRead(ctx context.Context, arg MarkAICCLeadReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAICCLeadRead, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAICCSessionConsented = `-- name: MarkAICCSessionConsented :execrows
UPDATE aicc_sessions
SET privacy_consented_at = now(), updated_at = now()
WHERE session_token = ? AND expires_at > now()
`

func (q *Queries) MarkAICCSessionConsented(ctx context.Context, sessionToken string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAICCSessionConsented, sessionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAICCAgentStatus = `-- name: SetAICCAgentStatus :exec
UPDATE aicc_agents
SET status = ?, updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type SetAICCAgentStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetAICCAgentStatus(ctx context.Context, arg SetAICCAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAICCAgentStatus, arg.Status, arg.ID)
	return err
}

const softDeleteAICCAgent = `-- name: SoftDeleteAICCAgent :exec
UPDATE aicc_agents
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAICCAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteAICCAgent, id)
	return err
}

const updateAICCAgentProfile = `-- name: UpdateAICCAgentProfile :exec
UPDATE aicc_agents
SET name = ?, scenario = ?, greeting = ?, answer_boundary = ?, privacy_mode = ?,
    privacy_text = ?, retention_days = ?, theme_json = ?, allowed_domains_json = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAICCAgentProfileParams struct {
	Name               string      `db:"name" json:"name"`
	Scenario           null.String `db:"scenario" json:"scenario"`
	Greeting           null.String `db:"greeting" json:"greeting"`
	AnswerBoundary     null.String `db:"answer_boundary" json:"answer_boundary"`
	PrivacyMode        string      `db:"privacy_mode" json:"privacy_mode"`
	PrivacyText        null.String `db:"privacy_text" json:"privacy_text"`
	RetentionDays      int32       `db:"retention_days" json:"retention_days"`
	ThemeJson          []byte      `db:"theme_json" json:"theme_json"`
	AllowedDomainsJson []byte      `db:"allowed_domains_json" json:"allowed_domains_json"`
	ID                 string      `db:"id" json:"id"`
}

func (q *Queries) UpdateAICCAgentProfile(ctx context.Context, arg UpdateAICCAgentProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAICCAgentProfile,
		arg.Name,
		arg.Scenario,
		arg.Greeting,
		arg.AnswerBoundary,
		arg.PrivacyMode,
		arg.PrivacyText,
		arg.RetentionDays,
		arg.ThemeJson,
		arg.AllowedDomainsJson,
		arg.ID,
	)
	return err
}

const updateAICCSessionLeadStatus = `-- name: UpdateAICCSessionLeadStatus :exec
UPDATE aicc_sessions
SET lead_status = ?, updated_at = now()
WHERE id = ?
`

type UpdateAICCSessionLeadStatusParams struct {
	LeadStatus string `db:"lead_status" json:"lead_status"`
	ID         string `db:"id" json:"id"`
}

func (q *Queries) UpdateAICCSessionLeadStatus(ctx context.Context, arg UpdateAICCSessionLeadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAICCSessionLeadStatus, arg.LeadStatus, arg.ID)
	return err
}

const updateAICCSessionResolutionStatus = `-- name: UpdateAICCSessionResolutionStatus :exec
UPDATE aicc_sessions
SET resolution_status = ?, updated_at = now()
WHERE id = ?
`

type UpdateAICCSessionResolutionStatusParams struct {
	ResolutionStatus string `db:"resolution_status" json:"resolution_status"`
	ID               string `db:"id" json:"id"`
}

func (q *Queries) UpdateAICCSessionResolutionStatus(ctx context.Context, arg UpdateAICCSessionResolutionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAICCSessionResolutionStatus, arg.ResolutionStatus, arg.ID)
	return err
}

const upsertAICCFeedback = `-- name: UpsertAICCFeedback :exec
INSERT INTO aicc_feedback (id, session_id, message_id, helpful)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    helpful = VALUES(helpful)
`

type UpsertAICCFeedbackParams struct {
	ID        string `db:"id" json:"id"`
	SessionID string `db:"session_id" json:"session_id"`
	MessageID string `db:"message_id" json:"message_id"`
	Helpful   bool   `db:"helpful" json:"helpful"`
}

func (q *Queries) UpsertAICCFeedback(ctx context.Context, arg UpsertAICCFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, upsertAICCFeedback,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.Helpful,
	)
	return err
}

const upsertAICCLead = `-- name: UpsertAICCLead :exec
INSERT INTO aicc_leads (
    id, org_id, primary_contact_hash, display_name, latest_session_id
) VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    display_name = VALUES(display_name),
    latest_session_id = VALUES(latest_session_id),
    unread = TRUE,
    updated_at = now()
`

type UpsertAICCLeadParams struct {
	ID                 string      `db:"id" json:"id"`
	OrgID              string      `db:"org_id" json:"org_id"`
	PrimaryContactHash string      `db:"primary_contact_hash" json:"primary_contact_hash"`
	DisplayName        null.String `db:"display_name" json:"display_name"`
	LatestSessionID    null.String `db:"latest_session_id" json:"latest_session_id"`
}

func (q *Queries) UpsertAICCLead(ctx context.Context, arg UpsertAICCLeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertAICCLead,
		arg.ID,
		arg.OrgID,
		arg.PrimaryContactHash,
		arg.DisplayName,
		arg.LatestSessionID,
	)
	return err
}

const upsertAICCLeadField = `-- name: UpsertAICCLeadField :exec
INSERT INTO aicc_lead_fields (
    id, agent_id, field_key, label, field_type, required, prompt_text, sort_order
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    label = VALUES(label),
    field_type = VALUES(field_type),
    required = VALUES(required),
    prompt_text = VALUES(prompt_text),
    sort_order = VALUES(sort_order),
    deleted_at = NULL,
    updated_at = now()
`

type UpsertAICCLeadFieldParams struct {
	ID         string      `db:"id" json:"id"`
	AgentID    string      `db:"agent_id" json:"agent_id"`
	FieldKey   string      `db:"field_key" json:"field_key"`
	Label      string      `db:"label" json:"label"`
	FieldType  string      `db:"field_type" json:"field_type"`
	Required   bool        `db:"required" json:"required"`
	PromptText null.String `db:"prompt_text" json:"prompt_text"`
	SortOrder  int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) UpsertAICCLeadField(ctx context.Context, arg UpsertAICCLeadFieldParams) error {
	_, err := q.db.ExecContext(ctx, upsertAICCLeadField,
		arg.ID,
		arg.AgentID,
		arg.FieldKey,
		arg.Label,
		arg.FieldType,
		arg.Required,
		arg.PromptText,
		arg.SortOrder,
	)
	return err
}

const upsertAICCLeadValue = `-- name: UpsertAICCLeadValue :exec
INSERT INTO aicc_lead_values (
    id, session_id, agent_id, org_id, field_id, value_text, value_hash
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    value_text = VALUES(value_text),
    value_hash = VALUES(value_hash)
`

type UpsertAICCLeadValueParams struct {
	ID        string      `db:"id" json:"id"`
	SessionID string      `db:"session_id" json:"session_id"`
	AgentID   string      `db:"agent_id" json:"agent_id"`
	OrgID     string      `db:"org_id" json:"org_id"`
	FieldID   string      `db:"field_id" json:"field_id"`
	ValueText string      `db:"value_text" json:"value_text"`
	ValueHash null.String `db:"value_hash" json:"value_hash"`
}

func (q *Queries) UpsertAICCLeadValue(ctx context.Context, arg UpsertAICCLeadValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertAICCLeadValue,
		arg.ID,
		arg.SessionID,
		arg.AgentID,
		arg.OrgID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueHash,
	)
	return err
}
