// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aicc.sql

package sqlc

import (
	"context"
	"time"

	null "github.com/guregu/null/v5"
)

const countAICCAgentsByOrg = `-- name: CountAICCAgentsByOrg :one
SELECT COUNT(*)
FROM aicc_agents
WHERE org_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountAICCAgentsByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAICCAgentsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAICCAgent = `-- name: CreateAICCAgent :exec
INSERT INTO aicc_agents (
    id, org_id, app_id, name, status, scenario, greeting, answer_boundary,
    privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json,
    public_token, widget_token
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCAgentParams struct {
	ID                 string      `db:"id" json:"id"`
	OrgID              string      `db:"org_id" json:"org_id"`
	AppID              string      `db:"app_id" json:"app_id"`
	Name               string      `db:"name" json:"name"`
	Status             string      `db:"status" json:"status"`
	Scenario           null.String `db:"scenario" json:"scenario"`
	Greeting           null.String `db:"greeting" json:"greeting"`
	AnswerBoundary     null.String `db:"answer_boundary" json:"answer_boundary"`
	PrivacyMode        string      `db:"privacy_mode" json:"privacy_mode"`
	PrivacyText        null.String `db:"privacy_text" json:"privacy_text"`
	RetentionDays      int32       `db:"retention_days" json:"retention_days"`
	ThemeJson          []byte      `db:"theme_json" json:"theme_json"`
	AllowedDomainsJson []byte      `db:"allowed_domains_json" json:"allowed_domains_json"`
	PublicToken        string      `db:"public_token" json:"public_token"`
	WidgetToken        string      `db:"widget_token" json:"widget_token"`
}

func (q *Queries) CreateAICCAgent(ctx context.Context, arg CreateAICCAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAICCAgent,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Name,
		arg.Status,
		arg.Scenario,
		arg.Greeting,
		arg.AnswerBoundary,
		arg.PrivacyMode,
		arg.PrivacyText,
		arg.RetentionDays,
		arg.ThemeJson,
		arg.AllowedDomainsJson,
		arg.PublicToken,
		arg.WidgetToken,
	)
	return err
}

const createAICCMessage = `-- name: CreateAICCMessage :exec
INSERT INTO aicc_messages (
    id, session_id, agent_id, direction, content_type, text_content,
    image_object_key, image_mime, image_size_bytes, hermes_message_id,
    is_fallback, is_refusal, error_summary
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCMessageParams struct {
	ID              string      `db:"id" json:"id"`
	SessionID       string      `db:"session_id" json:"session_id"`
	AgentID         string      `db:"agent_id" json:"agent_id"`
	Direction       string      `db:"direction" json:"direction"`
	ContentType     string      `db:"content_type" json:"content_type"`
	TextContent     null.String `db:"text_content" json:"text_content"`
	ImageObjectKey  null.String `db:"image_object_key" json:"image_object_key"`
	ImageMime       null.String `db:"image_mime" json:"image_mime"`
	ImageSizeBytes  null.Int    `db:"image_size_bytes" json:"image_size_bytes"`
	HermesMessageID null.String `db:"hermes_message_id" json:"hermes_message_id"`
	IsFallback      bool        `db:"is_fallback" json:"is_fallback"`
	IsRefusal       bool        `db:"is_refusal" json:"is_refusal"`
	ErrorSummary    null.String `db:"error_summary" json:"error_summary"`
}

func (q *Queries) CreateAICCMessage(ctx context.Context, arg CreateAICCMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAICCMessage,
		arg.ID,
		arg.SessionID,
		arg.AgentID,
		arg.Direction,
		arg.ContentType,
		arg.TextContent,
		arg.ImageObjectKey,
		arg.ImageMime,
		arg.ImageSizeBytes,
		arg.HermesMessageID,
		arg.IsFallback,
		arg.IsRefusal,
		arg.ErrorSummary,
	)
	return err
}

const createAICCSession = `-- name: CreateAICCSession :exec
INSERT INTO aicc_sessions (
    id, agent_id, org_id, session_token, channel, source_url, referrer, region,
    ip_hash, user_agent_hash, privacy_notice_shown, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAICCSessionParams struct {
	ID                 string      `db:"id" json:"id"`
	AgentID            string      `db:"agent_id" json:"agent_id"`
	OrgID              string      `db:"org_id" json:"org_id"`
	SessionToken       string      `db:"session_token" json:"session_token"`
	Channel            string      `db:"channel" json:"channel"`
	SourceUrl          null.String `db:"source_url" json:"source_url"`
	Referrer           null.String `db:"referrer" json:"referrer"`
	Region             null.String `db:"region" json:"region"`
	IpHash             null.String `db:"ip_hash" json:"ip_hash"`
	UserAgentHash      null.String `db:"user_agent_hash" json:"user_agent_hash"`
	PrivacyNoticeShown bool        `db:"privacy_notice_shown" json:"privacy_notice_shown"`
	ExpiresAt          time.Time   `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateAICCSession(ctx context.Context, arg CreateAICCSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAICCSession,
		arg.ID,
		arg.AgentID,
		arg.OrgID,
		arg.SessionToken,
		arg.Channel,
		arg.SourceUrl,
		arg.Referrer,
		arg.Region,
		arg.IpHash,
		arg.UserAgentHash,
		arg.PrivacyNoticeShown,
		arg.ExpiresAt,
	)
	return err
}

const deleteAICCSession = `-- name: DeleteAICCSession :exec
DELETE FROM aicc_sessions
WHERE id = ?
`

func (q *Queries) DeleteAICCSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAICCSession, id)
	return err
}

const getAICCAgent = `-- name: GetAICCAgent :one
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAICCAgent(ctx context.Context, id string) (AiccAgent, error) {
	row := q.db.QueryRowContext(ctx, getAICCAgent, id)
	var i AiccAgent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.Status,
		&i.Scenario,
		&i.Greeting,
		&i.AnswerBoundary,
		&i.PrivacyMode,
		&i.PrivacyText,
		&i.RetentionDays,
		&i.ThemeJson,
		&i.AllowedDomainsJson,
		&i.PublicToken,
		&i.WidgetToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAICCAgentByPublicToken = `-- name: GetAICCAgentByPublicToken :one
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE public_token = ? AND deleted_at IS NULL
`

func (q *Queries) GetAICCAgentByPublicToken(ctx context.Context, publicToken string) (AiccAgent, error) {
	row := q.db.QueryRowContext(ctx, getAICCAgentByPublicToken, publicToken)
	var i AiccAgent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.Status,
		&i.Scenario,
		&i.Greeting,
		&i.AnswerBoundary,
		&i.PrivacyMode,
		&i.PrivacyText,
		&i.RetentionDays,
		&i.ThemeJson,
		&i.AllowedDomainsJson,
		&i.PublicToken,
		&i.WidgetToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAICCSessionByToken = `-- name: GetAICCSessionByToken :one
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE session_token = ?
`

func (q *Queries) GetAICCSessionByToken(ctx context.Context, sessionToken string) (AiccSession, error) {
	row := q.db.QueryRowContext(ctx, getAICCSessionByToken, sessionToken)
	var i AiccSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OrgID,
		&i.SessionToken,
		&i.Channel,
		&i.SourceUrl,
		&i.Referrer,
		&i.Region,
		&i.IpHash,
		&i.UserAgentHash,
		&i.PrivacyNoticeShown,
		&i.PrivacyConsentedAt,
		&i.ResolutionStatus,
		&i.LeadStatus,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAICCAgentsByOrg = `-- name: ListAICCAgentsByOrg :many
SELECT id, org_id, app_id, name, status, scenario, greeting, answer_boundary, privacy_mode, privacy_text, retention_days, theme_json, allowed_domains_json, public_token, widget_token, created_at, updated_at, deleted_at
FROM aicc_agents
WHERE org_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAICCAgentsByOrgParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAICCAgentsByOrg(ctx context.Context, arg ListAICCAgentsByOrgParams) ([]AiccAgent, error) {
	rows, err := q.db.QueryContext(ctx, listAICCAgentsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccAgent{}
	for rows.Next() {
		var i AiccAgent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Name,
			&i.Status,
			&i.Scenario,
			&i.Greeting,
			&i.AnswerBoundary,
			&i.PrivacyMode,
			&i.PrivacyText,
			&i.RetentionDays,
			&i.ThemeJson,
			&i.AllowedDomainsJson,
			&i.PublicToken,
			&i.WidgetToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAICCMessagesBySession = `-- name: ListAICCMessagesBySession :many
SELECT id, session_id, agent_id, direction, content_type, text_content, image_object_key, image_mime, image_size_bytes, hermes_message_id, is_fallback, is_refusal, error_summary, created_at
FROM aicc_messages
WHERE session_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListAICCMessagesBySession(ctx context.Context, sessionID string) ([]AiccMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAICCMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccMessage{}
	for rows.Next() {
		var i AiccMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Direction,
			&i.ContentType,
			&i.TextContent,
			&i.ImageObjectKey,
			&i.ImageMime,
			&i.ImageSizeBytes,
			&i.HermesMessageID,
			&i.IsFallback,
			&i.IsRefusal,
			&i.ErrorSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAICCSessions = `-- name: ListExpiredAICCSessions :many
SELECT id, agent_id, org_id, session_token, channel, source_url, referrer, region, ip_hash, user_agent_hash, privacy_notice_shown, privacy_consented_at, resolution_status, lead_status, last_active_at, expires_at, created_at, updated_at
FROM aicc_sessions
WHERE expires_at < now()
ORDER BY expires_at ASC, id ASC
LIMIT ?
`

func (q *Queries) ListExpiredAICCSessions(ctx context.Context, limit int32) ([]AiccSession, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredAICCSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiccSession{}
	for rows.Next() {
		var i AiccSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OrgID,
			&i.SessionToken,
			&i.Channel,
			&i.SourceUrl,
			&i.Referrer,
			&i.Region,
			&i.IpHash,
			&i.UserAgentHash,
			&i.PrivacyNoticeShown,
			&i.PrivacyConsentedAt,
			&i.ResolutionStatus,
			&i.LeadStatus,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAICCSessionConsented = `-- name: MarkAICCSessionConsented :exec
UPDATE aicc_sessions
SET privacy_consented_at = now(), updated_at = now()
WHERE session_token = ?
`

func (q *Queries) MarkAICCSessionConsented(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, markAICCSessionConsented, sessionToken)
	return err
}

const setAICCAgentStatus = `-- name: SetAICCAgentStatus :exec
UPDATE aicc_agents
SET status = ?, updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type SetAICCAgentStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetAICCAgentStatus(ctx context.Context, arg SetAICCAgentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAICCAgentStatus, arg.Status, arg.ID)
	return err
}

const softDeleteAICCAgent = `-- name: SoftDeleteAICCAgent :exec
UPDATE aicc_agents
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAICCAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteAICCAgent, id)
	return err
}

const updateAICCAgentProfile = `-- name: UpdateAICCAgentProfile :exec
UPDATE aicc_agents
SET name = ?, scenario = ?, greeting = ?, answer_boundary = ?, privacy_mode = ?,
    privacy_text = ?, retention_days = ?, theme_json = ?, allowed_domains_json = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAICCAgentProfileParams struct {
	Name               string      `db:"name" json:"name"`
	Scenario           null.String `db:"scenario" json:"scenario"`
	Greeting           null.String `db:"greeting" json:"greeting"`
	AnswerBoundary     null.String `db:"answer_boundary" json:"answer_boundary"`
	PrivacyMode        string      `db:"privacy_mode" json:"privacy_mode"`
	PrivacyText        null.String `db:"privacy_text" json:"privacy_text"`
	RetentionDays      int32       `db:"retention_days" json:"retention_days"`
	ThemeJson          []byte      `db:"theme_json" json:"theme_json"`
	AllowedDomainsJson []byte      `db:"allowed_domains_json" json:"allowed_domains_json"`
	ID                 string      `db:"id" json:"id"`
}

func (q *Queries) UpdateAICCAgentProfile(ctx context.Context, arg UpdateAICCAgentProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAICCAgentProfile,
		arg.Name,
		arg.Scenario,
		arg.Greeting,
		arg.AnswerBoundary,
		arg.PrivacyMode,
		arg.PrivacyText,
		arg.RetentionDays,
		arg.ThemeJson,
		arg.AllowedDomainsJson,
		arg.ID,
	)
	return err
}
