// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"
	"encoding/json"

	null "github.com/guregu/null/v5"
)

const clearAppProgress = `-- name: ClearAppProgress :exec
UPDATE apps
SET progress_current = NULL,
    progress_total = NULL,
    updated_at = now()
WHERE id = ?
`

// transitionTo / RequestInitialize 强制清空进度字段。
func (q *Queries) ClearAppProgress(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearAppProgress, id)
	return err
}

const countActiveAppsByOrg = `-- name: CountActiveAppsByOrg :one
SELECT COUNT(*) FROM apps WHERE org_id = ? AND deleted_at IS NULL
`

// 统计企业当前未删除实例数（apps.deleted_at IS NULL），用于企业实例数量上限校验。
func (q *Queries) CountActiveAppsByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAppsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApp = `-- name: CreateApp :exec
INSERT INTO apps (
    id,
    org_id,
    owner_user_id,
    name,
    description,
    status,
    api_key_status,
    version_id,
    locale
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAppParams struct {
	ID           string      `db:"id" json:"id"`
	OrgID        string      `db:"org_id" json:"org_id"`
	OwnerUserID  string      `db:"owner_user_id" json:"owner_user_id"`
	Name         string      `db:"name" json:"name"`
	Description  null.String `db:"description" json:"description"`
	Status       string      `db:"status" json:"status"`
	ApiKeyStatus string      `db:"api_key_status" json:"api_key_status"`
	VersionID    null.String `db:"version_id" json:"version_id"`
	Locale       null.String `db:"locale" json:"locale"`
}

// k8s 模型下 app 对应 Deployment，pod 落点由调度器决定，不再写 runtime_node_id。
// locale 在创建时快照 owner 的用户语言偏好（NULL=平台回退默认）。
func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.OrgID,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ApiKeyStatus,
		arg.VersionID,
		arg.Locale,
	)
	return err
}

const getActiveAppByOwner = `-- name: GetActiveAppByOwner :one
SELECT id, org_id, owner_user_id, name, description, status, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key, knowledge_quota_bytes, locale, runtime_phase
FROM apps
WHERE owner_user_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetActiveAppByOwner(ctx context.Context, ownerUserID string) (App, error) {
	row := q.db.QueryRowContext(ctx, getActiveAppByOwner, ownerUserID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
		&i.KnowledgeQuotaBytes,
		&i.Locale,
		&i.RuntimePhase,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, org_id, owner_user_id, name, description, status, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key, knowledge_quota_bytes, locale, runtime_phase
FROM apps
WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
		&i.KnowledgeQuotaBytes,
		&i.Locale,
		&i.RuntimePhase,
	)
	return i, err
}

const getAppByRuntimeTokenHash = `-- name: GetAppByRuntimeTokenHash :one
SELECT id, org_id, owner_user_id, name, description, status, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key, knowledge_quota_bytes, locale, runtime_phase
FROM apps
WHERE runtime_token_hash = ? AND deleted_at IS NULL
`

// 按 control token（per-app 三用：bootstrap / oc-kb / oc-ops）的 hash 反查当前 app；
// 不允许请求方传入目标 app/dataset，鉴权即定位。
func (q *Queries) GetAppByRuntimeTokenHash(ctx context.Context, runtimeTokenHash null.String) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByRuntimeTokenHash, runtimeTokenHash)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
		&i.KnowledgeQuotaBytes,
		&i.Locale,
		&i.RuntimePhase,
	)
	return i, err
}

const getAppWithVersion = `-- name: GetAppWithVersion :one
SELECT apps.id, apps.org_id, apps.owner_user_id, apps.name, apps.description, apps.status, apps.newapi_key_id, apps.newapi_key_ciphertext, apps.api_key_status, apps.runtime_snapshot_json, apps.runtime_snapshot_at, apps.restart_policy_json, apps.health_state_json, apps.progress_current, apps.progress_total, apps.last_error_status, apps.last_error_message, apps.runtime_image_ref, apps.runtime_image_sha256, apps.newapi_key_name, apps.version_id, apps.applied_version_revision, apps.applied_image_ref, apps.runtime_token_hash, apps.runtime_token_ciphertext, apps.created_at, apps.updated_at, apps.deleted_at, apps.owner_active_key, apps.runtime_token_active_key, apps.knowledge_quota_bytes, apps.locale, apps.runtime_phase, av.revision AS version_revision, av.image_id AS version_image_id
FROM apps
JOIN assistant_versions av ON av.id = apps.version_id
WHERE apps.id = ?
`

type GetAppWithVersionRow struct {
	App             App    `db:"app" json:"app"`
	VersionRevision int32  `db:"version_revision" json:"version_revision"`
	VersionImageID  string `db:"version_image_id" json:"version_image_id"`
}

// 取实例及其绑定版本的 revision / image_id，供 version_synced 计算。
func (q *Queries) GetAppWithVersion(ctx context.Context, id string) (GetAppWithVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getAppWithVersion, id)
	var i GetAppWithVersionRow
	err := row.Scan(
		&i.App.ID,
		&i.App.OrgID,
		&i.App.OwnerUserID,
		&i.App.Name,
		&i.App.Description,
		&i.App.Status,
		&i.App.NewapiKeyID,
		&i.App.NewapiKeyCiphertext,
		&i.App.ApiKeyStatus,
		&i.App.RuntimeSnapshotJson,
		&i.App.RuntimeSnapshotAt,
		&i.App.RestartPolicyJson,
		&i.App.HealthStateJson,
		&i.App.ProgressCurrent,
		&i.App.ProgressTotal,
		&i.App.LastErrorStatus,
		&i.App.LastErrorMessage,
		&i.App.RuntimeImageRef,
		&i.App.RuntimeImageSha256,
		&i.App.NewapiKeyName,
		&i.App.VersionID,
		&i.App.AppliedVersionRevision,
		&i.App.AppliedImageRef,
		&i.App.RuntimeTokenHash,
		&i.App.RuntimeTokenCiphertext,
		&i.App.CreatedAt,
		&i.App.UpdatedAt,
		&i.App.DeletedAt,
		&i.App.OwnerActiveKey,
		&i.App.RuntimeTokenActiveKey,
		&i.App.KnowledgeQuotaBytes,
		&i.App.Locale,
		&i.App.RuntimePhase,
		&i.VersionRevision,
		&i.VersionImageID,
	)
	return i, err
}

const listAppsByOrg = `-- name: ListAppsByOrg :many
SELECT id, org_id, owner_user_id, name, description, status, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key, knowledge_quota_bytes, locale, runtime_phase
FROM apps
WHERE org_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAppsByOrgParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAppsByOrg(ctx context.Context, arg ListAppsByOrgParams) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.NewapiKeyID,
			&i.NewapiKeyCiphertext,
			&i.ApiKeyStatus,
			&i.RuntimeSnapshotJson,
			&i.RuntimeSnapshotAt,
			&i.RestartPolicyJson,
			&i.HealthStateJson,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.LastErrorStatus,
			&i.LastErrorMessage,
			&i.RuntimeImageRef,
			&i.RuntimeImageSha256,
			&i.NewapiKeyName,
			&i.VersionID,
			&i.AppliedVersionRevision,
			&i.AppliedImageRef,
			&i.RuntimeTokenHash,
			&i.RuntimeTokenCiphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OwnerActiveKey,
			&i.RuntimeTokenActiveKey,
			&i.KnowledgeQuotaBytes,
			&i.Locale,
			&i.RuntimePhase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOrgWithVersion = `-- name: ListAppsByOrgWithVersion :many
SELECT apps.id, apps.org_id, apps.owner_user_id, apps.name, apps.description, apps.status, apps.newapi_key_id, apps.newapi_key_ciphertext, apps.api_key_status, apps.runtime_snapshot_json, apps.runtime_snapshot_at, apps.restart_policy_json, apps.health_state_json, apps.progress_current, apps.progress_total, apps.last_error_status, apps.last_error_message, apps.runtime_image_ref, apps.runtime_image_sha256, apps.newapi_key_name, apps.version_id, apps.applied_version_revision, apps.applied_image_ref, apps.runtime_token_hash, apps.runtime_token_ciphertext, apps.created_at, apps.updated_at, apps.deleted_at, apps.owner_active_key, apps.runtime_token_active_key, apps.knowledge_quota_bytes, apps.locale, apps.runtime_phase, av.revision AS version_revision, av.image_id AS version_image_id
FROM apps
JOIN assistant_versions av ON av.id = apps.version_id
WHERE apps.org_id = ? AND apps.deleted_at IS NULL
ORDER BY apps.created_at DESC, apps.id DESC
LIMIT ? OFFSET ?
`

type ListAppsByOrgWithVersionParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type ListAppsByOrgWithVersionRow struct {
	App             App    `db:"app" json:"app"`
	VersionRevision int32  `db:"version_revision" json:"version_revision"`
	VersionImageID  string `db:"version_image_id" json:"version_image_id"`
}

// 组织实例列表联查版本 revision / image_id，供 version_synced 批量计算。
func (q *Queries) ListAppsByOrgWithVersion(ctx context.Context, arg ListAppsByOrgWithVersionParams) ([]ListAppsByOrgWithVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOrgWithVersion, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByOrgWithVersionRow{}
	for rows.Next() {
		var i ListAppsByOrgWithVersionRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.OrgID,
			&i.App.OwnerUserID,
			&i.App.Name,
			&i.App.Description,
			&i.App.Status,
			&i.App.NewapiKeyID,
			&i.App.NewapiKeyCiphertext,
			&i.App.ApiKeyStatus,
			&i.App.RuntimeSnapshotJson,
			&i.App.RuntimeSnapshotAt,
			&i.App.RestartPolicyJson,
			&i.App.HealthStateJson,
			&i.App.ProgressCurrent,
			&i.App.ProgressTotal,
			&i.App.LastErrorStatus,
			&i.App.LastErrorMessage,
			&i.App.RuntimeImageRef,
			&i.App.RuntimeImageSha256,
			&i.App.NewapiKeyName,
			&i.App.VersionID,
			&i.App.AppliedVersionRevision,
			&i.App.AppliedImageRef,
			&i.App.RuntimeTokenHash,
			&i.App.RuntimeTokenCiphertext,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.DeletedAt,
			&i.App.OwnerActiveKey,
			&i.App.RuntimeTokenActiveKey,
			&i.App.KnowledgeQuotaBytes,
			&i.App.Locale,
			&i.App.RuntimePhase,
			&i.VersionRevision,
			&i.VersionImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorApps = `-- name: ListErrorApps :many
SELECT id
FROM apps
WHERE deleted_at IS NULL
  AND status = 'error'
ORDER BY id
`

// reconciler 兜底用：列出 status=error 的 app。reconciler 查其 pod，若 hermes 实际 Ready
// （说明并非真失败，只是状态没收敛，如 WaitReady 曾误超时但 pod 后来起来了），就重新入队
// init job 推进到 running；pod 真坏则保持 error 不动。reaper 只扫 init 子状态、不管 error，
// 此查询补上「init 失败成 error 后无法自愈」的洞。
func (q *Queries) ListErrorApps(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listErrorApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestartingApps = `-- name: ListRestartingApps :many
SELECT id
FROM apps
WHERE deleted_at IS NULL
  AND status = 'restarting'
ORDER BY id
`

// reconciler 收敛用：列出 status=restarting 的 app id。渠道解绑触发 RolloutRestart 后
// 实例置 restarting，pod 重建（Recreate）期间 oc-ops 不可用；reconciler 周期查其 pod 状态，
// pod 重新 Ready → 收敛回 running，pod 坏死 → error，重启空窗（Pending）→ 保持 restarting 等下轮。
func (q *Queries) ListRestartingApps(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRestartingApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningApps = `-- name: ListRunningApps :many
SELECT id
FROM apps
WHERE deleted_at IS NULL
  AND status IN ('running', 'binding_waiting')
ORDER BY id
`

// 列出当前期望运行（k8s Deployment 已创建）的应用，供 app_status_reconciler 周期 poll pod 状态。
// running 是常态；binding_waiting 表示 pod 已起但渠道还在登录中，也需要 reconcile。
// spec-A2b：去掉 runtime_node_id / container_id（k8s 路径不再写这两列），消费方仅用 id。
func (q *Queries) ListRunningApps(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRunningApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleInits = `-- name: ListStaleInits :many
SELECT id, status
FROM apps
WHERE deleted_at IS NULL
  AND status IN ('pulling_runtime_image','preparing_runtime','creating_container','starting')
  AND updated_at < now() - INTERVAL ? SECOND
ORDER BY id
`

type ListStaleInitsRow struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

// reaper 扫描 init 子状态下「连续 N 秒无更新」的孤儿；N 由调用方按秒传入。
// 包含新旧两套 init 状态，确保历史孤儿也能被正确清理。
// spec-A2b：去掉 runtime_node_id（k8s 路径不再写该列），reaper 仅需 id / status 重置孤儿。
// 关键：阈值用 SQL 侧 now() - INTERVAL 计算，而非接收 Go 侧 time.Now() 阈值。
// updated_at 由 now() 写入，二者同处服务器时钟与会话时区，根除「Go 时间 vs now() 列」
// 跨时区比较错位（曾因 DSN loc=UTC 与服务器 +08:00 不匹配导致本查询恒返回 0，孤儿永不回收）。
func (q *Queries) ListStaleInits(ctx context.Context, dateSUB interface{}) ([]ListStaleInitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleInits, dateSUB)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleInitsRow{}
	for rows.Next() {
		var i ListStaleInitsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppFailed = `-- name: MarkAppFailed :exec
UPDATE apps
SET status = 'error',
    last_error_status = ?,
    last_error_message = ?,
    progress_current = NULL,
    progress_total = NULL,
    updated_at = now()
WHERE id = ?
`

type MarkAppFailedParams struct {
	LastErrorStatus  null.String `db:"last_error_status" json:"last_error_status"`
	LastErrorMessage null.String `db:"last_error_message" json:"last_error_message"`
	ID               string      `db:"id" json:"id"`
}

// 任意状态 → error 时同时写入来源状态与错误文本，保留"在哪一步失败"与"为什么失败"语义。
// last_error_status 不加 CHECK 约束，值由调用方在 Go 层负责合法性。
func (q *Queries) MarkAppFailed(ctx context.Context, arg MarkAppFailedParams) error {
	_, err := q.db.ExecContext(ctx, markAppFailed, arg.LastErrorStatus, arg.LastErrorMessage, arg.ID)
	return err
}

const setAppAppliedVersion = `-- name: SetAppAppliedVersion :exec
UPDATE apps
SET applied_version_revision = ?,
    applied_image_ref = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppAppliedVersionParams struct {
	AppliedVersionRevision int32  `db:"applied_version_revision" json:"applied_version_revision"`
	AppliedImageRef        string `db:"applied_image_ref" json:"applied_image_ref"`
	ID                     string `db:"id" json:"id"`
}

// 初始化/重启成功后记录已应用的版本修订与镜像 ref，用于 version_synced 检测。
func (q *Queries) SetAppAppliedVersion(ctx context.Context, arg SetAppAppliedVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAppAppliedVersion, arg.AppliedVersionRevision, arg.AppliedImageRef, arg.ID)
	return err
}

const setAppHealthState = `-- name: SetAppHealthState :exec
UPDATE apps
SET health_state_json = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppHealthStateParams struct {
	HealthStateJson []byte `db:"health_state_json" json:"health_state_json"`
	ID              string `db:"id" json:"id"`
}

// worker app_health_check handler 写最近一次健康检查结果；用于自动重启窗口计数。
func (q *Queries) SetAppHealthState(ctx context.Context, arg SetAppHealthStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppHealthState, arg.HealthStateJson, arg.ID)
	return err
}

const setAppKnowledgeQuota = `-- name: SetAppKnowledgeQuota :exec
UPDATE apps
SET knowledge_quota_bytes = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type SetAppKnowledgeQuotaParams struct {
	KnowledgeQuotaBytes int64  `db:"knowledge_quota_bytes" json:"knowledge_quota_bytes"`
	ID                  string `db:"id" json:"id"`
}

// 更新单个实例知识库累计容量上限；允许低于当前已用，后续上传由 KnowledgeService 拒绝。
func (q *Queries) SetAppKnowledgeQuota(ctx context.Context, arg SetAppKnowledgeQuotaParams) error {
	_, err := q.db.ExecContext(ctx, setAppKnowledgeQuota, arg.KnowledgeQuotaBytes, arg.ID)
	return err
}

const setAppNewAPIKey = `-- name: SetAppNewAPIKey :exec
UPDATE apps
SET
    newapi_key_id = ?,
    newapi_key_ciphertext = ?,
    api_key_status = ?,
    newapi_key_name = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppNewAPIKeyParams struct {
	NewapiKeyID         null.String `db:"newapi_key_id" json:"newapi_key_id"`
	NewapiKeyCiphertext null.String `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus        string      `db:"api_key_status" json:"api_key_status"`
	NewapiKeyName       null.String `db:"newapi_key_name" json:"newapi_key_name"`
	ID                  string      `db:"id" json:"id"`
}

func (q *Queries) SetAppNewAPIKey(ctx context.Context, arg SetAppNewAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAppNewAPIKey,
		arg.NewapiKeyID,
		arg.NewapiKeyCiphertext,
		arg.ApiKeyStatus,
		arg.NewapiKeyName,
		arg.ID,
	)
	return err
}

const setAppProgress = `-- name: SetAppProgress :exec
UPDATE apps
SET progress_current = ?,
    progress_total = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppProgressParams struct {
	ProgressCurrent null.Int `db:"progress_current" json:"progress_current"`
	ProgressTotal   null.Int `db:"progress_total" json:"progress_total"`
	ID              string   `db:"id" json:"id"`
}

// progressReporter 节流后写入；NULL/NULL 表示阶段切换或未知。
func (q *Queries) SetAppProgress(ctx context.Context, arg SetAppProgressParams) error {
	_, err := q.db.ExecContext(ctx, setAppProgress, arg.ProgressCurrent, arg.ProgressTotal, arg.ID)
	return err
}

const setAppRestartPolicy = `-- name: SetAppRestartPolicy :exec
UPDATE apps
SET restart_policy_json = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppRestartPolicyParams struct {
	RestartPolicyJson json.RawMessage `db:"restart_policy_json" json:"restart_policy_json"`
	ID                string          `db:"id" json:"id"`
}

// 管理员 PATCH /apps/:appId/restart-policy 写入；mode/max_per_window/window_seconds 校验在 service 层。
func (q *Queries) SetAppRestartPolicy(ctx context.Context, arg SetAppRestartPolicyParams) error {
	_, err := q.db.ExecContext(ctx, setAppRestartPolicy, arg.RestartPolicyJson, arg.ID)
	return err
}

const setAppRuntimePhase = `-- name: SetAppRuntimePhase :exec
UPDATE apps
SET runtime_phase = ?, updated_at = now()
WHERE id = ?
`

type SetAppRuntimePhaseParams struct {
	RuntimePhase string `db:"runtime_phase" json:"runtime_phase"`
	ID           string `db:"id" json:"id"`
}

// 裸 UPDATE runtime_phase(运行时就绪维度,与 status 正交,无状态机守卫,守卫不适用):
// reconciler 周期写、init worker 首启/就绪写、渠道解绑/升级重启前置 restarting 用。
func (q *Queries) SetAppRuntimePhase(ctx context.Context, arg SetAppRuntimePhaseParams) error {
	_, err := q.db.ExecContext(ctx, setAppRuntimePhase, arg.RuntimePhase, arg.ID)
	return err
}

const setAppRuntimeSnapshot = `-- name: SetAppRuntimeSnapshot :exec
UPDATE apps
SET runtime_snapshot_json = ?,
    runtime_snapshot_at = now(),
    updated_at = now()
WHERE id = ?
`

type SetAppRuntimeSnapshotParams struct {
	RuntimeSnapshotJson []byte `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
	ID                  string `db:"id" json:"id"`
}

func (q *Queries) SetAppRuntimeSnapshot(ctx context.Context, arg SetAppRuntimeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, setAppRuntimeSnapshot, arg.RuntimeSnapshotJson, arg.ID)
	return err
}

const setAppRuntimeToken = `-- name: SetAppRuntimeToken :exec
UPDATE apps
SET runtime_token_hash = ?,
    runtime_token_ciphertext = ?,
    updated_at = now()
WHERE id = ?
  AND deleted_at IS NULL
  AND runtime_token_hash IS NULL
  AND runtime_token_ciphertext IS NULL
`

type SetAppRuntimeTokenParams struct {
	RuntimeTokenHash       null.String `db:"runtime_token_hash" json:"runtime_token_hash"`
	RuntimeTokenCiphertext null.String `db:"runtime_token_ciphertext" json:"runtime_token_ciphertext"`
	ID                     string      `db:"id" json:"id"`
}

// 首次写入 per-app control token（三用：bootstrap / oc-kb / oc-ops）；并发重复初始化拿不到行，由 service 读取既有 token。
func (q *Queries) SetAppRuntimeToken(ctx context.Context, arg SetAppRuntimeTokenParams) error {
	_, err := q.db.ExecContext(ctx, setAppRuntimeToken, arg.RuntimeTokenHash, arg.RuntimeTokenCiphertext, arg.ID)
	return err
}

const setAppStatus = `-- name: SetAppStatus :exec
UPDATE apps
SET status = ?, updated_at = now()
WHERE id = ?
`

type SetAppStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetAppStatus(ctx context.Context, arg SetAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAppStatus, arg.Status, arg.ID)
	return err
}

const setAppVersion = `-- name: SetAppVersion :exec
UPDATE apps
SET version_id = ?,
    applied_version_revision = 0,
    applied_image_ref = '',
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type SetAppVersionParams struct {
	VersionID null.String `db:"version_id" json:"version_id"`
	ID        string      `db:"id" json:"id"`
}

// 切换实例绑定的助手版本，并把 applied_version_revision / applied_image_ref 清零。
// 不同版本各自维护独立的 revision 计数，若切换后保留旧 applied_*，当新旧版本
// 的 revision 数字恰好相同（且镜像相同）时 version_synced 会误判为已同步。
// 清零后 applied_version_revision=0 永远不等于任何真实版本 revision（从 1 起），
// 实例切换后必然进入需重启态，直到重启重新写入 applied_*。
func (q *Queries) SetAppVersion(ctx context.Context, arg SetAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAppVersion, arg.VersionID, arg.ID)
	return err
}

const softDeleteApp = `-- name: SoftDeleteApp :exec
UPDATE apps
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteApp, id)
	return err
}

const touchApp = `-- name: TouchApp :exec
UPDATE apps
SET updated_at = now()
WHERE id = ?
`

// 仅刷新 updated_at：worker 等待 pod Ready 期间的心跳。让 reaper 凭 updated_at 区分
// 「worker 仍在等待（拉镜像可能数十分钟）」与「worker 已死的孤儿」，避免误回收正在处理的 job。
// 不改 status 或其它字段。
func (q *Queries) TouchApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchApp, id)
	return err
}

const updateAppLocale = `-- name: UpdateAppLocale :exec
UPDATE apps
SET locale = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAppLocaleParams struct {
	Locale null.String `db:"locale" json:"locale"`
	ID     string      `db:"id" json:"id"`
}

// 更新实例语言偏好（hermes 对终端用户说话的语言）。locale 由 service 层校验合法取值后传入。
func (q *Queries) UpdateAppLocale(ctx context.Context, arg UpdateAppLocaleParams) error {
	_, err := q.db.ExecContext(ctx, updateAppLocale, arg.Locale, arg.ID)
	return err
}

const updateAppRuntimeImage = `-- name: UpdateAppRuntimeImage :exec
UPDATE apps
SET
    runtime_image_ref    = ?,
    runtime_image_sha256 = ?,
    updated_at = now()
WHERE id = ?
`

type UpdateAppRuntimeImageParams struct {
	RuntimeImageRef    string `db:"runtime_image_ref" json:"runtime_image_ref"`
	RuntimeImageSha256 string `db:"runtime_image_sha256" json:"runtime_image_sha256"`
	ID                 string `db:"id" json:"id"`
}

// phasePullRuntimeImage 成功后写入镜像引用与 sha256。
func (q *Queries) UpdateAppRuntimeImage(ctx context.Context, arg UpdateAppRuntimeImageParams) error {
	_, err := q.db.ExecContext(ctx, updateAppRuntimeImage, arg.RuntimeImageRef, arg.RuntimeImageSha256, arg.ID)
	return err
}
