// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	null "github.com/guregu/null/v5"
)

const clearAppProgress = `-- name: ClearAppProgress :exec
UPDATE apps
SET progress_current = NULL,
    progress_total = NULL,
    updated_at = now()
WHERE id = ?
`

// transitionTo / RequestInitialize 强制清空进度字段。
func (q *Queries) ClearAppProgress(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearAppProgress, id)
	return err
}

const createApp = `-- name: CreateApp :exec
INSERT INTO apps (
    id,
    org_id,
    owner_user_id,
    runtime_node_id,
    name,
    description,
    status,
    api_key_status,
    version_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAppParams struct {
	ID            string      `db:"id" json:"id"`
	OrgID         string      `db:"org_id" json:"org_id"`
	OwnerUserID   string      `db:"owner_user_id" json:"owner_user_id"`
	RuntimeNodeID string      `db:"runtime_node_id" json:"runtime_node_id"`
	Name          string      `db:"name" json:"name"`
	Description   null.String `db:"description" json:"description"`
	Status        string      `db:"status" json:"status"`
	ApiKeyStatus  string      `db:"api_key_status" json:"api_key_status"`
	VersionID     null.String `db:"version_id" json:"version_id"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) error {
	_, err := q.db.ExecContext(ctx, createApp,
		arg.ID,
		arg.OrgID,
		arg.OwnerUserID,
		arg.RuntimeNodeID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ApiKeyStatus,
		arg.VersionID,
	)
	return err
}

const getActiveAppByOwner = `-- name: GetActiveAppByOwner :one
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key
FROM apps
WHERE owner_user_id = ? AND deleted_at IS NULL
`

func (q *Queries) GetActiveAppByOwner(ctx context.Context, ownerUserID string) (App, error) {
	row := q.db.QueryRowContext(ctx, getActiveAppByOwner, ownerUserID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key
FROM apps
WHERE id = ?
`

func (q *Queries) GetApp(ctx context.Context, id string) (App, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
	)
	return i, err
}

const getAppByRuntimeTokenHash = `-- name: GetAppByRuntimeTokenHash :one
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key
FROM apps
WHERE runtime_token_hash = ? AND deleted_at IS NULL
`

// runtime API 只接受 token hash 解析出的当前 app，不允许请求方传入目标 app/dataset。
func (q *Queries) GetAppByRuntimeTokenHash(ctx context.Context, runtimeTokenHash null.String) (App, error) {
	row := q.db.QueryRowContext(ctx, getAppByRuntimeTokenHash, runtimeTokenHash)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
		&i.RestartPolicyJson,
		&i.HealthStateJson,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.LastErrorStatus,
		&i.LastErrorMessage,
		&i.RuntimeImageRef,
		&i.RuntimeImageSha256,
		&i.NewapiKeyName,
		&i.VersionID,
		&i.AppliedVersionRevision,
		&i.AppliedImageRef,
		&i.RuntimeTokenHash,
		&i.RuntimeTokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OwnerActiveKey,
		&i.RuntimeTokenActiveKey,
	)
	return i, err
}

const getAppWithVersion = `-- name: GetAppWithVersion :one
SELECT apps.id, apps.org_id, apps.owner_user_id, apps.runtime_node_id, apps.name, apps.description, apps.status, apps.container_id, apps.container_name, apps.newapi_key_id, apps.newapi_key_ciphertext, apps.api_key_status, apps.runtime_snapshot_json, apps.runtime_snapshot_at, apps.restart_policy_json, apps.health_state_json, apps.progress_current, apps.progress_total, apps.last_error_status, apps.last_error_message, apps.runtime_image_ref, apps.runtime_image_sha256, apps.newapi_key_name, apps.version_id, apps.applied_version_revision, apps.applied_image_ref, apps.runtime_token_hash, apps.runtime_token_ciphertext, apps.created_at, apps.updated_at, apps.deleted_at, apps.owner_active_key, apps.runtime_token_active_key, av.revision AS version_revision, av.image_id AS version_image_id
FROM apps
JOIN assistant_versions av ON av.id = apps.version_id
WHERE apps.id = ?
`

type GetAppWithVersionRow struct {
	App             App    `db:"app" json:"app"`
	VersionRevision int32  `db:"version_revision" json:"version_revision"`
	VersionImageID  string `db:"version_image_id" json:"version_image_id"`
}

// 取实例及其绑定版本的 revision / image_id，供 version_synced 计算。
func (q *Queries) GetAppWithVersion(ctx context.Context, id string) (GetAppWithVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getAppWithVersion, id)
	var i GetAppWithVersionRow
	err := row.Scan(
		&i.App.ID,
		&i.App.OrgID,
		&i.App.OwnerUserID,
		&i.App.RuntimeNodeID,
		&i.App.Name,
		&i.App.Description,
		&i.App.Status,
		&i.App.ContainerID,
		&i.App.ContainerName,
		&i.App.NewapiKeyID,
		&i.App.NewapiKeyCiphertext,
		&i.App.ApiKeyStatus,
		&i.App.RuntimeSnapshotJson,
		&i.App.RuntimeSnapshotAt,
		&i.App.RestartPolicyJson,
		&i.App.HealthStateJson,
		&i.App.ProgressCurrent,
		&i.App.ProgressTotal,
		&i.App.LastErrorStatus,
		&i.App.LastErrorMessage,
		&i.App.RuntimeImageRef,
		&i.App.RuntimeImageSha256,
		&i.App.NewapiKeyName,
		&i.App.VersionID,
		&i.App.AppliedVersionRevision,
		&i.App.AppliedImageRef,
		&i.App.RuntimeTokenHash,
		&i.App.RuntimeTokenCiphertext,
		&i.App.CreatedAt,
		&i.App.UpdatedAt,
		&i.App.DeletedAt,
		&i.App.OwnerActiveKey,
		&i.App.RuntimeTokenActiveKey,
		&i.VersionRevision,
		&i.VersionImageID,
	)
	return i, err
}

const listAppsByOrg = `-- name: ListAppsByOrg :many
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key
FROM apps
WHERE org_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAppsByOrgParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAppsByOrg(ctx context.Context, arg ListAppsByOrgParams) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.RuntimeNodeID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.ContainerID,
			&i.ContainerName,
			&i.NewapiKeyID,
			&i.NewapiKeyCiphertext,
			&i.ApiKeyStatus,
			&i.RuntimeSnapshotJson,
			&i.RuntimeSnapshotAt,
			&i.RestartPolicyJson,
			&i.HealthStateJson,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.LastErrorStatus,
			&i.LastErrorMessage,
			&i.RuntimeImageRef,
			&i.RuntimeImageSha256,
			&i.NewapiKeyName,
			&i.VersionID,
			&i.AppliedVersionRevision,
			&i.AppliedImageRef,
			&i.RuntimeTokenHash,
			&i.RuntimeTokenCiphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OwnerActiveKey,
			&i.RuntimeTokenActiveKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByOrgWithVersion = `-- name: ListAppsByOrgWithVersion :many
SELECT apps.id, apps.org_id, apps.owner_user_id, apps.runtime_node_id, apps.name, apps.description, apps.status, apps.container_id, apps.container_name, apps.newapi_key_id, apps.newapi_key_ciphertext, apps.api_key_status, apps.runtime_snapshot_json, apps.runtime_snapshot_at, apps.restart_policy_json, apps.health_state_json, apps.progress_current, apps.progress_total, apps.last_error_status, apps.last_error_message, apps.runtime_image_ref, apps.runtime_image_sha256, apps.newapi_key_name, apps.version_id, apps.applied_version_revision, apps.applied_image_ref, apps.runtime_token_hash, apps.runtime_token_ciphertext, apps.created_at, apps.updated_at, apps.deleted_at, apps.owner_active_key, apps.runtime_token_active_key, av.revision AS version_revision, av.image_id AS version_image_id
FROM apps
JOIN assistant_versions av ON av.id = apps.version_id
WHERE apps.org_id = ? AND apps.deleted_at IS NULL
ORDER BY apps.created_at DESC, apps.id DESC
LIMIT ? OFFSET ?
`

type ListAppsByOrgWithVersionParams struct {
	OrgID  string `db:"org_id" json:"org_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type ListAppsByOrgWithVersionRow struct {
	App             App    `db:"app" json:"app"`
	VersionRevision int32  `db:"version_revision" json:"version_revision"`
	VersionImageID  string `db:"version_image_id" json:"version_image_id"`
}

// 组织实例列表联查版本 revision / image_id，供 version_synced 批量计算。
func (q *Queries) ListAppsByOrgWithVersion(ctx context.Context, arg ListAppsByOrgWithVersionParams) ([]ListAppsByOrgWithVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByOrgWithVersion, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByOrgWithVersionRow{}
	for rows.Next() {
		var i ListAppsByOrgWithVersionRow
		if err := rows.Scan(
			&i.App.ID,
			&i.App.OrgID,
			&i.App.OwnerUserID,
			&i.App.RuntimeNodeID,
			&i.App.Name,
			&i.App.Description,
			&i.App.Status,
			&i.App.ContainerID,
			&i.App.ContainerName,
			&i.App.NewapiKeyID,
			&i.App.NewapiKeyCiphertext,
			&i.App.ApiKeyStatus,
			&i.App.RuntimeSnapshotJson,
			&i.App.RuntimeSnapshotAt,
			&i.App.RestartPolicyJson,
			&i.App.HealthStateJson,
			&i.App.ProgressCurrent,
			&i.App.ProgressTotal,
			&i.App.LastErrorStatus,
			&i.App.LastErrorMessage,
			&i.App.RuntimeImageRef,
			&i.App.RuntimeImageSha256,
			&i.App.NewapiKeyName,
			&i.App.VersionID,
			&i.App.AppliedVersionRevision,
			&i.App.AppliedImageRef,
			&i.App.RuntimeTokenHash,
			&i.App.RuntimeTokenCiphertext,
			&i.App.CreatedAt,
			&i.App.UpdatedAt,
			&i.App.DeletedAt,
			&i.App.OwnerActiveKey,
			&i.App.RuntimeTokenActiveKey,
			&i.VersionRevision,
			&i.VersionImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByRuntimeNode = `-- name: ListAppsByRuntimeNode :many
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, runtime_snapshot_json, runtime_snapshot_at, restart_policy_json, health_state_json, progress_current, progress_total, last_error_status, last_error_message, runtime_image_ref, runtime_image_sha256, newapi_key_name, version_id, applied_version_revision, applied_image_ref, runtime_token_hash, runtime_token_ciphertext, created_at, updated_at, deleted_at, owner_active_key, runtime_token_active_key
FROM apps
WHERE runtime_node_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListAppsByRuntimeNodeParams struct {
	RuntimeNodeID string `db:"runtime_node_id" json:"runtime_node_id"`
	Limit         int32  `db:"limit" json:"limit"`
	Offset        int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListAppsByRuntimeNode(ctx context.Context, arg ListAppsByRuntimeNodeParams) ([]App, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByRuntimeNode, arg.RuntimeNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.RuntimeNodeID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.ContainerID,
			&i.ContainerName,
			&i.NewapiKeyID,
			&i.NewapiKeyCiphertext,
			&i.ApiKeyStatus,
			&i.RuntimeSnapshotJson,
			&i.RuntimeSnapshotAt,
			&i.RestartPolicyJson,
			&i.HealthStateJson,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.LastErrorStatus,
			&i.LastErrorMessage,
			&i.RuntimeImageRef,
			&i.RuntimeImageSha256,
			&i.NewapiKeyName,
			&i.VersionID,
			&i.AppliedVersionRevision,
			&i.AppliedImageRef,
			&i.RuntimeTokenHash,
			&i.RuntimeTokenCiphertext,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OwnerActiveKey,
			&i.RuntimeTokenActiveKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningApps = `-- name: ListRunningApps :many
SELECT id, runtime_node_id, container_id
FROM apps
WHERE deleted_at IS NULL
  AND status IN ('running', 'binding_waiting')
  AND runtime_node_id IS NOT NULL
  AND container_id IS NOT NULL
ORDER BY id
`

type ListRunningAppsRow struct {
	ID            string      `db:"id" json:"id"`
	RuntimeNodeID string      `db:"runtime_node_id" json:"runtime_node_id"`
	ContainerID   null.String `db:"container_id" json:"container_id"`
}

// 列出当前期望持有 runtime 容器的应用，供 scheduler 周期 dispatch
// runtime_refresh_status 与 app_health_check job。
// running 是常态；binding_waiting 表示容器已起但渠道还在登录中，依然要刷指标。
func (q *Queries) ListRunningApps(ctx context.Context) ([]ListRunningAppsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningAppsRow{}
	for rows.Next() {
		var i ListRunningAppsRow
		if err := rows.Scan(&i.ID, &i.RuntimeNodeID, &i.ContainerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleInits = `-- name: ListStaleInits :many
SELECT id, runtime_node_id, status
FROM apps
WHERE deleted_at IS NULL
  AND status IN ('pulling_runtime_image','preparing_runtime','creating_container','starting')
  AND updated_at < ?
ORDER BY id
`

type ListStaleInitsRow struct {
	ID            string `db:"id" json:"id"`
	RuntimeNodeID string `db:"runtime_node_id" json:"runtime_node_id"`
	Status        string `db:"status" json:"status"`
}

// reaper 扫描 init 子状态下连续 90s 无更新的孤儿；阈值由调用方传入。
// 包含新旧两套 init 状态，确保历史孤儿也能被正确清理。
func (q *Queries) ListStaleInits(ctx context.Context, updatedAt time.Time) ([]ListStaleInitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleInits, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleInitsRow{}
	for rows.Next() {
		var i ListStaleInitsRow
		if err := rows.Scan(&i.ID, &i.RuntimeNodeID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAppFailed = `-- name: MarkAppFailed :exec
UPDATE apps
SET status = 'error',
    last_error_status = ?,
    last_error_message = ?,
    progress_current = NULL,
    progress_total = NULL,
    updated_at = now()
WHERE id = ?
`

type MarkAppFailedParams struct {
	LastErrorStatus  null.String `db:"last_error_status" json:"last_error_status"`
	LastErrorMessage null.String `db:"last_error_message" json:"last_error_message"`
	ID               string      `db:"id" json:"id"`
}

// 任意状态 → error 时同时写入来源状态与错误文本，保留"在哪一步失败"与"为什么失败"语义。
// last_error_status 不加 CHECK 约束，值由调用方在 Go 层负责合法性。
func (q *Queries) MarkAppFailed(ctx context.Context, arg MarkAppFailedParams) error {
	_, err := q.db.ExecContext(ctx, markAppFailed, arg.LastErrorStatus, arg.LastErrorMessage, arg.ID)
	return err
}

const setAppAppliedVersion = `-- name: SetAppAppliedVersion :exec
UPDATE apps
SET applied_version_revision = ?,
    applied_image_ref = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppAppliedVersionParams struct {
	AppliedVersionRevision int32  `db:"applied_version_revision" json:"applied_version_revision"`
	AppliedImageRef        string `db:"applied_image_ref" json:"applied_image_ref"`
	ID                     string `db:"id" json:"id"`
}

// 初始化/重启成功后记录已应用的版本修订与镜像 ref，用于 version_synced 检测。
func (q *Queries) SetAppAppliedVersion(ctx context.Context, arg SetAppAppliedVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAppAppliedVersion, arg.AppliedVersionRevision, arg.AppliedImageRef, arg.ID)
	return err
}

const setAppContainer = `-- name: SetAppContainer :exec
UPDATE apps
SET container_id = ?, container_name = ?, updated_at = now()
WHERE id = ?
`

type SetAppContainerParams struct {
	ContainerID   null.String `db:"container_id" json:"container_id"`
	ContainerName null.String `db:"container_name" json:"container_name"`
	ID            string      `db:"id" json:"id"`
}

func (q *Queries) SetAppContainer(ctx context.Context, arg SetAppContainerParams) error {
	_, err := q.db.ExecContext(ctx, setAppContainer, arg.ContainerID, arg.ContainerName, arg.ID)
	return err
}

const setAppHealthState = `-- name: SetAppHealthState :exec
UPDATE apps
SET health_state_json = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppHealthStateParams struct {
	HealthStateJson json.RawMessage `db:"health_state_json" json:"health_state_json"`
	ID              string          `db:"id" json:"id"`
}

// worker app_health_check handler 写最近一次健康检查结果；用于自动重启窗口计数。
func (q *Queries) SetAppHealthState(ctx context.Context, arg SetAppHealthStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppHealthState, arg.HealthStateJson, arg.ID)
	return err
}

const setAppNewAPIKey = `-- name: SetAppNewAPIKey :exec
UPDATE apps
SET
    newapi_key_id = ?,
    newapi_key_ciphertext = ?,
    api_key_status = ?,
    newapi_key_name = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppNewAPIKeyParams struct {
	NewapiKeyID         null.String `db:"newapi_key_id" json:"newapi_key_id"`
	NewapiKeyCiphertext null.String `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus        string      `db:"api_key_status" json:"api_key_status"`
	NewapiKeyName       null.String `db:"newapi_key_name" json:"newapi_key_name"`
	ID                  string      `db:"id" json:"id"`
}

func (q *Queries) SetAppNewAPIKey(ctx context.Context, arg SetAppNewAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAppNewAPIKey,
		arg.NewapiKeyID,
		arg.NewapiKeyCiphertext,
		arg.ApiKeyStatus,
		arg.NewapiKeyName,
		arg.ID,
	)
	return err
}

const setAppProgress = `-- name: SetAppProgress :exec
UPDATE apps
SET progress_current = ?,
    progress_total = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppProgressParams struct {
	ProgressCurrent null.Int `db:"progress_current" json:"progress_current"`
	ProgressTotal   null.Int `db:"progress_total" json:"progress_total"`
	ID              string   `db:"id" json:"id"`
}

// progressReporter 节流后写入；NULL/NULL 表示阶段切换或未知。
func (q *Queries) SetAppProgress(ctx context.Context, arg SetAppProgressParams) error {
	_, err := q.db.ExecContext(ctx, setAppProgress, arg.ProgressCurrent, arg.ProgressTotal, arg.ID)
	return err
}

const setAppRestartPolicy = `-- name: SetAppRestartPolicy :exec
UPDATE apps
SET restart_policy_json = ?,
    updated_at = now()
WHERE id = ?
`

type SetAppRestartPolicyParams struct {
	RestartPolicyJson json.RawMessage `db:"restart_policy_json" json:"restart_policy_json"`
	ID                string          `db:"id" json:"id"`
}

// 管理员 PATCH /apps/:appId/restart-policy 写入；mode/max_per_window/window_seconds 校验在 service 层。
func (q *Queries) SetAppRestartPolicy(ctx context.Context, arg SetAppRestartPolicyParams) error {
	_, err := q.db.ExecContext(ctx, setAppRestartPolicy, arg.RestartPolicyJson, arg.ID)
	return err
}

const setAppRuntimeSnapshot = `-- name: SetAppRuntimeSnapshot :exec
UPDATE apps
SET runtime_snapshot_json = ?,
    runtime_snapshot_at = now(),
    updated_at = now()
WHERE id = ?
`

type SetAppRuntimeSnapshotParams struct {
	RuntimeSnapshotJson json.RawMessage `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
	ID                  string          `db:"id" json:"id"`
}

func (q *Queries) SetAppRuntimeSnapshot(ctx context.Context, arg SetAppRuntimeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, setAppRuntimeSnapshot, arg.RuntimeSnapshotJson, arg.ID)
	return err
}

const setAppRuntimeToken = `-- name: SetAppRuntimeToken :exec
UPDATE apps
SET runtime_token_hash = ?,
    runtime_token_ciphertext = ?,
    updated_at = now()
WHERE id = ?
  AND deleted_at IS NULL
  AND runtime_token_hash IS NULL
  AND runtime_token_ciphertext IS NULL
`

type SetAppRuntimeTokenParams struct {
	RuntimeTokenHash       null.String `db:"runtime_token_hash" json:"runtime_token_hash"`
	RuntimeTokenCiphertext null.String `db:"runtime_token_ciphertext" json:"runtime_token_ciphertext"`
	ID                     string      `db:"id" json:"id"`
}

// 首次写入 Hermes 调 manager runtime API 的 app 级 token；并发重复初始化拿不到行，由 service 读取既有 token。
func (q *Queries) SetAppRuntimeToken(ctx context.Context, arg SetAppRuntimeTokenParams) error {
	_, err := q.db.ExecContext(ctx, setAppRuntimeToken, arg.RuntimeTokenHash, arg.RuntimeTokenCiphertext, arg.ID)
	return err
}

const setAppStatus = `-- name: SetAppStatus :exec
UPDATE apps
SET status = ?, updated_at = now()
WHERE id = ?
`

type SetAppStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetAppStatus(ctx context.Context, arg SetAppStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAppStatus, arg.Status, arg.ID)
	return err
}

const setAppVersion = `-- name: SetAppVersion :exec
UPDATE apps
SET version_id = ?,
    applied_version_revision = 0,
    applied_image_ref = '',
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type SetAppVersionParams struct {
	VersionID null.String `db:"version_id" json:"version_id"`
	ID        string      `db:"id" json:"id"`
}

// 切换实例绑定的助手版本，并把 applied_version_revision / applied_image_ref 清零。
// 不同版本各自维护独立的 revision 计数，若切换后保留旧 applied_*，当新旧版本
// 的 revision 数字恰好相同（且镜像相同）时 version_synced 会误判为已同步。
// 清零后 applied_version_revision=0 永远不等于任何真实版本 revision（从 1 起），
// 实例切换后必然进入需重启态，直到重启重新写入 applied_*。
func (q *Queries) SetAppVersion(ctx context.Context, arg SetAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, setAppVersion, arg.VersionID, arg.ID)
	return err
}

const softDeleteApp = `-- name: SoftDeleteApp :exec
UPDATE apps
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteApp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteApp, id)
	return err
}

const updateAppRuntimeImage = `-- name: UpdateAppRuntimeImage :exec
UPDATE apps
SET
    runtime_image_ref    = ?,
    runtime_image_sha256 = ?,
    updated_at = now()
WHERE id = ?
`

type UpdateAppRuntimeImageParams struct {
	RuntimeImageRef    string `db:"runtime_image_ref" json:"runtime_image_ref"`
	RuntimeImageSha256 string `db:"runtime_image_sha256" json:"runtime_image_sha256"`
	ID                 string `db:"id" json:"id"`
}

// phasePullRuntimeImage 成功后写入镜像引用与 sha256。
func (q *Queries) UpdateAppRuntimeImage(ctx context.Context, arg UpdateAppRuntimeImageParams) error {
	_, err := q.db.ExecContext(ctx, updateAppRuntimeImage, arg.RuntimeImageRef, arg.RuntimeImageSha256, arg.ID)
	return err
}
