// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    org_id,
    owner_user_id,
    runtime_node_id,
    name,
    description,
    status,
    persona_mode,
    app_prompt,
    api_key_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

type CreateAppParams struct {
	OrgID         pgtype.UUID `db:"org_id" json:"org_id"`
	OwnerUserID   pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
	RuntimeNodeID pgtype.UUID `db:"runtime_node_id" json:"runtime_node_id"`
	Name          string      `db:"name" json:"name"`
	Description   pgtype.Text `db:"description" json:"description"`
	Status        string      `db:"status" json:"status"`
	PersonaMode   string      `db:"persona_mode" json:"persona_mode"`
	AppPrompt     pgtype.Text `db:"app_prompt" json:"app_prompt"`
	ApiKeyStatus  string      `db:"api_key_status" json:"api_key_status"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.OrgID,
		arg.OwnerUserID,
		arg.RuntimeNodeID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.PersonaMode,
		arg.AppPrompt,
		arg.ApiKeyStatus,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const getActiveAppByOwner = `-- name: GetActiveAppByOwner :one
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
FROM apps
WHERE owner_user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetActiveAppByOwner(ctx context.Context, ownerUserID pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getActiveAppByOwner, ownerUserID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
FROM apps
WHERE id = $1
`

func (q *Queries) GetApp(ctx context.Context, id pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const listAppsByOrg = `-- name: ListAppsByOrg :many
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
FROM apps
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAppsByOrgParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAppsByOrg(ctx context.Context, arg ListAppsByOrgParams) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.RuntimeNodeID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.PersonaMode,
			&i.AppPrompt,
			&i.ContainerID,
			&i.ContainerName,
			&i.NewapiKeyID,
			&i.NewapiKeyCiphertext,
			&i.ApiKeyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RuntimeSnapshotJson,
			&i.RuntimeSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppsByRuntimeNode = `-- name: ListAppsByRuntimeNode :many
SELECT id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
FROM apps
WHERE runtime_node_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAppsByRuntimeNodeParams struct {
	RuntimeNodeID pgtype.UUID `db:"runtime_node_id" json:"runtime_node_id"`
	Limit         int32       `db:"limit" json:"limit"`
	Offset        int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListAppsByRuntimeNode(ctx context.Context, arg ListAppsByRuntimeNodeParams) ([]App, error) {
	rows, err := q.db.Query(ctx, listAppsByRuntimeNode, arg.RuntimeNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []App{}
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OwnerUserID,
			&i.RuntimeNodeID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.PersonaMode,
			&i.AppPrompt,
			&i.ContainerID,
			&i.ContainerName,
			&i.NewapiKeyID,
			&i.NewapiKeyCiphertext,
			&i.ApiKeyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RuntimeSnapshotJson,
			&i.RuntimeSnapshotAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningApps = `-- name: ListRunningApps :many
SELECT id, runtime_node_id, container_id
FROM apps
WHERE deleted_at IS NULL
  AND status IN ('running', 'binding_waiting')
  AND runtime_node_id IS NOT NULL
  AND container_id IS NOT NULL
ORDER BY id
`

type ListRunningAppsRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	RuntimeNodeID pgtype.UUID `db:"runtime_node_id" json:"runtime_node_id"`
	ContainerID   pgtype.Text `db:"container_id" json:"container_id"`
}

// 列出当前期望持有 OpenClaw 容器的应用，供 scheduler 周期 dispatch
// runtime_refresh_status 与 app_health_check job。
// running 是常态；binding_waiting 表示容器已起但渠道还在登录中，依然要刷指标。
func (q *Queries) ListRunningApps(ctx context.Context) ([]ListRunningAppsRow, error) {
	rows, err := q.db.Query(ctx, listRunningApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunningAppsRow{}
	for rows.Next() {
		var i ListRunningAppsRow
		if err := rows.Scan(&i.ID, &i.RuntimeNodeID, &i.ContainerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppContainer = `-- name: SetAppContainer :one
UPDATE apps
SET container_id = $2, container_name = $3, updated_at = now()
WHERE id = $1
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

type SetAppContainerParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	ContainerID   pgtype.Text `db:"container_id" json:"container_id"`
	ContainerName pgtype.Text `db:"container_name" json:"container_name"`
}

func (q *Queries) SetAppContainer(ctx context.Context, arg SetAppContainerParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppContainer, arg.ID, arg.ContainerID, arg.ContainerName)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const setAppNewAPIKey = `-- name: SetAppNewAPIKey :one
UPDATE apps
SET
    newapi_key_id = $2,
    newapi_key_ciphertext = $3,
    api_key_status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

type SetAppNewAPIKeyParams struct {
	ID                  pgtype.UUID `db:"id" json:"id"`
	NewapiKeyID         pgtype.Text `db:"newapi_key_id" json:"newapi_key_id"`
	NewapiKeyCiphertext pgtype.Text `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus        string      `db:"api_key_status" json:"api_key_status"`
}

func (q *Queries) SetAppNewAPIKey(ctx context.Context, arg SetAppNewAPIKeyParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppNewAPIKey,
		arg.ID,
		arg.NewapiKeyID,
		arg.NewapiKeyCiphertext,
		arg.ApiKeyStatus,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const setAppRuntimeSnapshot = `-- name: SetAppRuntimeSnapshot :one
UPDATE apps
SET runtime_snapshot_json = $2,
    runtime_snapshot_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

type SetAppRuntimeSnapshotParams struct {
	ID                  pgtype.UUID `db:"id" json:"id"`
	RuntimeSnapshotJson []byte      `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
}

func (q *Queries) SetAppRuntimeSnapshot(ctx context.Context, arg SetAppRuntimeSnapshotParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppRuntimeSnapshot, arg.ID, arg.RuntimeSnapshotJson)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const setAppStatus = `-- name: SetAppStatus :one
UPDATE apps
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

type SetAppStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) SetAppStatus(ctx context.Context, arg SetAppStatusParams) (App, error) {
	row := q.db.QueryRow(ctx, setAppStatus, arg.ID, arg.Status)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}

const softDeleteApp = `-- name: SoftDeleteApp :one
UPDATE apps
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, owner_user_id, runtime_node_id, name, description, status, persona_mode, app_prompt, container_id, container_name, newapi_key_id, newapi_key_ciphertext, api_key_status, created_at, updated_at, deleted_at, runtime_snapshot_json, runtime_snapshot_at
`

func (q *Queries) SoftDeleteApp(ctx context.Context, id pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, softDeleteApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OwnerUserID,
		&i.RuntimeNodeID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.PersonaMode,
		&i.AppPrompt,
		&i.ContainerID,
		&i.ContainerName,
		&i.NewapiKeyID,
		&i.NewapiKeyCiphertext,
		&i.ApiKeyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RuntimeSnapshotJson,
		&i.RuntimeSnapshotAt,
	)
	return i, err
}
