// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant_versions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppsUsingVersion = `-- name: CountAppsUsingVersion :one
SELECT count(*) FROM apps
WHERE version_id = $1 AND deleted_at IS NULL
`

// 严格保护：版本被未删除实例引用时不可删除。
func (q *Queries) CountAppsUsingVersion(ctx context.Context, versionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAppsUsingVersion, versionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsUsingVersion = `-- name: CountOrgsUsingVersion :one
SELECT count(*) FROM organizations
WHERE deleted_at IS NULL AND jsonb_exists(assistant_version_ids, $1)
`

// 严格保护：版本出现在任意未删除组织 allowlist 时不可删除。
func (q *Queries) CountOrgsUsingVersion(ctx context.Context, jsonbExists string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgsUsingVersion, jsonbExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssistantVersion = `-- name: CreateAssistantVersion :one
INSERT INTO assistant_versions (
    name, description, system_prompt, image_id, main_model,
    routing_json, skills_json, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at
`

type CreateAssistantVersionParams struct {
	Name         string      `db:"name" json:"name"`
	Description  string      `db:"description" json:"description"`
	SystemPrompt string      `db:"system_prompt" json:"system_prompt"`
	ImageID      string      `db:"image_id" json:"image_id"`
	MainModel    string      `db:"main_model" json:"main_model"`
	RoutingJson  []byte      `db:"routing_json" json:"routing_json"`
	SkillsJson   []byte      `db:"skills_json" json:"skills_json"`
	CreatedBy    pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAssistantVersion(ctx context.Context, arg CreateAssistantVersionParams) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, createAssistantVersion,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ImageID,
		arg.MainModel,
		arg.RoutingJson,
		arg.SkillsJson,
		arg.CreatedBy,
	)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssistantVersion = `-- name: GetAssistantVersion :one
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at FROM assistant_versions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAssistantVersion(ctx context.Context, id pgtype.UUID) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, getAssistantVersion, id)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssistantVersionByName = `-- name: GetAssistantVersionByName :one
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at FROM assistant_versions
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAssistantVersionByName(ctx context.Context, name string) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, getAssistantVersionByName, name)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssistantVersions = `-- name: ListAssistantVersions :many
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at FROM assistant_versions
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAssistantVersions(ctx context.Context) ([]AssistantVersion, error) {
	rows, err := q.db.Query(ctx, listAssistantVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantVersion{}
	for rows.Next() {
		var i AssistantVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ImageID,
			&i.MainModel,
			&i.RoutingJson,
			&i.SkillsJson,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAssistantVersion = `-- name: SoftDeleteAssistantVersion :one
UPDATE assistant_versions
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteAssistantVersion(ctx context.Context, id pgtype.UUID) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, softDeleteAssistantVersion, id)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAssistantVersion = `-- name: UpdateAssistantVersion :one
UPDATE assistant_versions
SET name = $2,
    description = $3,
    system_prompt = $4,
    image_id = $5,
    main_model = $6,
    routing_json = $7,
    skills_json = $8,
    revision = $9,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at
`

type UpdateAssistantVersionParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Name         string      `db:"name" json:"name"`
	Description  string      `db:"description" json:"description"`
	SystemPrompt string      `db:"system_prompt" json:"system_prompt"`
	ImageID      string      `db:"image_id" json:"image_id"`
	MainModel    string      `db:"main_model" json:"main_model"`
	RoutingJson  []byte      `db:"routing_json" json:"routing_json"`
	SkillsJson   []byte      `db:"skills_json" json:"skills_json"`
	Revision     int32       `db:"revision" json:"revision"`
}

// revision 由 service 计算后整体写入（仅容器相关字段变更才递增）。
func (q *Queries) UpdateAssistantVersion(ctx context.Context, arg UpdateAssistantVersionParams) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, updateAssistantVersion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ImageID,
		arg.MainModel,
		arg.RoutingJson,
		arg.SkillsJson,
		arg.Revision,
	)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAssistantVersionSkills = `-- name: UpdateAssistantVersionSkills :one
UPDATE assistant_versions
SET skills_json = $2,
    revision = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at
`

type UpdateAssistantVersionSkillsParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	SkillsJson []byte      `db:"skills_json" json:"skills_json"`
	Revision   int32       `db:"revision" json:"revision"`
}

// skill 上传/删除单独走此查询：只改 skills_json 与 revision，避免覆盖其它字段。
func (q *Queries) UpdateAssistantVersionSkills(ctx context.Context, arg UpdateAssistantVersionSkillsParams) (AssistantVersion, error) {
	row := q.db.QueryRow(ctx, updateAssistantVersionSkills, arg.ID, arg.SkillsJson, arg.Revision)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
