// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assistant_versions.sql

package sqlc

import (
	"context"
	"encoding/json"

	null "github.com/guregu/null/v5"
)

const countAppsUsingVersion = `-- name: CountAppsUsingVersion :one
SELECT count(*) FROM apps
WHERE version_id = ? AND deleted_at IS NULL
`

// 严格保护：版本被未删除实例引用时不可删除。
func (q *Queries) CountAppsUsingVersion(ctx context.Context, versionID null.String) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppsUsingVersion, versionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsUsingVersion = `-- name: CountOrgsUsingVersion :one
SELECT count(*) FROM organizations
WHERE deleted_at IS NULL AND JSON_CONTAINS(assistant_version_ids, JSON_QUOTE(?))
`

// 严格保护：版本出现在任意未删除组织 allowlist 时不可删除。
func (q *Queries) CountOrgsUsingVersion(ctx context.Context, jsonQUOTE string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgsUsingVersion, jsonQUOTE)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssistantVersion = `-- name: CreateAssistantVersion :exec
INSERT INTO assistant_versions (
    id, name, description, system_prompt, image_id, main_model,
    routing_json, skills_json, created_by
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAssistantVersionParams struct {
	ID           string          `db:"id" json:"id"`
	Name         string          `db:"name" json:"name"`
	Description  string          `db:"description" json:"description"`
	SystemPrompt string          `db:"system_prompt" json:"system_prompt"`
	ImageID      string          `db:"image_id" json:"image_id"`
	MainModel    string          `db:"main_model" json:"main_model"`
	RoutingJson  json.RawMessage `db:"routing_json" json:"routing_json"`
	SkillsJson   json.RawMessage `db:"skills_json" json:"skills_json"`
	CreatedBy    null.String     `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAssistantVersion(ctx context.Context, arg CreateAssistantVersionParams) error {
	_, err := q.db.ExecContext(ctx, createAssistantVersion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ImageID,
		arg.MainModel,
		arg.RoutingJson,
		arg.SkillsJson,
		arg.CreatedBy,
	)
	return err
}

const getAssistantVersion = `-- name: GetAssistantVersion :one
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at, name_active_key FROM assistant_versions
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAssistantVersion(ctx context.Context, id string) (AssistantVersion, error) {
	row := q.db.QueryRowContext(ctx, getAssistantVersion, id)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NameActiveKey,
	)
	return i, err
}

const getAssistantVersionByName = `-- name: GetAssistantVersionByName :one
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at, name_active_key FROM assistant_versions
WHERE name = ? AND deleted_at IS NULL
`

func (q *Queries) GetAssistantVersionByName(ctx context.Context, name string) (AssistantVersion, error) {
	row := q.db.QueryRowContext(ctx, getAssistantVersionByName, name)
	var i AssistantVersion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ImageID,
		&i.MainModel,
		&i.RoutingJson,
		&i.SkillsJson,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.NameActiveKey,
	)
	return i, err
}

const listAssistantVersions = `-- name: ListAssistantVersions :many
SELECT id, name, description, system_prompt, image_id, main_model, routing_json, skills_json, revision, created_by, created_at, updated_at, deleted_at, name_active_key FROM assistant_versions
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAssistantVersions(ctx context.Context) ([]AssistantVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAssistantVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantVersion{}
	for rows.Next() {
		var i AssistantVersion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ImageID,
			&i.MainModel,
			&i.RoutingJson,
			&i.SkillsJson,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.NameActiveKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAssistantVersion = `-- name: SoftDeleteAssistantVersion :exec
UPDATE assistant_versions
SET deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAssistantVersion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteAssistantVersion, id)
	return err
}

const updateAssistantVersion = `-- name: UpdateAssistantVersion :exec
UPDATE assistant_versions
SET name = ?,
    description = ?,
    system_prompt = ?,
    image_id = ?,
    main_model = ?,
    routing_json = ?,
    skills_json = ?,
    revision = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAssistantVersionParams struct {
	Name         string          `db:"name" json:"name"`
	Description  string          `db:"description" json:"description"`
	SystemPrompt string          `db:"system_prompt" json:"system_prompt"`
	ImageID      string          `db:"image_id" json:"image_id"`
	MainModel    string          `db:"main_model" json:"main_model"`
	RoutingJson  json.RawMessage `db:"routing_json" json:"routing_json"`
	SkillsJson   json.RawMessage `db:"skills_json" json:"skills_json"`
	Revision     int32           `db:"revision" json:"revision"`
	ID           string          `db:"id" json:"id"`
}

// revision 由 service 计算后整体写入（仅容器相关字段变更才递增）。
func (q *Queries) UpdateAssistantVersion(ctx context.Context, arg UpdateAssistantVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateAssistantVersion,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ImageID,
		arg.MainModel,
		arg.RoutingJson,
		arg.SkillsJson,
		arg.Revision,
		arg.ID,
	)
	return err
}

const updateAssistantVersionSkills = `-- name: UpdateAssistantVersionSkills :exec
UPDATE assistant_versions
SET skills_json = ?,
    revision = ?,
    updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAssistantVersionSkillsParams struct {
	SkillsJson json.RawMessage `db:"skills_json" json:"skills_json"`
	Revision   int32           `db:"revision" json:"revision"`
	ID         string          `db:"id" json:"id"`
}

// skill 上传/删除单独走此查询：只改 skills_json 与 revision，避免覆盖其它字段。
func (q *Queries) UpdateAssistantVersionSkills(ctx context.Context, arg UpdateAssistantVersionSkillsParams) error {
	_, err := q.db.ExecContext(ctx, updateAssistantVersionSkills, arg.SkillsJson, arg.Revision, arg.ID)
	return err
}
