// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	null "github.com/guregu/null/v5"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id,
    actor_id,
    actor_role,
    org_id,
    target_type,
    target_id,
    action,
    result,
    error_message,
    ip_address,
    metadata_json,
    detail_message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAuditLogParams struct {
	ID            string          `db:"id" json:"id"`
	ActorID       null.String     `db:"actor_id" json:"actor_id"`
	ActorRole     string          `db:"actor_role" json:"actor_role"`
	OrgID         null.String     `db:"org_id" json:"org_id"`
	TargetType    string          `db:"target_type" json:"target_type"`
	TargetID      string          `db:"target_id" json:"target_id"`
	Action        string          `db:"action" json:"action"`
	Result        string          `db:"result" json:"result"`
	ErrorMessage  null.String     `db:"error_message" json:"error_message"`
	IpAddress     null.String     `db:"ip_address" json:"ip_address"`
	MetadataJson  json.RawMessage `db:"metadata_json" json:"metadata_json"`
	DetailMessage null.String     `db:"detail_message" json:"detail_message"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.ActorID,
		arg.ActorRole,
		arg.OrgID,
		arg.TargetType,
		arg.TargetID,
		arg.Action,
		arg.Result,
		arg.ErrorMessage,
		arg.IpAddress,
		arg.MetadataJson,
		arg.DetailMessage,
	)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, actor_id, actor_role, org_id, target_type, target_id, action, result, error_message, ip_address, metadata_json, detail_message, created_at
FROM audit_logs
WHERE id = ?
`

func (q *Queries) GetAuditLog(ctx context.Context, id string) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, getAuditLog, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorRole,
		&i.OrgID,
		&i.TargetType,
		&i.TargetID,
		&i.Action,
		&i.Result,
		&i.ErrorMessage,
		&i.IpAddress,
		&i.MetadataJson,
		&i.DetailMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT
    al.id,
    al.actor_id,
    al.actor_role,
    al.org_id,
    al.target_type,
    al.target_id,
    al.action,
    al.result,
    al.error_message,
    al.ip_address,
    al.metadata_json,
    al.created_at,
    al.detail_message,
    COALESCE(NULLIF(au.display_name, ''), au.username, '')          AS actor_name,
    COALESCE(au.deleted_at IS NOT NULL, false)                       AS actor_deleted,
    COALESCE(
        (SELECT a.name FROM apps a
            WHERE al.target_type = 'app' AND a.id = al.target_id),
        (SELECT o.name FROM organizations o
            WHERE al.target_type = 'organization' AND o.id = al.target_id),
        (SELECT COALESCE(NULLIF(tu.display_name, ''), tu.username) FROM users tu
            WHERE al.target_type IN ('user', 'member') AND tu.id = al.target_id),
        (SELECT n.name FROM runtime_nodes n
            WHERE al.target_type = 'runtime_node' AND n.id = al.target_id)
    ) AS target_name,
    COALESCE(
        (SELECT a.deleted_at IS NOT NULL FROM apps a
            WHERE al.target_type = 'app' AND a.id = al.target_id),
        (SELECT o.deleted_at IS NOT NULL FROM organizations o
            WHERE al.target_type = 'organization' AND o.id = al.target_id),
        (SELECT tu.deleted_at IS NOT NULL FROM users tu
            WHERE al.target_type IN ('user', 'member') AND tu.id = al.target_id),
        false
    ) AS target_deleted
FROM audit_logs al
LEFT JOIN users au ON au.id = al.actor_id
WHERE al.org_id = ?
ORDER BY al.created_at DESC, al.id DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByOrgParams struct {
	OrgID  null.String `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListAuditLogsByOrgRow struct {
	ID            string          `db:"id" json:"id"`
	ActorID       null.String     `db:"actor_id" json:"actor_id"`
	ActorRole     string          `db:"actor_role" json:"actor_role"`
	OrgID         null.String     `db:"org_id" json:"org_id"`
	TargetType    string          `db:"target_type" json:"target_type"`
	TargetID      string          `db:"target_id" json:"target_id"`
	Action        string          `db:"action" json:"action"`
	Result        string          `db:"result" json:"result"`
	ErrorMessage  null.String     `db:"error_message" json:"error_message"`
	IpAddress     null.String     `db:"ip_address" json:"ip_address"`
	MetadataJson  json.RawMessage `db:"metadata_json" json:"metadata_json"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	DetailMessage null.String     `db:"detail_message" json:"detail_message"`
	ActorName     string          `db:"actor_name" json:"actor_name"`
	ActorDeleted  interface{}     `db:"actor_deleted" json:"actor_deleted"`
	TargetName    interface{}     `db:"target_name" json:"target_name"`
	TargetDeleted interface{}     `db:"target_deleted" json:"target_deleted"`
}

// 返回审计行 + actor 实时名称 + target 实时名称（按 target_type 走子查询）。
// 子查询里 WHERE al.target_type = X 保证 newapi_call 的 endpoint 字符串
// 永不被尝试转 UUID，避开 cast error。
func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]ListAuditLogsByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByOrgRow{}
	for rows.Next() {
		var i ListAuditLogsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.OrgID,
			&i.TargetType,
			&i.TargetID,
			&i.Action,
			&i.Result,
			&i.ErrorMessage,
			&i.IpAddress,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.DetailMessage,
			&i.ActorName,
			&i.ActorDeleted,
			&i.TargetName,
			&i.TargetDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTarget = `-- name: ListAuditLogsByTarget :many
SELECT
    al.id,
    al.actor_id,
    al.actor_role,
    al.org_id,
    al.target_type,
    al.target_id,
    al.action,
    al.result,
    al.error_message,
    al.ip_address,
    al.metadata_json,
    al.created_at,
    al.detail_message,
    COALESCE(NULLIF(au.display_name, ''), au.username, '')          AS actor_name,
    COALESCE(au.deleted_at IS NOT NULL, false)                       AS actor_deleted,
    COALESCE(
        (SELECT a.name FROM apps a
            WHERE al.target_type = 'app' AND a.id = al.target_id),
        (SELECT o.name FROM organizations o
            WHERE al.target_type = 'organization' AND o.id = al.target_id),
        (SELECT COALESCE(NULLIF(tu.display_name, ''), tu.username) FROM users tu
            WHERE al.target_type IN ('user', 'member') AND tu.id = al.target_id),
        (SELECT n.name FROM runtime_nodes n
            WHERE al.target_type = 'runtime_node' AND n.id = al.target_id)
    ) AS target_name,
    COALESCE(
        (SELECT a.deleted_at IS NOT NULL FROM apps a
            WHERE al.target_type = 'app' AND a.id = al.target_id),
        (SELECT o.deleted_at IS NOT NULL FROM organizations o
            WHERE al.target_type = 'organization' AND o.id = al.target_id),
        (SELECT tu.deleted_at IS NOT NULL FROM users tu
            WHERE al.target_type IN ('user', 'member') AND tu.id = al.target_id),
        false
    ) AS target_deleted
FROM audit_logs al
LEFT JOIN users au ON au.id = al.actor_id
WHERE al.target_type = ? AND al.target_id = ?
ORDER BY al.created_at DESC, al.id DESC
LIMIT ? OFFSET ?
`

type ListAuditLogsByTargetParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	Limit      int32  `db:"limit" json:"limit"`
	Offset     int32  `db:"offset" json:"offset"`
}

type ListAuditLogsByTargetRow struct {
	ID            string          `db:"id" json:"id"`
	ActorID       null.String     `db:"actor_id" json:"actor_id"`
	ActorRole     string          `db:"actor_role" json:"actor_role"`
	OrgID         null.String     `db:"org_id" json:"org_id"`
	TargetType    string          `db:"target_type" json:"target_type"`
	TargetID      string          `db:"target_id" json:"target_id"`
	Action        string          `db:"action" json:"action"`
	Result        string          `db:"result" json:"result"`
	ErrorMessage  null.String     `db:"error_message" json:"error_message"`
	IpAddress     null.String     `db:"ip_address" json:"ip_address"`
	MetadataJson  json.RawMessage `db:"metadata_json" json:"metadata_json"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	DetailMessage null.String     `db:"detail_message" json:"detail_message"`
	ActorName     string          `db:"actor_name" json:"actor_name"`
	ActorDeleted  interface{}     `db:"actor_deleted" json:"actor_deleted"`
	TargetName    interface{}     `db:"target_name" json:"target_name"`
	TargetDeleted interface{}     `db:"target_deleted" json:"target_deleted"`
}

// 同 ListAuditLogsByOrg，按 target_type + target_id 过滤。
func (q *Queries) ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]ListAuditLogsByTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByTarget,
		arg.TargetType,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsByTargetRow{}
	for rows.Next() {
		var i ListAuditLogsByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorRole,
			&i.OrgID,
			&i.TargetType,
			&i.TargetID,
			&i.Action,
			&i.Result,
			&i.ErrorMessage,
			&i.IpAddress,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.DetailMessage,
			&i.ActorName,
			&i.ActorDeleted,
			&i.TargetName,
			&i.TargetDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
