// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannelBindingsByApp = `-- name: CountChannelBindingsByApp :one
SELECT COUNT(*)::bigint AS count
FROM channel_bindings
WHERE app_id = $1 AND status <> 'deleted'
`

// 统计指定应用下未被标记为 deleted 的渠道绑定数。
// RuntimeOperationService.Trigger 在写 delete 审计前调用，把数量塞进 detail_message。
func (q *Queries) CountChannelBindingsByApp(ctx context.Context, appID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelBindingsByApp, appID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelBinding = `-- name: CreateChannelBinding :one
INSERT INTO channel_bindings (
    app_id,
    channel_type,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, app_id, channel_type, status, bound_identity, channel_name, metadata_json, bound_at, last_online_at, last_error, created_at, updated_at
`

type CreateChannelBindingParams struct {
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType string      `db:"channel_type" json:"channel_type"`
	Status      string      `db:"status" json:"status"`
}

func (q *Queries) CreateChannelBinding(ctx context.Context, arg CreateChannelBindingParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, createChannelBinding, arg.AppID, arg.ChannelType, arg.Status)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelType,
		&i.Status,
		&i.BoundIdentity,
		&i.ChannelName,
		&i.MetadataJson,
		&i.BoundAt,
		&i.LastOnlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBindingByAppAndType = `-- name: GetChannelBindingByAppAndType :one
SELECT id, app_id, channel_type, status, bound_identity, channel_name, metadata_json, bound_at, last_online_at, last_error, created_at, updated_at
FROM channel_bindings
WHERE app_id = $1 AND channel_type = $2 AND status <> 'deleted'
`

type GetChannelBindingByAppAndTypeParams struct {
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType string      `db:"channel_type" json:"channel_type"`
}

func (q *Queries) GetChannelBindingByAppAndType(ctx context.Context, arg GetChannelBindingByAppAndTypeParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, getChannelBindingByAppAndType, arg.AppID, arg.ChannelType)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelType,
		&i.Status,
		&i.BoundIdentity,
		&i.ChannelName,
		&i.MetadataJson,
		&i.BoundAt,
		&i.LastOnlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markChannelBindingBound = `-- name: MarkChannelBindingBound :one
UPDATE channel_bindings
SET
    status = 'bound',
    bound_identity = $3,
    channel_name = $4,
    metadata_json = $5,
    bound_at = now(),
    last_error = NULL,
    updated_at = now()
WHERE app_id = $1 AND channel_type = $2 AND status <> 'deleted'
RETURNING id, app_id, channel_type, status, bound_identity, channel_name, metadata_json, bound_at, last_online_at, last_error, created_at, updated_at
`

type MarkChannelBindingBoundParams struct {
	AppID         pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType   string      `db:"channel_type" json:"channel_type"`
	BoundIdentity pgtype.Text `db:"bound_identity" json:"bound_identity"`
	ChannelName   pgtype.Text `db:"channel_name" json:"channel_name"`
	MetadataJson  []byte      `db:"metadata_json" json:"metadata_json"`
}

func (q *Queries) MarkChannelBindingBound(ctx context.Context, arg MarkChannelBindingBoundParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, markChannelBindingBound,
		arg.AppID,
		arg.ChannelType,
		arg.BoundIdentity,
		arg.ChannelName,
		arg.MetadataJson,
	)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelType,
		&i.Status,
		&i.BoundIdentity,
		&i.ChannelName,
		&i.MetadataJson,
		&i.BoundAt,
		&i.LastOnlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setChannelBindingChallenge = `-- name: SetChannelBindingChallenge :one
UPDATE channel_bindings
SET status = 'pending_auth', metadata_json = $3, last_error = NULL, updated_at = now()
WHERE app_id = $1 AND channel_type = $2 AND status <> 'deleted'
RETURNING id, app_id, channel_type, status, bound_identity, channel_name, metadata_json, bound_at, last_online_at, last_error, created_at, updated_at
`

type SetChannelBindingChallengeParams struct {
	AppID        pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType  string      `db:"channel_type" json:"channel_type"`
	MetadataJson []byte      `db:"metadata_json" json:"metadata_json"`
}

func (q *Queries) SetChannelBindingChallenge(ctx context.Context, arg SetChannelBindingChallengeParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, setChannelBindingChallenge, arg.AppID, arg.ChannelType, arg.MetadataJson)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelType,
		&i.Status,
		&i.BoundIdentity,
		&i.ChannelName,
		&i.MetadataJson,
		&i.BoundAt,
		&i.LastOnlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setChannelBindingStatus = `-- name: SetChannelBindingStatus :one
UPDATE channel_bindings
SET status = $3, last_error = $4, updated_at = now()
WHERE app_id = $1 AND channel_type = $2 AND status <> 'deleted'
RETURNING id, app_id, channel_type, status, bound_identity, channel_name, metadata_json, bound_at, last_online_at, last_error, created_at, updated_at
`

type SetChannelBindingStatusParams struct {
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType string      `db:"channel_type" json:"channel_type"`
	Status      string      `db:"status" json:"status"`
	LastError   pgtype.Text `db:"last_error" json:"last_error"`
}

func (q *Queries) SetChannelBindingStatus(ctx context.Context, arg SetChannelBindingStatusParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, setChannelBindingStatus,
		arg.AppID,
		arg.ChannelType,
		arg.Status,
		arg.LastError,
	)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.ChannelType,
		&i.Status,
		&i.BoundIdentity,
		&i.ChannelName,
		&i.MetadataJson,
		&i.BoundAt,
		&i.LastOnlineAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
