// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_files.sql

package sqlc

import (
	"context"
)

const createConversationFile = `-- name: CreateConversationFile :exec
INSERT INTO conversation_files (
    id, app_id, session_id, s3_key, filename, mime, size
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateConversationFileParams struct {
	ID        string `db:"id" json:"id"`
	AppID     string `db:"app_id" json:"app_id"`
	SessionID string `db:"session_id" json:"session_id"`
	S3Key     string `db:"s3_key" json:"s3_key"`
	Filename  string `db:"filename" json:"filename"`
	Mime      string `db:"mime" json:"mime"`
	Size      int64  `db:"size" json:"size"`
}

func (q *Queries) CreateConversationFile(ctx context.Context, arg CreateConversationFileParams) error {
	_, err := q.db.ExecContext(ctx, createConversationFile,
		arg.ID,
		arg.AppID,
		arg.SessionID,
		arg.S3Key,
		arg.Filename,
		arg.Mime,
		arg.Size,
	)
	return err
}

const getConversationFile = `-- name: GetConversationFile :one
SELECT id, app_id, session_id, s3_key, filename, mime, size, created_at FROM conversation_files WHERE id = ?
`

func (q *Queries) GetConversationFile(ctx context.Context, id string) (ConversationFile, error) {
	row := q.db.QueryRowContext(ctx, getConversationFile, id)
	var i ConversationFile
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.SessionID,
		&i.S3Key,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}
