// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    type,
    status,
    priority,
    run_after,
    max_attempts,
    payload_json
) VALUES (
    $1, 'pending', $2, $3, $4, $5
)
RETURNING id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
`

type CreateJobParams struct {
	Type        string             `db:"type" json:"type"`
	Priority    int32              `db:"priority" json:"priority"`
	RunAfter    pgtype.Timestamptz `db:"run_after" json:"run_after"`
	MaxAttempts int32              `db:"max_attempts" json:"max_attempts"`
	PayloadJson []byte             `db:"payload_json" json:"payload_json"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Type,
		arg.Priority,
		arg.RunAfter,
		arg.MaxAttempts,
		arg.PayloadJson,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listReadyJobs = `-- name: ListReadyJobs :many
SELECT id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
FROM jobs
WHERE status = 'pending'
  AND run_after <= now()
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

func (q *Queries) ListReadyJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, listReadyJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.RunAfter,
			&i.Attempts,
			&i.MaxAttempts,
			&i.PayloadJson,
			&i.LockedBy,
			&i.LockedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJobForUpdate = `-- name: LockJobForUpdate :one
SELECT id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
FROM jobs
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockJobForUpdate(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, lockJobForUpdate, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :one
UPDATE jobs
SET
    status = 'failed',
    last_error = $2,
    finished_at = now(),
    locked_by = NULL,
    locked_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
`

type MarkJobFailedParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	LastError pgtype.Text `db:"last_error" json:"last_error"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFailed, arg.ID, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markJobRunning = `-- name: MarkJobRunning :one
UPDATE jobs
SET
    status = 'running',
    locked_by = $2,
    locked_at = now(),
    attempts = attempts + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
`

type MarkJobRunningParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	LockedBy pgtype.Text `db:"locked_by" json:"locked_by"`
}

func (q *Queries) MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobRunning, arg.ID, arg.LockedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markJobSucceeded = `-- name: MarkJobSucceeded :one
UPDATE jobs
SET
    status = 'succeeded',
    finished_at = now(),
    locked_by = NULL,
    locked_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
`

func (q *Queries) MarkJobSucceeded(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, markJobSucceeded, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const retryJob = `-- name: RetryJob :one
UPDATE jobs
SET
    status = 'pending',
    run_after = $2,
    last_error = $3,
    locked_by = NULL,
    locked_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, type, status, priority, run_after, attempts, max_attempts, payload_json, locked_by, locked_at, last_error, created_at, updated_at, finished_at
`

type RetryJobParams struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	RunAfter  pgtype.Timestamptz `db:"run_after" json:"run_after"`
	LastError pgtype.Text        `db:"last_error" json:"last_error"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryJob, arg.ID, arg.RunAfter, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.LockedBy,
		&i.LockedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
