// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// 成员客户端应用表；第一版每个未删除成员账号最多拥有一个未删除应用。
type App struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	OrgID       pgtype.UUID `db:"org_id" json:"org_id"`
	OwnerUserID pgtype.UUID `db:"owner_user_id" json:"owner_user_id"`
	// 应用所在运行节点，第一版创建应用前必须已有可用节点。
	RuntimeNodeID pgtype.UUID `db:"runtime_node_id" json:"runtime_node_id"`
	Name          string      `db:"name" json:"name"`
	Description   pgtype.Text `db:"description" json:"description"`
	Status        string      `db:"status" json:"status"`
	// 人设模式：继承组织人设或使用应用级覆盖提示词。
	PersonaMode   string      `db:"persona_mode" json:"persona_mode"`
	AppPrompt     pgtype.Text `db:"app_prompt" json:"app_prompt"`
	ContainerID   pgtype.Text `db:"container_id" json:"container_id"`
	ContainerName pgtype.Text `db:"container_name" json:"container_name"`
	NewapiKeyID   pgtype.Text `db:"newapi_key_id" json:"newapi_key_id"`
	// new-api key 密文，使用 manager 的 security.master_key 加密。
	NewapiKeyCiphertext pgtype.Text        `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus        string             `db:"api_key_status" json:"api_key_status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// 软删除时间；业务记录不做物理删除。
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	RuntimeSnapshotJson []byte             `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
	RuntimeSnapshotAt   pgtype.Timestamptz `db:"runtime_snapshot_at" json:"runtime_snapshot_at"`
	RestartPolicyJson   []byte             `db:"restart_policy_json" json:"restart_policy_json"`
	HealthStateJson     []byte             `db:"health_state_json" json:"health_state_json"`
}

// 审计日志表，记录关键操作、结果和错误信息；普通业务 API 不允许修改或删除。
type AuditLog struct {
	ID pgtype.UUID `db:"id" json:"id"`
	// 操作者用户 ID；系统任务产生的审计可为空。
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	ActorRole  string      `db:"actor_role" json:"actor_role"`
	OrgID      pgtype.UUID `db:"org_id" json:"org_id"`
	TargetType string      `db:"target_type" json:"target_type"`
	// 目标资源 ID；知识库文件可使用 org:{id}:filename 或 app:{id}:filename 编码。
	TargetID     string      `db:"target_id" json:"target_id"`
	Action       string      `db:"action" json:"action"`
	Result       string      `db:"result" json:"result"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	// 审计扩展元数据，例如文件大小、MIME、上传者等。
	MetadataJson []byte             `db:"metadata_json" json:"metadata_json"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 应用渠道绑定表，第一版仅支持 wechat，后续可扩展其他渠道。
type ChannelBinding struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ChannelType string      `db:"channel_type" json:"channel_type"`
	Status      string      `db:"status" json:"status"`
	// 渠道下的账号唯一标识，例如微信 wxid。
	BoundIdentity pgtype.Text `db:"bound_identity" json:"bound_identity"`
	ChannelName   pgtype.Text `db:"channel_name" json:"channel_name"`
	// 渠道特有元数据，例如二维码 payload、过期时间和登录 challenge。
	MetadataJson []byte             `db:"metadata_json" json:"metadata_json"`
	BoundAt      pgtype.Timestamptz `db:"bound_at" json:"bound_at"`
	LastOnlineAt pgtype.Timestamptz `db:"last_online_at" json:"last_online_at"`
	LastError    pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// 异步任务事实表；Redis 只负责分发，任务状态以本表为准。
type Job struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Type     string      `db:"type" json:"type"`
	Status   string      `db:"status" json:"status"`
	Priority int32       `db:"priority" json:"priority"`
	// 任务最早可执行时间，用于失败重试和延迟调度。
	RunAfter    pgtype.Timestamptz `db:"run_after" json:"run_after"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	MaxAttempts int32              `db:"max_attempts" json:"max_attempts"`
	// 任务载荷，handler 必须按类型做结构化校验。
	PayloadJson []byte `db:"payload_json" json:"payload_json"`
	// 当前领取任务的 worker 实例 ID。
	LockedBy   pgtype.Text        `db:"locked_by" json:"locked_by"`
	LockedAt   pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LastError  pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type KnowledgeSyncStatus struct {
	OrgID         pgtype.UUID        `db:"org_id" json:"org_id"`
	NodeID        pgtype.UUID        `db:"node_id" json:"node_id"`
	Status        string             `db:"status" json:"status"`
	LastSuccessAt pgtype.Timestamptz `db:"last_success_at" json:"last_success_at"`
	LastError     pgtype.Text        `db:"last_error" json:"last_error"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// 组织租户表，保存组织基础信息、new-api 账号映射和余额预警阈值。
type Organization struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	// 组织状态：active 表示可用，disabled 表示禁用，deleted 表示软删除。
	Status       string      `db:"status" json:"status"`
	ContactName  pgtype.Text `db:"contact_name" json:"contact_name"`
	ContactPhone pgtype.Text `db:"contact_phone" json:"contact_phone"`
	Remark       pgtype.Text `db:"remark" json:"remark"`
	NewapiUserID pgtype.Text `db:"newapi_user_id" json:"newapi_user_id"`
	// 组织余额预警百分比阈值，空值表示不启用预警。
	CreditWarningThreshold pgtype.Int4        `db:"credit_warning_threshold" json:"credit_warning_threshold"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	// new-api 业务用户凭据密文，明文为 JSON {username, password, access_token}，使用 manager 的 security.master_key AES-256-GCM 加密。
	NewapiUserCredentialsCiphertext pgtype.Text `db:"newapi_user_credentials_ciphertext" json:"newapi_user_credentials_ciphertext"`
}

// 组织级 AI 人设版本表，当前生效版本取同组织最大 version。
type OrganizationPersona struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	OrgID             pgtype.UUID `db:"org_id" json:"org_id"`
	SystemPrompt      string      `db:"system_prompt" json:"system_prompt"`
	ConversationRules pgtype.Text `db:"conversation_rules" json:"conversation_rules"`
	ForbiddenRules    pgtype.Text `db:"forbidden_rules" json:"forbidden_rules"`
	ReplyStyle        pgtype.Text `db:"reply_style" json:"reply_style"`
	// 是否允许成员应用使用 app_prompt 覆盖组织默认人设。
	AllowMemberOverride bool               `db:"allow_member_override" json:"allow_member_override"`
	Version             int32              `db:"version" json:"version"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 组织点数充值记录，计费事实仍以 new-api 为准。
type RechargeRecord struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	OrgID      pgtype.UUID `db:"org_id" json:"org_id"`
	OperatorID pgtype.UUID `db:"operator_id" json:"operator_id"`
	// 充值点数，使用整数避免浮点误差。
	CreditAmount int64       `db:"credit_amount" json:"credit_amount"`
	Remark       pgtype.Text `db:"remark" json:"remark"`
	// new-api 侧充值或余额调整引用 ID。
	NewapiRefID  pgtype.Text        `db:"newapi_ref_id" json:"newapi_ref_id"`
	Status       string             `db:"status" json:"status"`
	ErrorMessage pgtype.Text        `db:"error_message" json:"error_message"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 登录刷新令牌表，只保存 token hash，不保存明文令牌。
type RefreshToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	// 令牌撤销时间；为空且未过期时可用于刷新登录态。
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 运行节点注册表，manager 通过节点 agent 执行 Docker 与文件操作。
type RuntimeNode struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Name   string      `db:"name" json:"name"`
	Status string      `db:"status" json:"status"`
	// agent Docker 代理地址，manager 通过该地址访问节点 Docker 能力。
	AgentDockerEndpoint pgtype.Text `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	// agent 文件 API 地址，manager 通过该地址访问节点工作目录和知识库目录。
	AgentFileEndpoint pgtype.Text `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert    pgtype.Text `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	// 长期通信令牌 hash，明文令牌只保存在 agent 侧。
	AgentTokenHash pgtype.Text `db:"agent_token_hash" json:"agent_token_hash"`
	// 一次性注册令牌 hash，节点注册成功后清空。
	BootstrapTokenHash       pgtype.Text        `db:"bootstrap_token_hash" json:"bootstrap_token_hash"`
	BootstrapTokenExpiresAt  pgtype.Timestamptz `db:"bootstrap_token_expires_at" json:"bootstrap_token_expires_at"`
	AgentVersion             pgtype.Text        `db:"agent_version" json:"agent_version"`
	HeartbeatIntervalSeconds int32              `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	LastHeartbeatAt          pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	// agent 上报的 CPU、内存、磁盘、容器数量等资源快照。
	ResourceSnapshotJson []byte             `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson         []byte             `db:"metadata_json" json:"metadata_json"`
	NodeDataRoot         pgtype.Text        `db:"node_data_root" json:"node_data_root"`
	RegisteredAt         pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	// agent token 的 AES-256-GCM 密文，base64 编码；nullable 兼容 A 阶段已注册节点。
	AgentTokenCiphertext pgtype.Text `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
	// 节点最大未删除应用数；NULL 表示不限。OnboardingService 在自动选节点时按剩余容量过滤。
	MaxApps pgtype.Int4 `db:"max_apps" json:"max_apps"`
}

// 平台管理员、组织管理员和组织成员账号。
type User struct {
	ID pgtype.UUID `db:"id" json:"id"`
	// 平台管理员为空，组织管理员和组织成员必须归属一个组织。
	OrgID    pgtype.UUID `db:"org_id" json:"org_id"`
	Username string      `db:"username" json:"username"`
	// 密码 hash，不保存明文密码。
	PasswordHash string `db:"password_hash" json:"password_hash"`
	DisplayName  string `db:"display_name" json:"display_name"`
	// 账号角色：platform_admin、org_admin、org_member。
	Role        string             `db:"role" json:"role"`
	Status      string             `db:"status" json:"status"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
