// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	null "github.com/guregu/null/v5"
)

type App struct {
	ID                     string          `db:"id" json:"id"`
	OrgID                  string          `db:"org_id" json:"org_id"`
	OwnerUserID            string          `db:"owner_user_id" json:"owner_user_id"`
	Name                   string          `db:"name" json:"name"`
	Description            null.String     `db:"description" json:"description"`
	Status                 string          `db:"status" json:"status"`
	NewapiKeyID            null.String     `db:"newapi_key_id" json:"newapi_key_id"`
	NewapiKeyCiphertext    null.String     `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus           string          `db:"api_key_status" json:"api_key_status"`
	RuntimeSnapshotJson    []byte          `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
	RuntimeSnapshotAt      null.Time       `db:"runtime_snapshot_at" json:"runtime_snapshot_at"`
	RestartPolicyJson      json.RawMessage `db:"restart_policy_json" json:"restart_policy_json"`
	HealthStateJson        []byte          `db:"health_state_json" json:"health_state_json"`
	ProgressCurrent        null.Int        `db:"progress_current" json:"progress_current"`
	ProgressTotal          null.Int        `db:"progress_total" json:"progress_total"`
	LastErrorStatus        null.String     `db:"last_error_status" json:"last_error_status"`
	LastErrorMessage       null.String     `db:"last_error_message" json:"last_error_message"`
	RuntimeImageRef        string          `db:"runtime_image_ref" json:"runtime_image_ref"`
	RuntimeImageSha256     string          `db:"runtime_image_sha256" json:"runtime_image_sha256"`
	NewapiKeyName          null.String     `db:"newapi_key_name" json:"newapi_key_name"`
	VersionID              null.String     `db:"version_id" json:"version_id"`
	AppliedVersionRevision int32           `db:"applied_version_revision" json:"applied_version_revision"`
	AppliedImageRef        string          `db:"applied_image_ref" json:"applied_image_ref"`
	RuntimeTokenHash       null.String     `db:"runtime_token_hash" json:"runtime_token_hash"`
	RuntimeTokenCiphertext null.String     `db:"runtime_token_ciphertext" json:"runtime_token_ciphertext"`
	CreatedAt              time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt              null.Time       `db:"deleted_at" json:"deleted_at"`
	OwnerActiveKey         null.String     `db:"owner_active_key" json:"owner_active_key"`
	RuntimeTokenActiveKey  null.String     `db:"runtime_token_active_key" json:"runtime_token_active_key"`
	KnowledgeQuotaBytes    int64           `db:"knowledge_quota_bytes" json:"knowledge_quota_bytes"`
}

// 实例级 skill 安装清单，自包含快照，运行时唯一来源
type AppSkill struct {
	// 主键 UUID
	ID string `db:"id" json:"id"`
	// 所属实例 app id
	AppID string `db:"app_id" json:"app_id"`
	// 解压目录名，实例内唯一，去重键
	Name string `db:"name" json:"name"`
	// 来源：platform | clawhub
	Source string `db:"source" json:"source"`
	// 来源内精准标识：platform=name、clawhub=slug，回源查更新用
	SourceRef string `db:"source_ref" json:"source_ref"`
	// 锁定的当前安装版本
	Version string `db:"version" json:"version"`
	// 定时任务回源所得最高版本，大于 version 即有更新
	LatestVersion null.String `db:"latest_version" json:"latest_version"`
	// 对象存储缓存路径，恢复走它（确定性 + 抗下架）
	CachedTarPath string `db:"cached_tar_path" json:"cached_tar_path"`
	// 安装时来源完整元数据快照，后台展示用（抗下架）
	SourceMetadata json.RawMessage `db:"source_metadata" json:"source_metadata"`
	// 归档字节大小
	FileSize int64 `db:"file_size" json:"file_size"`
	// 归档内容 SHA256
	FileSha256 string `db:"file_sha256" json:"file_sha256"`
	// 安装者 user id
	InstalledBy null.String `db:"installed_by" json:"installed_by"`
	// 安装时间
	InstalledAt time.Time `db:"installed_at" json:"installed_at"`
	// 定时任务上次回源检查时间
	LastCheckedAt null.Time `db:"last_checked_at" json:"last_checked_at"`
}

type AssistantVersion struct {
	ID            string          `db:"id" json:"id"`
	Name          string          `db:"name" json:"name"`
	Description   string          `db:"description" json:"description"`
	SystemPrompt  string          `db:"system_prompt" json:"system_prompt"`
	ImageID       string          `db:"image_id" json:"image_id"`
	MainModel     string          `db:"main_model" json:"main_model"`
	RoutingJson   json.RawMessage `db:"routing_json" json:"routing_json"`
	SkillsJson    json.RawMessage `db:"skills_json" json:"skills_json"`
	Revision      int32           `db:"revision" json:"revision"`
	CreatedBy     null.String     `db:"created_by" json:"created_by"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt     null.Time       `db:"deleted_at" json:"deleted_at"`
	NameActiveKey null.String     `db:"name_active_key" json:"name_active_key"`
}

type AssistantVersionIndustryKnowledgeBasis struct {
	VersionID               string    `db:"version_id" json:"version_id"`
	IndustryKnowledgeBaseID string    `db:"industry_knowledge_base_id" json:"industry_knowledge_base_id"`
	CreatedAt               time.Time `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID            string      `db:"id" json:"id"`
	ActorID       null.String `db:"actor_id" json:"actor_id"`
	ActorRole     string      `db:"actor_role" json:"actor_role"`
	OrgID         null.String `db:"org_id" json:"org_id"`
	TargetType    string      `db:"target_type" json:"target_type"`
	TargetID      string      `db:"target_id" json:"target_id"`
	Action        string      `db:"action" json:"action"`
	Result        string      `db:"result" json:"result"`
	ErrorMessage  null.String `db:"error_message" json:"error_message"`
	IpAddress     null.String `db:"ip_address" json:"ip_address"`
	MetadataJson  []byte      `db:"metadata_json" json:"metadata_json"`
	DetailMessage null.String `db:"detail_message" json:"detail_message"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

type ChannelBinding struct {
	ID            string      `db:"id" json:"id"`
	AppID         string      `db:"app_id" json:"app_id"`
	ChannelType   string      `db:"channel_type" json:"channel_type"`
	Status        string      `db:"status" json:"status"`
	BoundIdentity null.String `db:"bound_identity" json:"bound_identity"`
	ChannelName   null.String `db:"channel_name" json:"channel_name"`
	MetadataJson  []byte      `db:"metadata_json" json:"metadata_json"`
	BoundAt       null.Time   `db:"bound_at" json:"bound_at"`
	LastOnlineAt  null.Time   `db:"last_online_at" json:"last_online_at"`
	LastError     null.String `db:"last_error" json:"last_error"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
	AppActiveKey  null.String `db:"app_active_key" json:"app_active_key"`
}

type IndustryKnowledgeBasis struct {
	ID            string      `db:"id" json:"id"`
	Name          string      `db:"name" json:"name"`
	CreatedBy     string      `db:"created_by" json:"created_by"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
	DeletedAt     null.Time   `db:"deleted_at" json:"deleted_at"`
	NameActiveKey null.String `db:"name_active_key" json:"name_active_key"`
}

type Job struct {
	ID          string          `db:"id" json:"id"`
	Type        string          `db:"type" json:"type"`
	Status      string          `db:"status" json:"status"`
	Priority    int32           `db:"priority" json:"priority"`
	RunAfter    time.Time       `db:"run_after" json:"run_after"`
	Attempts    int32           `db:"attempts" json:"attempts"`
	MaxAttempts int32           `db:"max_attempts" json:"max_attempts"`
	PayloadJson json.RawMessage `db:"payload_json" json:"payload_json"`
	LockedBy    null.String     `db:"locked_by" json:"locked_by"`
	LockedAt    null.Time       `db:"locked_at" json:"locked_at"`
	LastError   null.String     `db:"last_error" json:"last_error"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	FinishedAt  null.Time       `db:"finished_at" json:"finished_at"`
}

type Organization struct {
	// 组织 ID
	ID string `db:"id" json:"id"`
	// 组织名称
	Name string `db:"name" json:"name"`
	// 组织状态
	Status                          string      `db:"status" json:"status"`
	ContactName                     null.String `db:"contact_name" json:"contact_name"`
	ContactPhone                    null.String `db:"contact_phone" json:"contact_phone"`
	Remark                          null.String `db:"remark" json:"remark"`
	NewapiUserID                    null.String `db:"newapi_user_id" json:"newapi_user_id"`
	CreditWarningThreshold          null.Int    `db:"credit_warning_threshold" json:"credit_warning_threshold"`
	NewapiUserCredentialsCiphertext null.String `db:"newapi_user_credentials_ciphertext" json:"newapi_user_credentials_ciphertext"`
	// 组织代码，登录命名空间
	Code           string      `db:"code" json:"code"`
	NewapiUsername null.String `db:"newapi_username" json:"newapi_username"`
	// 可用助手版本 ID allowlist
	AssistantVersionIds json.RawMessage `db:"assistant_version_ids" json:"assistant_version_ids"`
	CreatedAt           time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt           null.Time       `db:"deleted_at" json:"deleted_at"`
	MaxInstanceCount    null.Int        `db:"max_instance_count" json:"max_instance_count"`
	KnowledgeQuotaBytes int64           `db:"knowledge_quota_bytes" json:"knowledge_quota_bytes"`
}

// 平台库 skill，平台管理员维护，多版本共存
type PlatformSkill struct {
	// 主键 UUID
	ID string `db:"id" json:"id"`
	// skill 名，等于容器内解压目录名
	Name string `db:"name" json:"name"`
	// skill 描述，市场展示用
	Description string `db:"description" json:"description"`
	// 语义版本号
	Version string `db:"version" json:"version"`
	// 对象存储相对路径 library/platform/<name>/<version>.tar
	TarPath string `db:"tar_path" json:"tar_path"`
	// tar 字节大小
	FileSize int64 `db:"file_size" json:"file_size"`
	// tar 内容 SHA256，完整性校验
	FileSha256 string `db:"file_sha256" json:"file_sha256"`
	// 附加元数据（作者、标签等）
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
	// 上传者 user id（平台管理员）
	UploadedBy null.String `db:"uploaded_by" json:"uploaded_by"`
	// 创建时间
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type RagflowDataset struct {
	ID                      string      `db:"id" json:"id"`
	ScopeType               string      `db:"scope_type" json:"scope_type"`
	AppID                   null.String `db:"app_id" json:"app_id"`
	RagflowDatasetID        null.String `db:"ragflow_dataset_id" json:"ragflow_dataset_id"`
	Name                    string      `db:"name" json:"name"`
	Status                  string      `db:"status" json:"status"`
	LastError               null.String `db:"last_error" json:"last_error"`
	CreateClaimToken        null.String `db:"create_claim_token" json:"create_claim_token"`
	CreatedAt               time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time   `db:"updated_at" json:"updated_at"`
	OrgScopeKey             null.String `db:"org_scope_key" json:"org_scope_key"`
	AppScopeKey             null.String `db:"app_scope_key" json:"app_scope_key"`
	OrgID                   null.String `db:"org_id" json:"org_id"`
	IndustryKnowledgeBaseID null.String `db:"industry_knowledge_base_id" json:"industry_knowledge_base_id"`
	IndustryScopeKey        null.String `db:"industry_scope_key" json:"industry_scope_key"`
}

type RagflowDocument struct {
	ID                      string      `db:"id" json:"id"`
	DatasetID               string      `db:"dataset_id" json:"dataset_id"`
	ScopeType               string      `db:"scope_type" json:"scope_type"`
	AppID                   null.String `db:"app_id" json:"app_id"`
	RagflowDocumentID       string      `db:"ragflow_document_id" json:"ragflow_document_id"`
	Name                    string      `db:"name" json:"name"`
	SizeBytes               int64       `db:"size_bytes" json:"size_bytes"`
	MimeType                null.String `db:"mime_type" json:"mime_type"`
	Suffix                  null.String `db:"suffix" json:"suffix"`
	ParseStatus             string      `db:"parse_status" json:"parse_status"`
	Progress                int32       `db:"progress" json:"progress"`
	LastError               null.String `db:"last_error" json:"last_error"`
	CreatedBy               string      `db:"created_by" json:"created_by"`
	CreatedAt               time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time   `db:"updated_at" json:"updated_at"`
	OrgID                   null.String `db:"org_id" json:"org_id"`
	IndustryKnowledgeBaseID null.String `db:"industry_knowledge_base_id" json:"industry_knowledge_base_id"`
	IndustryDocumentBaseKey null.String `db:"industry_document_base_key" json:"industry_document_base_key"`
	IndustryDocumentNameKey null.String `db:"industry_document_name_key" json:"industry_document_name_key"`
	AutoReparseAttempts     int32       `db:"auto_reparse_attempts" json:"auto_reparse_attempts"`
	AutoReparseNextAt       null.Time   `db:"auto_reparse_next_at" json:"auto_reparse_next_at"`
}

type RechargeRecord struct {
	ID           string      `db:"id" json:"id"`
	OrgID        string      `db:"org_id" json:"org_id"`
	OperatorID   string      `db:"operator_id" json:"operator_id"`
	CreditAmount int64       `db:"credit_amount" json:"credit_amount"`
	Remark       null.String `db:"remark" json:"remark"`
	NewapiRefID  null.String `db:"newapi_ref_id" json:"newapi_ref_id"`
	Status       string      `db:"status" json:"status"`
	ErrorMessage null.String `db:"error_message" json:"error_message"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt null.Time `db:"revoked_at" json:"revoked_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID string `db:"id" json:"id"`
	// 所属组织（平台管理员为空）
	OrgID        null.String `db:"org_id" json:"org_id"`
	Username     string      `db:"username" json:"username"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	DisplayName  string      `db:"display_name" json:"display_name"`
	Role         string      `db:"role" json:"role"`
	Status       string      `db:"status" json:"status"`
	LastLoginAt  null.Time   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time   `db:"updated_at" json:"updated_at"`
	// 下线时间
	DeletedAt           null.Time   `db:"deleted_at" json:"deleted_at"`
	PlatformUsernameKey null.String `db:"platform_username_key" json:"platform_username_key"`
}
