// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	null "github.com/guregu/null/v5"
)

type App struct {
	ID                     string          `db:"id" json:"id"`
	OrgID                  string          `db:"org_id" json:"org_id"`
	OwnerUserID            string          `db:"owner_user_id" json:"owner_user_id"`
	Name                   string          `db:"name" json:"name"`
	Description            null.String     `db:"description" json:"description"`
	Status                 string          `db:"status" json:"status"`
	ContainerID            null.String     `db:"container_id" json:"container_id"`
	ContainerName          null.String     `db:"container_name" json:"container_name"`
	NewapiKeyID            null.String     `db:"newapi_key_id" json:"newapi_key_id"`
	NewapiKeyCiphertext    null.String     `db:"newapi_key_ciphertext" json:"newapi_key_ciphertext"`
	ApiKeyStatus           string          `db:"api_key_status" json:"api_key_status"`
	RuntimeSnapshotJson    []byte          `db:"runtime_snapshot_json" json:"runtime_snapshot_json"`
	RuntimeSnapshotAt      null.Time       `db:"runtime_snapshot_at" json:"runtime_snapshot_at"`
	RestartPolicyJson      json.RawMessage `db:"restart_policy_json" json:"restart_policy_json"`
	HealthStateJson        []byte          `db:"health_state_json" json:"health_state_json"`
	ProgressCurrent        null.Int        `db:"progress_current" json:"progress_current"`
	ProgressTotal          null.Int        `db:"progress_total" json:"progress_total"`
	LastErrorStatus        null.String     `db:"last_error_status" json:"last_error_status"`
	LastErrorMessage       null.String     `db:"last_error_message" json:"last_error_message"`
	RuntimeImageRef        string          `db:"runtime_image_ref" json:"runtime_image_ref"`
	RuntimeImageSha256     string          `db:"runtime_image_sha256" json:"runtime_image_sha256"`
	NewapiKeyName          null.String     `db:"newapi_key_name" json:"newapi_key_name"`
	VersionID              null.String     `db:"version_id" json:"version_id"`
	AppliedVersionRevision int32           `db:"applied_version_revision" json:"applied_version_revision"`
	AppliedImageRef        string          `db:"applied_image_ref" json:"applied_image_ref"`
	RuntimeTokenHash       null.String     `db:"runtime_token_hash" json:"runtime_token_hash"`
	RuntimeTokenCiphertext null.String     `db:"runtime_token_ciphertext" json:"runtime_token_ciphertext"`
	CreatedAt              time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt              time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt              null.Time       `db:"deleted_at" json:"deleted_at"`
	OwnerActiveKey         null.String     `db:"owner_active_key" json:"owner_active_key"`
	RuntimeTokenActiveKey  null.String     `db:"runtime_token_active_key" json:"runtime_token_active_key"`
	RuntimeNodeID          null.String     `db:"runtime_node_id" json:"runtime_node_id"`
}

type AssistantVersion struct {
	ID            string          `db:"id" json:"id"`
	Name          string          `db:"name" json:"name"`
	Description   string          `db:"description" json:"description"`
	SystemPrompt  string          `db:"system_prompt" json:"system_prompt"`
	ImageID       string          `db:"image_id" json:"image_id"`
	MainModel     string          `db:"main_model" json:"main_model"`
	RoutingJson   json.RawMessage `db:"routing_json" json:"routing_json"`
	SkillsJson    json.RawMessage `db:"skills_json" json:"skills_json"`
	Revision      int32           `db:"revision" json:"revision"`
	CreatedBy     null.String     `db:"created_by" json:"created_by"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt     null.Time       `db:"deleted_at" json:"deleted_at"`
	NameActiveKey null.String     `db:"name_active_key" json:"name_active_key"`
}

type AuditLog struct {
	ID            string      `db:"id" json:"id"`
	ActorID       null.String `db:"actor_id" json:"actor_id"`
	ActorRole     string      `db:"actor_role" json:"actor_role"`
	OrgID         null.String `db:"org_id" json:"org_id"`
	TargetType    string      `db:"target_type" json:"target_type"`
	TargetID      string      `db:"target_id" json:"target_id"`
	Action        string      `db:"action" json:"action"`
	Result        string      `db:"result" json:"result"`
	ErrorMessage  null.String `db:"error_message" json:"error_message"`
	IpAddress     null.String `db:"ip_address" json:"ip_address"`
	MetadataJson  []byte      `db:"metadata_json" json:"metadata_json"`
	DetailMessage null.String `db:"detail_message" json:"detail_message"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
}

type ChannelBinding struct {
	ID            string      `db:"id" json:"id"`
	AppID         string      `db:"app_id" json:"app_id"`
	ChannelType   string      `db:"channel_type" json:"channel_type"`
	Status        string      `db:"status" json:"status"`
	BoundIdentity null.String `db:"bound_identity" json:"bound_identity"`
	ChannelName   null.String `db:"channel_name" json:"channel_name"`
	MetadataJson  []byte      `db:"metadata_json" json:"metadata_json"`
	BoundAt       null.Time   `db:"bound_at" json:"bound_at"`
	LastOnlineAt  null.Time   `db:"last_online_at" json:"last_online_at"`
	LastError     null.String `db:"last_error" json:"last_error"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
	AppActiveKey  null.String `db:"app_active_key" json:"app_active_key"`
}

type InstanceResourceSample struct {
	ID               string      `db:"id" json:"id"`
	AppID            string      `db:"app_id" json:"app_id"`
	RuntimeNodeID    string      `db:"runtime_node_id" json:"runtime_node_id"`
	ContainerID      string      `db:"container_id" json:"container_id"`
	SampledAt        time.Time   `db:"sampled_at" json:"sampled_at"`
	ContainerStatus  null.String `db:"container_status" json:"container_status"`
	CpuPercent       null.Float  `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  null.Int    `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryLimitBytes null.Int    `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	DiskReadBytes    null.Int    `db:"disk_read_bytes" json:"disk_read_bytes"`
	DiskWriteBytes   null.Int    `db:"disk_write_bytes" json:"disk_write_bytes"`
	NetworkRxBytes   null.Int    `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   null.Int    `db:"network_tx_bytes" json:"network_tx_bytes"`
	LastError        null.String `db:"last_error" json:"last_error"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
}

type Job struct {
	ID          string          `db:"id" json:"id"`
	Type        string          `db:"type" json:"type"`
	Status      string          `db:"status" json:"status"`
	Priority    int32           `db:"priority" json:"priority"`
	RunAfter    time.Time       `db:"run_after" json:"run_after"`
	Attempts    int32           `db:"attempts" json:"attempts"`
	MaxAttempts int32           `db:"max_attempts" json:"max_attempts"`
	PayloadJson json.RawMessage `db:"payload_json" json:"payload_json"`
	LockedBy    null.String     `db:"locked_by" json:"locked_by"`
	LockedAt    null.Time       `db:"locked_at" json:"locked_at"`
	LastError   null.String     `db:"last_error" json:"last_error"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at" json:"updated_at"`
	FinishedAt  null.Time       `db:"finished_at" json:"finished_at"`
}

type NodeResourceSample struct {
	ID               string      `db:"id" json:"id"`
	RuntimeNodeID    string      `db:"runtime_node_id" json:"runtime_node_id"`
	SampledAt        time.Time   `db:"sampled_at" json:"sampled_at"`
	CpuPercent       null.Float  `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  null.Int    `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryTotalBytes null.Int    `db:"memory_total_bytes" json:"memory_total_bytes"`
	DiskUsedBytes    null.Int    `db:"disk_used_bytes" json:"disk_used_bytes"`
	DiskTotalBytes   null.Int    `db:"disk_total_bytes" json:"disk_total_bytes"`
	NetworkRxBytes   null.Int    `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   null.Int    `db:"network_tx_bytes" json:"network_tx_bytes"`
	InstanceCount    null.Int    `db:"instance_count" json:"instance_count"`
	LastError        null.String `db:"last_error" json:"last_error"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
}

type Organization struct {
	// 组织 ID
	ID string `db:"id" json:"id"`
	// 组织名称
	Name string `db:"name" json:"name"`
	// 组织状态
	Status                          string      `db:"status" json:"status"`
	ContactName                     null.String `db:"contact_name" json:"contact_name"`
	ContactPhone                    null.String `db:"contact_phone" json:"contact_phone"`
	Remark                          null.String `db:"remark" json:"remark"`
	NewapiUserID                    null.String `db:"newapi_user_id" json:"newapi_user_id"`
	CreditWarningThreshold          null.Int    `db:"credit_warning_threshold" json:"credit_warning_threshold"`
	NewapiUserCredentialsCiphertext null.String `db:"newapi_user_credentials_ciphertext" json:"newapi_user_credentials_ciphertext"`
	// 组织代码，登录命名空间
	Code           string      `db:"code" json:"code"`
	NewapiUsername null.String `db:"newapi_username" json:"newapi_username"`
	// 可用助手版本 ID allowlist
	AssistantVersionIds json.RawMessage `db:"assistant_version_ids" json:"assistant_version_ids"`
	CreatedAt           time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at" json:"updated_at"`
	DeletedAt           null.Time       `db:"deleted_at" json:"deleted_at"`
}

type RagflowDataset struct {
	ID               string      `db:"id" json:"id"`
	ScopeType        string      `db:"scope_type" json:"scope_type"`
	OrgID            string      `db:"org_id" json:"org_id"`
	AppID            null.String `db:"app_id" json:"app_id"`
	RagflowDatasetID null.String `db:"ragflow_dataset_id" json:"ragflow_dataset_id"`
	Name             string      `db:"name" json:"name"`
	Status           string      `db:"status" json:"status"`
	LastError        null.String `db:"last_error" json:"last_error"`
	CreateClaimToken null.String `db:"create_claim_token" json:"create_claim_token"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	OrgScopeKey      null.String `db:"org_scope_key" json:"org_scope_key"`
	AppScopeKey      null.String `db:"app_scope_key" json:"app_scope_key"`
}

type RagflowDocument struct {
	ID                string      `db:"id" json:"id"`
	DatasetID         string      `db:"dataset_id" json:"dataset_id"`
	ScopeType         string      `db:"scope_type" json:"scope_type"`
	OrgID             string      `db:"org_id" json:"org_id"`
	AppID             null.String `db:"app_id" json:"app_id"`
	RagflowDocumentID string      `db:"ragflow_document_id" json:"ragflow_document_id"`
	Name              string      `db:"name" json:"name"`
	SizeBytes         int64       `db:"size_bytes" json:"size_bytes"`
	MimeType          null.String `db:"mime_type" json:"mime_type"`
	Suffix            null.String `db:"suffix" json:"suffix"`
	ParseStatus       string      `db:"parse_status" json:"parse_status"`
	Progress          int32       `db:"progress" json:"progress"`
	LastError         null.String `db:"last_error" json:"last_error"`
	CreatedBy         string      `db:"created_by" json:"created_by"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time   `db:"updated_at" json:"updated_at"`
}

type RechargeRecord struct {
	ID           string      `db:"id" json:"id"`
	OrgID        string      `db:"org_id" json:"org_id"`
	OperatorID   string      `db:"operator_id" json:"operator_id"`
	CreditAmount int64       `db:"credit_amount" json:"credit_amount"`
	Remark       null.String `db:"remark" json:"remark"`
	NewapiRefID  null.String `db:"newapi_ref_id" json:"newapi_ref_id"`
	Status       string      `db:"status" json:"status"`
	ErrorMessage null.String `db:"error_message" json:"error_message"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
}

type RefreshToken struct {
	ID        string    `db:"id" json:"id"`
	UserID    string    `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	RevokedAt null.Time `db:"revoked_at" json:"revoked_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type RuntimeNode struct {
	ID                       string      `db:"id" json:"id"`
	Name                     string      `db:"name" json:"name"`
	Status                   string      `db:"status" json:"status"`
	AgentDockerEndpoint      null.String `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint        null.String `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert           null.String `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash           null.String `db:"agent_token_hash" json:"agent_token_hash"`
	AgentTokenCiphertext     null.String `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
	AgentVersion             null.String `db:"agent_version" json:"agent_version"`
	HeartbeatIntervalSeconds int32       `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	LastHeartbeatAt          null.Time   `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	ResourceSnapshotJson     []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson             []byte      `db:"metadata_json" json:"metadata_json"`
	NodeDataRoot             null.String `db:"node_data_root" json:"node_data_root"`
	RegisteredAt             null.Time   `db:"registered_at" json:"registered_at"`
	MaxApps                  null.Int    `db:"max_apps" json:"max_apps"`
	AgentID                  null.String `db:"agent_id" json:"agent_id"`
	LastProbeAttemptedAt     null.Time   `db:"last_probe_attempted_at" json:"last_probe_attempted_at"`
	LastProbeOkAt            null.Time   `db:"last_probe_ok_at" json:"last_probe_ok_at"`
	LastProbeFailedAt        null.Time   `db:"last_probe_failed_at" json:"last_probe_failed_at"`
	LastProbeError           null.String `db:"last_probe_error" json:"last_probe_error"`
	ProbeFailureStreak       int32       `db:"probe_failure_streak" json:"probe_failure_streak"`
	ProbeSuccessStreak       int32       `db:"probe_success_streak" json:"probe_success_streak"`
	CreatedAt                time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time   `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID string `db:"id" json:"id"`
	// 所属组织（平台管理员为空）
	OrgID        null.String `db:"org_id" json:"org_id"`
	Username     string      `db:"username" json:"username"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	DisplayName  string      `db:"display_name" json:"display_name"`
	Role         string      `db:"role" json:"role"`
	Status       string      `db:"status" json:"status"`
	LastLoginAt  null.Time   `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time   `db:"updated_at" json:"updated_at"`
	// 下线时间
	DeletedAt           null.Time   `db:"deleted_at" json:"deleted_at"`
	PlatformUsernameKey null.String `db:"platform_username_key" json:"platform_username_key"`
}
