// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    name,
    status,
    contact_name,
    contact_phone,
    remark,
    newapi_user_id,
    credit_warning_threshold
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Name                   string      `db:"name" json:"name"`
	Status                 string      `db:"status" json:"status"`
	ContactName            pgtype.Text `db:"contact_name" json:"contact_name"`
	ContactPhone           pgtype.Text `db:"contact_phone" json:"contact_phone"`
	Remark                 pgtype.Text `db:"remark" json:"remark"`
	NewapiUserID           pgtype.Text `db:"newapi_user_id" json:"newapi_user_id"`
	CreditWarningThreshold pgtype.Int4 `db:"credit_warning_threshold" json:"credit_warning_threshold"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Status,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.NewapiUserID,
		arg.CreditWarningThreshold,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
FROM organizations
WHERE name = $1
`

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByName, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.ContactName,
			&i.ContactPhone,
			&i.Remark,
			&i.NewapiUserID,
			&i.CreditWarningThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationStatus = `-- name: SetOrganizationStatus :one
UPDATE organizations
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
`

type SetOrganizationStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, setOrganizationStatus, arg.ID, arg.Status)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :one
UPDATE organizations
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, softDeleteOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrganizationProfile = `-- name: UpdateOrganizationProfile :one
UPDATE organizations
SET
    name = $2,
    contact_name = $3,
    contact_phone = $4,
    remark = $5,
    credit_warning_threshold = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, created_at, updated_at, deleted_at
`

type UpdateOrganizationProfileParams struct {
	ID                     pgtype.UUID `db:"id" json:"id"`
	Name                   string      `db:"name" json:"name"`
	ContactName            pgtype.Text `db:"contact_name" json:"contact_name"`
	ContactPhone           pgtype.Text `db:"contact_phone" json:"contact_phone"`
	Remark                 pgtype.Text `db:"remark" json:"remark"`
	CreditWarningThreshold pgtype.Int4 `db:"credit_warning_threshold" json:"credit_warning_threshold"`
}

func (q *Queries) UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationProfile,
		arg.ID,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.CreditWarningThreshold,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
