// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"
	"encoding/json"

	null "github.com/guregu/null/v5"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    id,
    name,
    code,
    status,
    contact_name,
    contact_phone,
    remark,
    credit_warning_threshold,
    max_instance_count,
    knowledge_quota_bytes,
    assistant_version_ids
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?,
    COALESCE(NULLIF(CAST(? AS SIGNED), 0), 1073741824),
    ?
)
`

type CreateOrganizationParams struct {
	ID                     string          `db:"id" json:"id"`
	Name                   string          `db:"name" json:"name"`
	Code                   string          `db:"code" json:"code"`
	Status                 string          `db:"status" json:"status"`
	ContactName            null.String     `db:"contact_name" json:"contact_name"`
	ContactPhone           null.String     `db:"contact_phone" json:"contact_phone"`
	Remark                 null.String     `db:"remark" json:"remark"`
	CreditWarningThreshold null.Int        `db:"credit_warning_threshold" json:"credit_warning_threshold"`
	MaxInstanceCount       null.Int        `db:"max_instance_count" json:"max_instance_count"`
	KnowledgeQuotaBytes    int64           `db:"knowledge_quota_bytes" json:"knowledge_quota_bytes"`
	AssistantVersionIds    json.RawMessage `db:"assistant_version_ids" json:"assistant_version_ids"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Status,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.CreditWarningThreshold,
		arg.MaxInstanceCount,
		arg.KnowledgeQuotaBytes,
		arg.AssistantVersionIds,
	)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE id = ?
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.NewapiUserCredentialsCiphertext,
		&i.Code,
		&i.NewapiUsername,
		&i.AssistantVersionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaxInstanceCount,
		&i.KnowledgeQuotaBytes,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE code = ?
`

func (q *Queries) GetOrganizationByCode(ctx context.Context, code string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByCode, code)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.NewapiUserCredentialsCiphertext,
		&i.Code,
		&i.NewapiUsername,
		&i.AssistantVersionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaxInstanceCount,
		&i.KnowledgeQuotaBytes,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE name = ?
`

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByName, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.NewapiUserCredentialsCiphertext,
		&i.Code,
		&i.NewapiUsername,
		&i.AssistantVersionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaxInstanceCount,
		&i.KnowledgeQuotaBytes,
	)
	return i, err
}

const getOrganizationForUpdate = `-- name: GetOrganizationForUpdate :one
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE id = ?
FOR UPDATE
`

// OOS-2 access_token 自愈用：以行锁查询组织，避免并发更新密文时出现写丢失。
func (q *Queries) GetOrganizationForUpdate(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationForUpdate, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ContactName,
		&i.ContactPhone,
		&i.Remark,
		&i.NewapiUserID,
		&i.CreditWarningThreshold,
		&i.NewapiUserCredentialsCiphertext,
		&i.Code,
		&i.NewapiUsername,
		&i.AssistantVersionIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.MaxInstanceCount,
		&i.KnowledgeQuotaBytes,
	)
	return i, err
}

const hardDeleteOrganization = `-- name: HardDeleteOrganization :exec
DELETE FROM organizations WHERE id = ?
`

// 用于组织创建链路失败时回滚刚刚 INSERT 的孤儿记录。
// 正常生命周期不可见此查询；普通"删除"必须走 SoftDeleteOrganization。
func (q *Queries) HardDeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteOrganization, id)
	return err
}

const listAllActiveOrganizations = `-- name: ListAllActiveOrganizations :many
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

// 全量返回活跃组织（deleted_at IS NULL），不分页；
// 仅供平台内部聚合使用（如 GetOrgUsageBreakdown），请勿用于用户可见的列表接口。
func (q *Queries) ListAllActiveOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.ContactName,
			&i.ContactPhone,
			&i.Remark,
			&i.NewapiUserID,
			&i.CreditWarningThreshold,
			&i.NewapiUserCredentialsCiphertext,
			&i.Code,
			&i.NewapiUsername,
			&i.AssistantVersionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MaxInstanceCount,
			&i.KnowledgeQuotaBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, status, contact_name, contact_phone, remark, newapi_user_id, credit_warning_threshold, newapi_user_credentials_ciphertext, code, newapi_username, assistant_version_ids, created_at, updated_at, deleted_at, max_instance_count, knowledge_quota_bytes
FROM organizations
WHERE deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListOrganizationsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.ContactName,
			&i.ContactPhone,
			&i.Remark,
			&i.NewapiUserID,
			&i.CreditWarningThreshold,
			&i.NewapiUserCredentialsCiphertext,
			&i.Code,
			&i.NewapiUsername,
			&i.AssistantVersionIds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MaxInstanceCount,
			&i.KnowledgeQuotaBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationNewAPIUser = `-- name: SetOrganizationNewAPIUser :exec
UPDATE organizations
SET
    newapi_user_id = ?,
    newapi_user_credentials_ciphertext = ?,
    newapi_username = ?,
    updated_at = now()
WHERE id = ?
`

type SetOrganizationNewAPIUserParams struct {
	NewapiUserID                    null.String `db:"newapi_user_id" json:"newapi_user_id"`
	NewapiUserCredentialsCiphertext null.String `db:"newapi_user_credentials_ciphertext" json:"newapi_user_credentials_ciphertext"`
	NewapiUsername                  null.String `db:"newapi_username" json:"newapi_username"`
	ID                              string      `db:"id" json:"id"`
}

func (q *Queries) SetOrganizationNewAPIUser(ctx context.Context, arg SetOrganizationNewAPIUserParams) error {
	_, err := q.db.ExecContext(ctx, setOrganizationNewAPIUser,
		arg.NewapiUserID,
		arg.NewapiUserCredentialsCiphertext,
		arg.NewapiUsername,
		arg.ID,
	)
	return err
}

const setOrganizationStatus = `-- name: SetOrganizationStatus :exec
UPDATE organizations
SET status = ?, updated_at = now()
WHERE id = ?
`

type SetOrganizationStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) error {
	_, err := q.db.ExecContext(ctx, setOrganizationStatus, arg.Status, arg.ID)
	return err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganizationCredentialsCiphertext = `-- name: UpdateOrganizationCredentialsCiphertext :exec
UPDATE organizations
SET newapi_user_credentials_ciphertext = ?,
    updated_at = now()
WHERE id = ?
`

type UpdateOrganizationCredentialsCiphertextParams struct {
	NewapiUserCredentialsCiphertext null.String `db:"newapi_user_credentials_ciphertext" json:"newapi_user_credentials_ciphertext"`
	ID                              string      `db:"id" json:"id"`
}

// OOS-2 access_token 自愈用：仅更新 newapi_user_credentials_ciphertext，不动 newapi_user_id。
func (q *Queries) UpdateOrganizationCredentialsCiphertext(ctx context.Context, arg UpdateOrganizationCredentialsCiphertextParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationCredentialsCiphertext, arg.NewapiUserCredentialsCiphertext, arg.ID)
	return err
}

const updateOrganizationProfile = `-- name: UpdateOrganizationProfile :exec
UPDATE organizations
SET
    name = ?,
    contact_name = ?,
    contact_phone = ?,
    remark = ?,
    credit_warning_threshold = ?,
    max_instance_count = ?,
    knowledge_quota_bytes = COALESCE(NULLIF(CAST(? AS SIGNED), 0), knowledge_quota_bytes),
    assistant_version_ids = ?,
    updated_at = now()
WHERE id = ?
`

type UpdateOrganizationProfileParams struct {
	Name                   string          `db:"name" json:"name"`
	ContactName            null.String     `db:"contact_name" json:"contact_name"`
	ContactPhone           null.String     `db:"contact_phone" json:"contact_phone"`
	Remark                 null.String     `db:"remark" json:"remark"`
	CreditWarningThreshold null.Int        `db:"credit_warning_threshold" json:"credit_warning_threshold"`
	MaxInstanceCount       null.Int        `db:"max_instance_count" json:"max_instance_count"`
	KnowledgeQuotaBytes    int64           `db:"knowledge_quota_bytes" json:"knowledge_quota_bytes"`
	AssistantVersionIds    json.RawMessage `db:"assistant_version_ids" json:"assistant_version_ids"`
	ID                     string          `db:"id" json:"id"`
}

func (q *Queries) UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganizationProfile,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.Remark,
		arg.CreditWarningThreshold,
		arg.MaxInstanceCount,
		arg.KnowledgeQuotaBytes,
		arg.AssistantVersionIds,
		arg.ID,
	)
	return err
}
