// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_skills.sql

package sqlc

import (
	"context"
	"encoding/json"

	null "github.com/guregu/null/v5"
)

const createPlatformSkill = `-- name: CreatePlatformSkill :exec
INSERT INTO platform_skills (
    id, name, description, version, tar_path, file_size, file_sha256, metadata_json, uploaded_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlatformSkillParams struct {
	ID           string          `db:"id" json:"id"`
	Name         string          `db:"name" json:"name"`
	Description  string          `db:"description" json:"description"`
	Version      string          `db:"version" json:"version"`
	TarPath      string          `db:"tar_path" json:"tar_path"`
	FileSize     int64           `db:"file_size" json:"file_size"`
	FileSha256   string          `db:"file_sha256" json:"file_sha256"`
	MetadataJson json.RawMessage `db:"metadata_json" json:"metadata_json"`
	UploadedBy   null.String     `db:"uploaded_by" json:"uploaded_by"`
}

func (q *Queries) CreatePlatformSkill(ctx context.Context, arg CreatePlatformSkillParams) error {
	_, err := q.db.ExecContext(ctx, createPlatformSkill,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.TarPath,
		arg.FileSize,
		arg.FileSha256,
		arg.MetadataJson,
		arg.UploadedBy,
	)
	return err
}

const deletePlatformSkill = `-- name: DeletePlatformSkill :exec
DELETE FROM platform_skills WHERE id = ?
`

func (q *Queries) DeletePlatformSkill(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlatformSkill, id)
	return err
}

const getPlatformSkill = `-- name: GetPlatformSkill :one
SELECT id, name, description, version, tar_path, file_size, file_sha256, metadata_json, uploaded_by, created_at FROM platform_skills WHERE id = ?
`

func (q *Queries) GetPlatformSkill(ctx context.Context, id string) (PlatformSkill, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSkill, id)
	var i PlatformSkill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.TarPath,
		&i.FileSize,
		&i.FileSha256,
		&i.MetadataJson,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformSkillByNameVersion = `-- name: GetPlatformSkillByNameVersion :one
SELECT id, name, description, version, tar_path, file_size, file_sha256, metadata_json, uploaded_by, created_at FROM platform_skills WHERE name = ? AND version = ?
`

type GetPlatformSkillByNameVersionParams struct {
	Name    string `db:"name" json:"name"`
	Version string `db:"version" json:"version"`
}

func (q *Queries) GetPlatformSkillByNameVersion(ctx context.Context, arg GetPlatformSkillByNameVersionParams) (PlatformSkill, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSkillByNameVersion, arg.Name, arg.Version)
	var i PlatformSkill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.TarPath,
		&i.FileSize,
		&i.FileSha256,
		&i.MetadataJson,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatformSkills = `-- name: ListPlatformSkills :many
SELECT id, name, description, version, tar_path, file_size, file_sha256, metadata_json, uploaded_by, created_at FROM platform_skills ORDER BY name ASC, created_at DESC, id DESC
`

func (q *Queries) ListPlatformSkills(ctx context.Context) ([]PlatformSkill, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSkill{}
	for rows.Next() {
		var i PlatformSkill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.TarPath,
			&i.FileSize,
			&i.FileSha256,
			&i.MetadataJson,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
