// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_overview.sql

package sqlc

import (
	"context"
)

const countActiveOrganizations = `-- name: CountActiveOrganizations :one
SELECT COUNT(*) AS count FROM organizations WHERE deleted_at IS NULL
`

// 平台总览组织计数：剔除 soft-deleted；status='active' 与 'disabled' 都算入册组织。
func (q *Queries) CountActiveOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) AS count FROM users
WHERE status = 'active' AND role != 'platform_admin'
`

// 平台总览成员计数：仅 active 状态、非 platform_admin。
// users 表当前没有 soft-delete 字段，status='disabled' 视为下线。
func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppsByStatus = `-- name: CountAppsByStatus :many
SELECT status, COUNT(*) AS count FROM apps
WHERE deleted_at IS NULL
GROUP BY status
`

type CountAppsByStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

// 平台总览应用计数：按 status 分组，soft-deleted 通过 deleted_at IS NULL 排除。
// 调用方在 service 层把结果聚合成 {status: count}，未出现 status 视为 0。
func (q *Queries) CountAppsByStatus(ctx context.Context) ([]CountAppsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countAppsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAppsByStatusRow{}
	for rows.Next() {
		var i CountAppsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
