// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: published_sites.sql

package sqlc

import (
	"context"
	"time"
)

const countActiveSitesByOrg = `-- name: CountActiveSitesByOrg :one
SELECT COUNT(*) FROM published_sites WHERE org_id = ? AND status = 'active'
`

func (q *Queries) CountActiveSitesByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSitesByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublishedSite = `-- name: CreatePublishedSite :exec
INSERT INTO published_sites (
    id, org_id, app_id, host, slug, current_version, s3_prefix, status, size_bytes, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)
`

type CreatePublishedSiteParams struct {
	ID             string    `db:"id" json:"id"`
	OrgID          string    `db:"org_id" json:"org_id"`
	AppID          string    `db:"app_id" json:"app_id"`
	Host           string    `db:"host" json:"host"`
	Slug           string    `db:"slug" json:"slug"`
	CurrentVersion string    `db:"current_version" json:"current_version"`
	S3Prefix       string    `db:"s3_prefix" json:"s3_prefix"`
	SizeBytes      int64     `db:"size_bytes" json:"size_bytes"`
	ExpiresAt      time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreatePublishedSite(ctx context.Context, arg CreatePublishedSiteParams) error {
	_, err := q.db.ExecContext(ctx, createPublishedSite,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Host,
		arg.Slug,
		arg.CurrentVersion,
		arg.S3Prefix,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	return err
}

const getPublishedSiteByHost = `-- name: GetPublishedSiteByHost :one
SELECT id, org_id, app_id, host, slug, current_version, s3_prefix, status, size_bytes, created_at, expires_at, updated_at FROM published_sites WHERE host = ?
`

func (q *Queries) GetPublishedSiteByHost(ctx context.Context, host string) (PublishedSite, error) {
	row := q.db.QueryRowContext(ctx, getPublishedSiteByHost, host)
	var i PublishedSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Host,
		&i.Slug,
		&i.CurrentVersion,
		&i.S3Prefix,
		&i.Status,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedSiteByID = `-- name: GetPublishedSiteByID :one
SELECT id, org_id, app_id, host, slug, current_version, s3_prefix, status, size_bytes, created_at, expires_at, updated_at FROM published_sites WHERE id = ?
`

func (q *Queries) GetPublishedSiteByID(ctx context.Context, id string) (PublishedSite, error) {
	row := q.db.QueryRowContext(ctx, getPublishedSiteByID, id)
	var i PublishedSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Host,
		&i.Slug,
		&i.CurrentVersion,
		&i.S3Prefix,
		&i.Status,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSites = `-- name: ListActiveSites :many
SELECT host, id, s3_prefix, status FROM published_sites WHERE status = 'active'
`

type ListActiveSitesRow struct {
	Host     string `db:"host" json:"host"`
	ID       string `db:"id" json:"id"`
	S3Prefix string `db:"s3_prefix" json:"s3_prefix"`
	Status   string `db:"status" json:"status"`
}

func (q *Queries) ListActiveSites(ctx context.Context) ([]ListActiveSitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSitesRow{}
	for rows.Next() {
		var i ListActiveSitesRow
		if err := rows.Scan(
			&i.Host,
			&i.ID,
			&i.S3Prefix,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveSites = `-- name: ListExpiredActiveSites :many
SELECT id, org_id, app_id, host, slug, current_version, s3_prefix, status, size_bytes, created_at, expires_at, updated_at FROM published_sites WHERE status = 'active' AND expires_at < now()
`

func (q *Queries) ListExpiredActiveSites(ctx context.Context) ([]PublishedSite, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredActiveSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedSite{}
	for rows.Next() {
		var i PublishedSite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Host,
			&i.Slug,
			&i.CurrentVersion,
			&i.S3Prefix,
			&i.Status,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesByOrg = `-- name: ListSitesByOrg :many
SELECT id, org_id, app_id, host, slug, current_version, s3_prefix, status, size_bytes, created_at, expires_at, updated_at FROM published_sites WHERE org_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListSitesByOrg(ctx context.Context, orgID string) ([]PublishedSite, error) {
	rows, err := q.db.QueryContext(ctx, listSitesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishedSite{}
	for rows.Next() {
		var i PublishedSite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Host,
			&i.Slug,
			&i.CurrentVersion,
			&i.S3Prefix,
			&i.Status,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewPublishedSite = `-- name: RenewPublishedSite :exec
UPDATE published_sites
SET expires_at = ?, status = 'active', updated_at = now()
WHERE id = ?
`

type RenewPublishedSiteParams struct {
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	ID        string    `db:"id" json:"id"`
}

// 续期：把过期时间延后到 now + N 天（N 由 service 按企业 site_ttl_days 传入），并置回 active。
func (q *Queries) RenewPublishedSite(ctx context.Context, arg RenewPublishedSiteParams) error {
	_, err := q.db.ExecContext(ctx, renewPublishedSite, arg.ExpiresAt, arg.ID)
	return err
}

const setPublishedSiteStatus = `-- name: SetPublishedSiteStatus :exec
UPDATE published_sites SET status = ?, updated_at = now() WHERE id = ?
`

type SetPublishedSiteStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetPublishedSiteStatus(ctx context.Context, arg SetPublishedSiteStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPublishedSiteStatus, arg.Status, arg.ID)
	return err
}
