// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"encoding/json"

	null "github.com/guregu/null/v5"
)

type Querier interface {
	// 为助手版本追加一个行业知识库关联；只允许关联未删除行业库，复合主键保证同一版本不重复关联。
	AddAssistantVersionIndustryKnowledgeBase(ctx context.Context, arg AddAssistantVersionIndustryKnowledgeBaseParams) (int64, error)
	// 判断指定应用下是否存在 status='bound' 的渠道绑定。
	// app_initialize 在推进到 binding_waiting 之后调用：若发现已 bound（如切换助手
	// 版本触发镜像重建后、容器重启前渠道凭证依旧落在 bind mount 目录、无需用户
	// 重新扫码），则直接把 status 推到 running，避免概览页长期卡在「待绑定」。
	AppHasBoundChannelBinding(ctx context.Context, appID string) (bool, error)
	// 抢占 failed 或超时 creating 的 dataset 创建租约；只有成功更新行的调用方允许访问 RAGFlow 创建远端 dataset。
	ClaimRAGFlowDatasetCreation(ctx context.Context, arg ClaimRAGFlowDatasetCreationParams) error
	// transitionTo / RequestInitialize 强制清空进度字段。
	ClearAppProgress(ctx context.Context, id string) error
	// 统计企业当前未删除实例数（apps.deleted_at IS NULL），用于企业实例数量上限校验。
	CountActiveAppsByOrg(ctx context.Context, orgID string) (int64, error)
	// 平台总览组织计数：剔除 soft-deleted；status='active' 与 'disabled' 都算入册组织。
	CountActiveOrganizations(ctx context.Context) (int64, error)
	CountActiveSitesByOrg(ctx context.Context, orgID string) (int64, error)
	// 平台总览成员计数：仅 active 状态、非 platform_admin。
	// users 表当前没有 soft-delete 字段，status='disabled' 视为下线。
	CountActiveUsers(ctx context.Context) (int64, error)
	// 平台总览应用计数：按 status 分组，soft-deleted 通过 deleted_at IS NULL 排除。
	// 调用方在 service 层把结果聚合成 {status: count}，未出现 status 视为 0。
	CountAppsByStatus(ctx context.Context) ([]CountAppsByStatusRow, error)
	// 严格保护：版本被未删除实例引用时不可删除。
	CountAppsUsingVersion(ctx context.Context, versionID null.String) (int64, error)
	// 统计仍被未删除助手版本引用的行业知识库，避免删除仍在使用的全局知识。
	CountAssistantVersionsUsingIndustryKnowledgeBase(ctx context.Context, industryKnowledgeBaseID string) (int64, error)
	// 统计指定应用下未被标记为 deleted 的渠道绑定数。
	// RuntimeOperationService.Trigger 在写 delete 审计前调用，把数量塞进 detail_message。
	CountChannelBindingsByApp(ctx context.Context, appID string) (int64, error)
	// 统计行业知识库列表总数，过滤条件必须与 ListIndustryKnowledgeBases 保持一致。
	CountIndustryKnowledgeBases(ctx context.Context, arg CountIndustryKnowledgeBasesParams) (int64, error)
	// 严格保护：版本出现在任意未删除组织 allowlist 时不可删除。
	CountOrgsUsingVersion(ctx context.Context, jsonQUOTE string) (int64, error)
	CountPendingSkillTickets(ctx context.Context) (int64, error)
	// 统计扁平文件列表总数，过滤条件必须与 ListRAGFlowDocumentsByScope 保持一致。
	CountRAGFlowDocumentsByScope(ctx context.Context, arg CountRAGFlowDocumentsByScopeParams) (int64, error)
	// 统计行业知识库文件总数，过滤条件必须与 ListRAGFlowIndustryDocuments 保持一致。
	CountRAGFlowIndustryDocuments(ctx context.Context, arg CountRAGFlowIndustryDocumentsParams) (int64, error)
	// k8s 模型下 app 对应 Deployment，pod 落点由调度器决定，不再写 runtime_node_id。
	// locale 在创建时快照 owner 的用户语言偏好（NULL=平台回退默认）。
	CreateApp(ctx context.Context, arg CreateAppParams) error
	CreateAppSkill(ctx context.Context, arg CreateAppSkillParams) error
	CreateAssistantVersion(ctx context.Context, arg CreateAssistantVersionParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateChannelBinding(ctx context.Context, arg CreateChannelBindingParams) error
	CreateConversationFile(ctx context.Context, arg CreateConversationFileParams) error
	// 定制技能相关查询。工单附件三条查询已在 000011 迁移后移除（改用统一消息表 skill_ticket_messages）；
	// 本文件保留 custom_skills / custom_skill_targets / 交付相关查询。
	CreateCustomSkill(ctx context.Context, arg CreateCustomSkillParams) error
	CreateCustomSkillTarget(ctx context.Context, arg CreateCustomSkillTargetParams) error
	// 创建平台级行业知识库；名称唯一性由未删除记录的生成列唯一键兜底。
	CreateIndustryKnowledgeBase(ctx context.Context, arg CreateIndustryKnowledgeBaseParams) error
	CreateJob(ctx context.Context, arg CreateJobParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreatePlatformSkill(ctx context.Context, arg CreatePlatformSkillParams) error
	CreatePublishedSite(ctx context.Context, arg CreatePublishedSiteParams) error
	// 懒创建实例级 dataset 映射；并发首创命中唯一索引时忽略，由 service 读取已有映射且不重复创建远端 dataset。
	CreateRAGFlowAppDatasetMapping(ctx context.Context, arg CreateRAGFlowAppDatasetMappingParams) error
	// 缓存 RAGFlow document 元数据，manager 不保存文件主副本。
	CreateRAGFlowDocument(ctx context.Context, arg CreateRAGFlowDocumentParams) error
	// 懒创建行业知识库 dataset 映射；行业库不归属企业，因此 org/app 字段固定为 NULL。
	CreateRAGFlowIndustryDatasetMapping(ctx context.Context, arg CreateRAGFlowIndustryDatasetMappingParams) error
	// 缓存行业知识库 RAGFlow document 元数据；行业 scope 不归属企业或实例，必须写入行业库外键。
	CreateRAGFlowIndustryDocument(ctx context.Context, arg CreateRAGFlowIndustryDocumentParams) error
	// 懒创建组织级 dataset 映射；并发首创命中唯一索引时忽略，由 service 读取已有映射且不重复创建远端 dataset。
	CreateRAGFlowOrgDatasetMapping(ctx context.Context, arg CreateRAGFlowOrgDatasetMappingParams) error
	CreateRechargeRecord(ctx context.Context, arg CreateRechargeRecordParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateSkillTicket(ctx context.Context, arg CreateSkillTicketParams) error
	CreateSkillTicketMessage(ctx context.Context, arg CreateSkillTicketMessageParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAppSkillByAppAndName(ctx context.Context, arg DeleteAppSkillByAppAndNameParams) error
	DeleteCustomSkillTargetsByName(ctx context.Context, customSkillName string) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeletePlatformSkill(ctx context.Context, id string) error
	// 删除本地 dataset 映射；document 缓存通过外键级联清理。
	DeleteRAGFlowDatasetMapping(ctx context.Context, id string) error
	// 删除本地 document 缓存；RAGFlow 远端删除由 service 在同一业务流程中处理。
	DeleteRAGFlowDocumentMapping(ctx context.Context, id string) error
	GetActiveAppByOwner(ctx context.Context, ownerUserID string) (App, error)
	GetApp(ctx context.Context, id string) (App, error)
	// 按 control token（per-app 三用：bootstrap / oc-kb / oc-ops）的 hash 反查当前 app；
	// 不允许请求方传入目标 app/dataset，鉴权即定位。
	GetAppByRuntimeTokenHash(ctx context.Context, runtimeTokenHash null.String) (App, error)
	GetAppSkillByAppAndName(ctx context.Context, arg GetAppSkillByAppAndNameParams) (AppSkill, error)
	// 取实例及其绑定版本的 revision / image_id，供 version_synced 计算。
	GetAppWithVersion(ctx context.Context, id string) (GetAppWithVersionRow, error)
	GetAssistantVersion(ctx context.Context, id string) (AssistantVersion, error)
	GetAssistantVersionByName(ctx context.Context, name string) (AssistantVersion, error)
	GetAuditLog(ctx context.Context, id string) (AuditLog, error)
	GetChannelBindingByAppAndType(ctx context.Context, arg GetChannelBindingByAppAndTypeParams) (ChannelBinding, error)
	GetConversationFile(ctx context.Context, id string) (ConversationFile, error)
	GetCustomSkillByNameVersion(ctx context.Context, arg GetCustomSkillByNameVersionParams) (CustomSkill, error)
	// 按 ID 读取未删除行业知识库，供管理面详情和后续权限校验使用。
	GetIndustryKnowledgeBase(ctx context.Context, id string) (IndustryKnowledgeBasis, error)
	// 按名称读取未删除行业知识库，用于创建和重命名时做业务提示。
	GetIndustryKnowledgeBaseByName(ctx context.Context, name string) (IndustryKnowledgeBasis, error)
	// 在事务内锁定未删除行业知识库，序列化版本关联写入和行业库删除。
	GetIndustryKnowledgeBaseForUpdate(ctx context.Context, id string) (IndustryKnowledgeBasis, error)
	GetJob(ctx context.Context, id string) (Job, error)
	// reaper 通过 payload_json->>'$.app_id' 查最近一份 app_initialize job。
	// 用 ORDER BY created_at DESC + LIMIT 1 取最新；不存在返回 sql.ErrNoRows。
	GetLatestAppInitJob(ctx context.Context, appID json.RawMessage) (Job, error)
	GetLatestCustomSkillByName(ctx context.Context, name string) (CustomSkill, error)
	// 组织列表复制登录信息时只需要一个可登录的组织管理员用户名。
	// 密码明文不落库，因此这里只返回账号名，密码提示由调用方生成。
	GetOrgAdminByOrg(ctx context.Context, orgID null.String) (User, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetOrganizationByCode(ctx context.Context, code string) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	// OOS-2 access_token 自愈用：以行锁查询组织，避免并发更新密文时出现写丢失。
	GetOrganizationForUpdate(ctx context.Context, id string) (Organization, error)
	GetPlatformSkill(ctx context.Context, id string) (PlatformSkill, error)
	GetPlatformSkillByNameVersion(ctx context.Context, arg GetPlatformSkillByNameVersionParams) (PlatformSkill, error)
	GetPublishedSiteByHost(ctx context.Context, host string) (PublishedSite, error)
	GetPublishedSiteByID(ctx context.Context, id string) (PublishedSite, error)
	// 读取实例知识库 dataset 映射，runtime 写入只能落到该 dataset。
	GetRAGFlowAppDataset(ctx context.Context, appID null.String) (RagflowDataset, error)
	// 按 ID 读取 dataset 记录，供 ClaimRAGFlowDatasetCreation 后的读回。
	GetRAGFlowDataset(ctx context.Context, id string) (RagflowDataset, error)
	// 按 manager 本地 ID 读取 document 缓存，供下载和删除前做权限校验。
	GetRAGFlowDocument(ctx context.Context, id string) (RagflowDocument, error)
	// 按 RAGFlow document ID 读取缓存，用于解析状态回刷和幂等处理。
	GetRAGFlowDocumentByRemoteID(ctx context.Context, arg GetRAGFlowDocumentByRemoteIDParams) (RagflowDocument, error)
	// 读取行业知识库 dataset 映射，供行业知识库文件管理和远端同步使用。
	GetRAGFlowIndustryDataset(ctx context.Context, industryKnowledgeBaseID null.String) (RagflowDataset, error)
	// 按行业知识库和文件名读取缓存，用于上传前幂等与重名校验。
	GetRAGFlowIndustryDocumentByName(ctx context.Context, arg GetRAGFlowIndustryDocumentByNameParams) (RagflowDocument, error)
	// 读取组织知识库 dataset 映射，供管理面列表和 runtime 检索使用。
	GetRAGFlowOrgDataset(ctx context.Context, orgID null.String) (RagflowDataset, error)
	GetRechargeRecord(ctx context.Context, id string) (RechargeRecord, error)
	GetRefreshToken(ctx context.Context, id string) (RefreshToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSkillTicket(ctx context.Context, id string) (SkillTicket, error)
	GetSkillTicketMessage(ctx context.Context, id string) (SkillTicketMessage, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByOrgAndUsername(ctx context.Context, arg GetUserByOrgAndUsernameParams) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// 按企业取发布能力配置；不存在返回 sql.ErrNoRows（视为未开通）。
	GetWebPublishConfig(ctx context.Context, orgID string) (OrgWebPublishConfig, error)
	// 用于组织创建链路失败时回滚刚刚 INSERT 的孤儿记录。
	// 正常生命周期不可见此查询；普通"删除"必须走 SoftDeleteOrganization。
	HardDeleteOrganization(ctx context.Context, id string) error
	ListActiveSites(ctx context.Context) ([]ListActiveSitesRow, error)
	// 全量返回活跃组织（deleted_at IS NULL），不分页；
	// 仅供平台内部聚合使用（如 GetOrgUsageBreakdown），请勿用于用户可见的列表接口。
	ListAllActiveOrganizations(ctx context.Context) ([]Organization, error)
	ListAllCustomSkills(ctx context.Context) ([]CustomSkill, error)
	// 清空企业或实例知识库时列出指定业务 scope 下的全部 document，不受分页和筛选条件影响。
	ListAllRAGFlowDocumentsByScope(ctx context.Context, arg ListAllRAGFlowDocumentsByScopeParams) ([]RagflowDocument, error)
	// 清空行业知识库文件内容时列出该行业库下的全部 document，不受分页、日期和状态筛选影响。
	ListAllRAGFlowIndustryDocuments(ctx context.Context, industryKnowledgeBaseID null.String) ([]RagflowDocument, error)
	ListAllSkillTickets(ctx context.Context) ([]SkillTicket, error)
	ListAppSkillsByApp(ctx context.Context, appID string) ([]AppSkill, error)
	ListAppSkillsBySourceRef(ctx context.Context, arg ListAppSkillsBySourceRefParams) ([]AppSkill, error)
	ListAppsByOrg(ctx context.Context, arg ListAppsByOrgParams) ([]App, error)
	// 组织实例列表联查版本 revision / image_id，供 version_synced 批量计算。
	ListAppsByOrgWithVersion(ctx context.Context, arg ListAppsByOrgWithVersionParams) ([]ListAppsByOrgWithVersionRow, error)
	ListAssistantVersions(ctx context.Context) ([]AssistantVersion, error)
	// 返回审计行 + actor 实时名称 + target 实时名称（按 target_type 走子查询）。
	// 子查询里 WHERE al.target_type = X 保证 newapi_call 的 endpoint 字符串
	// 永不被尝试转 UUID，避开 cast error。
	ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]ListAuditLogsByOrgRow, error)
	// 同 ListAuditLogsByOrg，按 target_type + target_id 过滤。
	ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]ListAuditLogsByTargetRow, error)
	// 证书续签巡检：列出已签发且 cert_not_after 早于阈值的企业配置（需续签）。
	ListConfigsCertExpiringBefore(ctx context.Context, certNotAfter null.Time) ([]OrgWebPublishConfig, error)
	ListCustomSkillTargetsByName(ctx context.Context, customSkillName string) ([]CustomSkillTarget, error)
	ListCustomSkillVersionsByName(ctx context.Context, name string) ([]CustomSkill, error)
	ListDistinctAppSkillSources(ctx context.Context) ([]ListDistinctAppSkillSourcesRow, error)
	// reconciler 兜底用：列出 status=error 的 app。reconciler 查其 pod，若 hermes 实际 Ready
	// （说明并非真失败，只是状态没收敛，如 WaitReady 曾误超时但 pod 后来起来了），就重新入队
	// init job 推进到 running；pod 真坏则保持 error 不动。reaper 只扫 init 子状态、不管 error，
	// 此查询补上「init 失败成 error 后无法自愈」的洞。
	ListErrorApps(ctx context.Context) ([]string, error)
	ListExpiredActiveSites(ctx context.Context) ([]PublishedSite, error)
	// 分页列出行业知识库，并统计行业 scope 下已缓存的 RAGFlow 文档数量。
	ListIndustryKnowledgeBases(ctx context.Context, arg ListIndustryKnowledgeBasesParams) ([]ListIndustryKnowledgeBasesRow, error)
	// 列出助手版本关联的未删除行业知识库，供发布配置和运行时检索范围使用。
	ListIndustryKnowledgeBasesByAssistantVersion(ctx context.Context, versionID string) ([]IndustryKnowledgeBasis, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPlatformSkills(ctx context.Context) ([]PlatformSkill, error)
	// 扁平列出某个组织或实例知识库文件，支持按状态和文件名过滤。
	ListRAGFlowDocumentsByScope(ctx context.Context, arg ListRAGFlowDocumentsByScopeParams) ([]RagflowDocument, error)
	// 找出需要刷新解析状态的 document，按最久未更新优先；
	// 同时连出所属 RAGFlow dataset 的远端 ID，供后台刷新任务直接调 RAGFlow ListDocuments。
	// 远端 dataset 尚未创建（ragflow_dataset_id IS NULL）的文档不会出现：
	// 此类文档此时本就无法从 RAGFlow 拉取状态，等 dataset 创建完成后再轮询即可。
	ListRAGFlowDocumentsNeedingRefresh(ctx context.Context, limit int32) ([]ListRAGFlowDocumentsNeedingRefreshRow, error)
	// 全库列出 failed/stopped 且远端 dataset 仍存在的文档,供自愈任务逐个重解析。带远端 dataset id 以直接调 RAGFlow。
	ListRAGFlowFailedDocumentsForHeal(ctx context.Context, limit int32) ([]ListRAGFlowFailedDocumentsForHealRow, error)
	// 分页列出行业知识库文件，支持按解析状态、文件名和创建时间过滤。
	ListRAGFlowIndustryDocuments(ctx context.Context, arg ListRAGFlowIndustryDocumentsParams) ([]RagflowDocument, error)
	// 全库列出 running 超过给定时刻仍未推进(updated_at 即「进入 running 时刻」,刷新任务状态不变时不写库)的文档,
	// 供自愈任务 stop_parsing→reparse。只取 running、不取 queued(排队是正常积压,不在此恢复)。
	ListRAGFlowStuckRunningDocumentsForHeal(ctx context.Context, arg ListRAGFlowStuckRunningDocumentsForHealParams) ([]ListRAGFlowStuckRunningDocumentsForHealRow, error)
	ListReadyJobs(ctx context.Context, limit int32) ([]Job, error)
	ListRechargeRecordsByOrg(ctx context.Context, arg ListRechargeRecordsByOrgParams) ([]RechargeRecord, error)
	// reconciler 收敛用：列出 status=restarting 的 app id。渠道解绑触发 RolloutRestart 后
	// 实例置 restarting，pod 重建（Recreate）期间 oc-ops 不可用；reconciler 周期查其 pod 状态，
	// pod 重新 Ready → 收敛回 running，pod 坏死 → error，重启空窗（Pending）→ 保持 restarting 等下轮。
	ListRestartingApps(ctx context.Context) ([]string, error)
	// 列出当前期望运行（k8s Deployment 已创建）的应用，供 app_status_reconciler 周期 poll pod 状态。
	// running 是常态；binding_waiting 表示 pod 已起但渠道还在登录中，也需要 reconcile；
	// binding_failed 表示上轮扫码超时，pod 仍在（属渠道发起 allowlist，需 reconciler 维护其 runtime_phase）。
	// spec-A2b：去掉 runtime_node_id / container_id（k8s 路径不再写这两列），消费方仅用 id。
	ListRunningApps(ctx context.Context) ([]string, error)
	ListSitesByOrg(ctx context.Context, orgID string) ([]PublishedSite, error)
	ListSkillTicketMessages(ctx context.Context, ticketID string) ([]SkillTicketMessage, error)
	ListSkillTicketsByRequester(ctx context.Context, requesterUserID string) ([]SkillTicket, error)
	// reaper 扫描 init 子状态下「连续 N 秒无更新」的孤儿；N 由调用方按秒传入。
	// 包含新旧两套 init 状态，确保历史孤儿也能被正确清理。
	// spec-A2b：去掉 runtime_node_id（k8s 路径不再写该列），reaper 仅需 id / status 重置孤儿。
	// 关键：阈值用 SQL 侧 now() - INTERVAL 计算，而非接收 Go 侧 time.Now() 阈值。
	// updated_at 由 now() 写入，二者同处服务器时钟与会话时区，根除「Go 时间 vs now() 列」
	// 跨时区比较错位（曾因 DSN loc=UTC 与服务器 +08:00 不匹配导致本查询恒返回 0，孤儿永不回收）。
	ListStaleInits(ctx context.Context, dateSUB interface{}) ([]ListStaleInitsRow, error)
	ListUsersByOrg(ctx context.Context, arg ListUsersByOrgParams) ([]User, error)
	// 列出组织内成员及其当前关联的活跃实例（LEFT JOIN，无实例的成员仍返回）。
	// apps 表上 apps_owner_active 唯一约束保证每个 owner 最多一个未软删实例，
	// LEFT JOIN 不会产生重复行；ORDER BY 保持与 ListUsersByOrg 一致。
	ListUsersByOrgWithActiveApp(ctx context.Context, arg ListUsersByOrgWithActiveAppParams) ([]ListUsersByOrgWithActiveAppRow, error)
	// 市场可见性：返回对某主体(org_id + 是否管理员 + user_id)可见的定制技能(含申请人名与命中受众)。
	// 同名多行(多版本)由 service 取首条(created_at DESC)为最新。
	ListVisibleCustomSkills(ctx context.Context, arg ListVisibleCustomSkillsParams) ([]ListVisibleCustomSkillsRow, error)
	// 平台管理员全局视图：列出所有企业的发布能力配置。
	ListWebPublishConfigs(ctx context.Context) ([]OrgWebPublishConfig, error)
	LockJobForUpdate(ctx context.Context, id string) (Job, error)
	// 任意状态 → error 时同时写入来源状态与错误文本，保留"在哪一步失败"与"为什么失败"语义。
	// last_error_status 不加 CHECK 约束，值由调用方在 Go 层负责合法性。
	MarkAppFailed(ctx context.Context, arg MarkAppFailedParams) error
	MarkChannelBindingBound(ctx context.Context, arg MarkChannelBindingBoundParams) error
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error
	MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) error
	MarkJobSucceeded(ctx context.Context, id string) error
	// 标记 dataset 生命周期失败，保留错误文本用于管理面排障。
	MarkRAGFlowDatasetFailed(ctx context.Context, arg MarkRAGFlowDatasetFailedParams) error
	// 人工重解析表示用户显式介入，把文档重置为 queued 交刷新任务继续推进。
	MarkRAGFlowDocumentManualReparseQueued(ctx context.Context, id string) error
	MarkSkillTicketDelivered(ctx context.Context, arg MarkSkillTicketDeliveredParams) error
	MarkUserLoggedIn(ctx context.Context, id string) error
	RejectSkillTicket(ctx context.Context, arg RejectSkillTicketParams) error
	// 重命名未删除行业知识库；唯一约束负责拦截同名未删除记录。
	RenameIndustryKnowledgeBase(ctx context.Context, arg RenameIndustryKnowledgeBaseParams) error
	// 续期：把过期时间延后到 now + N 天（N 由 service 按企业 site_ttl_days 传入），并置回 active。
	RenewPublishedSite(ctx context.Context, arg RenewPublishedSiteParams) error
	// 替换助手版本行业知识库关联前先清空旧关联，由调用方在同一事务中重新插入。
	ReplaceAssistantVersionIndustryKnowledgeBases(ctx context.Context, versionID string) error
	// 覆盖行业库同名文件时按旧远端 document ID 乐观替换本地映射；created_by 表示最近一次覆盖上传人，created_at 仍保留首创时间。
	ReplaceRAGFlowIndustryDocument(ctx context.Context, arg ReplaceRAGFlowIndustryDocumentParams) error
	// reaper 把已 running / succeeded 的 job 重置为 pending。
	// locked_by / locked_at 一并清空避免被旧 worker 误识别为本机持有。
	// 注意：jobs 表无 started_at 列，仅清 locked_* / last_error / 状态。
	RequeueJob(ctx context.Context, id string) error
	// 整库 embedding 模型切换后，把该 dataset 下所有本地 document 状态重置为 queued，交给现有刷新任务继续推进。
	ResetRAGFlowDocumentsParseStatusByDataset(ctx context.Context, datasetID string) error
	RetryJob(ctx context.Context, arg RetryJobParams) error
	RevokeRefreshToken(ctx context.Context, id string) error
	RevokeRefreshTokensByUser(ctx context.Context, userID string) error
	// 初始化/重启成功后记录已应用的版本修订与镜像 ref，用于 version_synced 检测。
	SetAppAppliedVersion(ctx context.Context, arg SetAppAppliedVersionParams) error
	// worker app_health_check handler 写最近一次健康检查结果；用于自动重启窗口计数。
	SetAppHealthState(ctx context.Context, arg SetAppHealthStateParams) error
	// 更新单个实例知识库累计容量上限；允许低于当前已用，后续上传由 KnowledgeService 拒绝。
	SetAppKnowledgeQuota(ctx context.Context, arg SetAppKnowledgeQuotaParams) error
	SetAppNewAPIKey(ctx context.Context, arg SetAppNewAPIKeyParams) error
	// progressReporter 节流后写入；NULL/NULL 表示阶段切换或未知。
	SetAppProgress(ctx context.Context, arg SetAppProgressParams) error
	// 管理员 PATCH /apps/:appId/restart-policy 写入；mode/max_per_window/window_seconds 校验在 service 层。
	SetAppRestartPolicy(ctx context.Context, arg SetAppRestartPolicyParams) error
	// 裸 UPDATE runtime_phase(运行时就绪维度,与 status 正交,无状态机守卫,守卫不适用):
	// reconciler 周期写、init worker 首启/就绪写、渠道解绑/升级重启前置 restarting 用。
	SetAppRuntimePhase(ctx context.Context, arg SetAppRuntimePhaseParams) error
	SetAppRuntimeSnapshot(ctx context.Context, arg SetAppRuntimeSnapshotParams) error
	// 首次写入 per-app control token（三用：bootstrap / oc-kb / oc-ops）；并发重复初始化拿不到行，由 service 读取既有 token。
	SetAppRuntimeToken(ctx context.Context, arg SetAppRuntimeTokenParams) error
	SetAppStatus(ctx context.Context, arg SetAppStatusParams) error
	// 切换实例绑定的助手版本，并把 applied_version_revision / applied_image_ref 清零。
	// 不同版本各自维护独立的 revision 计数，若切换后保留旧 applied_*，当新旧版本
	// 的 revision 数字恰好相同（且镜像相同）时 version_synced 会误判为已同步。
	// 清零后 applied_version_revision=0 永远不等于任何真实版本 revision（从 1 起），
	// 实例切换后必然进入需重启态，直到重启重新写入 applied_*。
	SetAppVersion(ctx context.Context, arg SetAppVersionParams) error
	SetChannelBindingChallenge(ctx context.Context, arg SetChannelBindingChallengeParams) error
	SetChannelBindingStatus(ctx context.Context, arg SetChannelBindingStatusParams) error
	// 写入飞书凭证 metadata（app_id 明文 + secret 密文 + domain + bot 信息 + injected 标记）并置状态。
	// 供 BeginAuth service（Task 14）与凭证注入 worker（Task 17）调用。
	SetFeishuCredentials(ctx context.Context, arg SetFeishuCredentialsParams) error
	SetOrganizationNewAPIUser(ctx context.Context, arg SetOrganizationNewAPIUserParams) error
	SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) error
	SetPublishedSiteStatus(ctx context.Context, arg SetPublishedSiteStatusParams) error
	// 远端 dataset 创建成功后写入 RAGFlow ID，并清理上一轮生命周期错误。
	SetRAGFlowDatasetActive(ctx context.Context, arg SetRAGFlowDatasetActiveParams) error
	SetSkillTicketQuote(ctx context.Context, arg SetSkillTicketQuoteParams) error
	// disabled 时同步写 deleted_at（下线时间戳）；enabled 时清空，让重启用户能恢复。
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) error
	// 状态机/巡检更新证书状态：状态 + 到期 + 最近签发时间 + 最近续签时间 + 摘要。
	// cert_last_renewed_at 用 COALESCE 跳过传 NULL 的场景（首签只更新 issued_at，续签更新 renewed_at）。
	SetWebPublishCertStatus(ctx context.Context, arg SetWebPublishCertStatusParams) error
	// 开通/停用：置 enabled 与 provisioning_status（开通时由 service 传 'provisioning'）。
	SetWebPublishEnabled(ctx context.Context, arg SetWebPublishEnabledParams) error
	// 状态机更新 provisioning 结果：状态 + 摘要 + 证书 Secret 名。
	SetWebPublishProvisioning(ctx context.Context, arg SetWebPublishProvisioningParams) error
	SoftDeleteApp(ctx context.Context, id string) error
	SoftDeleteAssistantVersion(ctx context.Context, id string) error
	// 软删除未被助手版本引用的行业知识库；删除后名称可被重新使用。
	SoftDeleteIndustryKnowledgeBase(ctx context.Context, id string) (int64, error)
	SoftDeleteOrganization(ctx context.Context, id string) error
	// 真软删除：仅设置 deleted_at（不动 status）；status 与 deleted_at 语义独立。
	SoftDeleteUser(ctx context.Context, id string) error
	// 汇总知识库当前累计占用；失败/停止文件仍占用 RAGFlow 原文件存储，因此全部状态都计入。
	SumRAGFlowDocumentsSizeByScope(ctx context.Context, arg SumRAGFlowDocumentsSizeByScopeParams) (int64, error)
	// SumRechargeAmountByOrg 聚合指定组织所有成功充值记录的总额。
	// 仅统计 status='succeeded' 的记录，failed 记录不计入累计金额。
	SumRechargeAmountByOrg(ctx context.Context, orgID string) (int64, error)
	// 仅刷新 updated_at：worker 等待 pod Ready 期间的心跳。让 reaper 凭 updated_at 区分
	// 「worker 仍在等待（拉镜像可能数十分钟）」与「worker 已死的孤儿」，避免误回收正在处理的 job。
	// 不改 status 或其它字段。
	TouchApp(ctx context.Context, id string) error
	TouchSkillTicket(ctx context.Context, id string) error
	// 更新实例语言偏好（hermes 对终端用户说话的语言）。locale 由 service 层校验合法取值后传入。
	UpdateAppLocale(ctx context.Context, arg UpdateAppLocaleParams) error
	// phasePullRuntimeImage 成功后写入镜像引用与 sha256。
	UpdateAppRuntimeImage(ctx context.Context, arg UpdateAppRuntimeImageParams) error
	UpdateAppSkillLatest(ctx context.Context, arg UpdateAppSkillLatestParams) error
	UpdateAppSkillVersion(ctx context.Context, arg UpdateAppSkillVersionParams) error
	// revision 由 service 计算后整体写入（仅容器相关字段变更才递增）。
	UpdateAssistantVersion(ctx context.Context, arg UpdateAssistantVersionParams) error
	// skill 上传/删除单独走此查询：只改 skills_json 与 revision，避免覆盖其它字段。
	UpdateAssistantVersionSkills(ctx context.Context, arg UpdateAssistantVersionSkillsParams) error
	// OOS-2 access_token 自愈用：仅更新 newapi_user_credentials_ciphertext，不动 newapi_user_id。
	UpdateOrganizationCredentialsCiphertext(ctx context.Context, arg UpdateOrganizationCredentialsCiphertextParams) error
	UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) error
	UpdatePublishedSiteVersion(ctx context.Context, arg UpdatePublishedSiteVersionParams) error
	// 回写解析状态、进度和错误；状态值由 service 层从 RAGFlow run 值归一化。
	UpdateRAGFlowDocumentParseStatus(ctx context.Context, arg UpdateRAGFlowDocumentParseStatusParams) error
	UpdateSkillTicketStatus(ctx context.Context, arg UpdateSkillTicketStatusParams) error
	// 更新用户界面语言偏好。locale 由 handler 校验取值集合后传入；NULL 表示重置为「未选择」。
	UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// 飞书无预建绑定行，BeginAuth 时 create-on-demand（已存在则忽略）。
	// app_active_key 是 VIRTUAL 生成列（非 deleted 行 = app_id），不能显式赋值，
	// ON DUPLICATE KEY 命中唯一约束 (app_active_key, channel_type) 时做 no-op。
	UpsertChannelBindingUnbound(ctx context.Context, arg UpsertChannelBindingUnboundParams) error
	// 平台管理员配置/改配置：写基础域名 / provider / 凭证密文 / 配额。
	// 不触碰 provisioning_status 与 cert_* 状态（那由状态机维护），首插时取列默认值。
	UpsertWebPublishConfig(ctx context.Context, arg UpsertWebPublishConfigParams) error
}

var _ Querier = (*Queries)(nil)
