// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateChannelBinding(ctx context.Context, arg CreateChannelBindingParams) (ChannelBinding, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOrganizationPersona(ctx context.Context, arg CreateOrganizationPersonaParams) (OrganizationPersona, error)
	CreateRechargeRecord(ctx context.Context, arg CreateRechargeRecordParams) (RechargeRecord, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRuntimeNode(ctx context.Context, arg CreateRuntimeNodeParams) (RuntimeNode, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetActiveAppByOwner(ctx context.Context, ownerUserID pgtype.UUID) (App, error)
	GetApp(ctx context.Context, id pgtype.UUID) (App, error)
	GetChannelBindingByAppAndType(ctx context.Context, arg GetChannelBindingByAppAndTypeParams) (ChannelBinding, error)
	GetCurrentOrganizationPersona(ctx context.Context, orgID pgtype.UUID) (OrganizationPersona, error)
	GetJob(ctx context.Context, id pgtype.UUID) (Job, error)
	// 查询单个 (org, node) 对的状态，主要用于幂等判断。
	GetKnowledgeSyncStatus(ctx context.Context, arg GetKnowledgeSyncStatusParams) (KnowledgeSyncStatus, error)
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRuntimeNode(ctx context.Context, id pgtype.UUID) (RuntimeNode, error)
	GetRuntimeNodeByName(ctx context.Context, name string) (RuntimeNode, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAppsByOrg(ctx context.Context, arg ListAppsByOrgParams) ([]App, error)
	ListAppsByRuntimeNode(ctx context.Context, arg ListAppsByRuntimeNodeParams) ([]App, error)
	ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error)
	ListAuditLogsByTarget(ctx context.Context, arg ListAuditLogsByTargetParams) ([]AuditLog, error)
	// 列出某组织在所有节点上的最近同步状态。
	ListKnowledgeSyncStatusByOrg(ctx context.Context, orgID pgtype.UUID) ([]KnowledgeSyncStatus, error)
	ListOrganizationPersonaVersions(ctx context.Context, arg ListOrganizationPersonaVersionsParams) ([]OrganizationPersona, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListReadyJobs(ctx context.Context, limit int32) ([]Job, error)
	ListRechargeRecordsByOrg(ctx context.Context, arg ListRechargeRecordsByOrgParams) ([]RechargeRecord, error)
	// 列出当前期望持有 OpenClaw 容器的应用，供 scheduler 周期 dispatch
	// runtime_refresh_status 与 app_health_check job。
	// running 是常态；binding_waiting 表示容器已起但渠道还在登录中，依然要刷指标。
	ListRunningApps(ctx context.Context) ([]ListRunningAppsRow, error)
	ListRuntimeNodes(ctx context.Context, arg ListRuntimeNodesParams) ([]RuntimeNode, error)
	ListUsersByOrg(ctx context.Context, arg ListUsersByOrgParams) ([]User, error)
	LockJobForUpdate(ctx context.Context, id pgtype.UUID) (Job, error)
	MarkChannelBindingBound(ctx context.Context, arg MarkChannelBindingBoundParams) (ChannelBinding, error)
	MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error)
	MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) (Job, error)
	MarkJobSucceeded(ctx context.Context, id pgtype.UUID) (Job, error)
	MarkUserLoggedIn(ctx context.Context, id pgtype.UUID) (User, error)
	RegisterRuntimeNode(ctx context.Context, arg RegisterRuntimeNodeParams) (RuntimeNode, error)
	RetryJob(ctx context.Context, arg RetryJobParams) (Job, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	SetAppContainer(ctx context.Context, arg SetAppContainerParams) (App, error)
	SetAppNewAPIKey(ctx context.Context, arg SetAppNewAPIKeyParams) (App, error)
	SetAppRuntimeSnapshot(ctx context.Context, arg SetAppRuntimeSnapshotParams) (App, error)
	SetAppStatus(ctx context.Context, arg SetAppStatusParams) (App, error)
	SetChannelBindingChallenge(ctx context.Context, arg SetChannelBindingChallengeParams) (ChannelBinding, error)
	SetChannelBindingStatus(ctx context.Context, arg SetChannelBindingStatusParams) (ChannelBinding, error)
	SetOrganizationStatus(ctx context.Context, arg SetOrganizationStatusParams) (Organization, error)
	SetRuntimeNodeStatus(ctx context.Context, arg SetRuntimeNodeStatusParams) (RuntimeNode, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	SoftDeleteApp(ctx context.Context, id pgtype.UUID) (App, error)
	SoftDeleteOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (Organization, error)
	UpdateRuntimeNodeHeartbeat(ctx context.Context, arg UpdateRuntimeNodeHeartbeatParams) (RuntimeNode, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// 插入或更新 (org_id, node_id) 的最近同步状态。
	// last_success_at 通过 sqlc.arg 显式传入，调用方在 status='synced' 时传 now()，
	// 其它状态传 NULL 表示保留之前的成功时间（COALESCE 在 SQL 内处理）。
	UpsertKnowledgeSyncStatus(ctx context.Context, arg UpsertKnowledgeSyncStatusParams) (KnowledgeSyncStatus, error)
}

var _ Querier = (*Queries)(nil)
