// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ragflow_knowledge.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRAGFlowDocumentsByScope = `-- name: CountRAGFlowDocumentsByScope :one
SELECT count(*)
FROM ragflow_documents
WHERE scope_type = $1
  AND org_id = $2
  AND ($3::uuid IS NULL OR app_id = $3::uuid)
  AND ($4::text IS NULL OR parse_status = $4::text)
  AND ($5::text IS NULL OR name ILIKE '%' || $5::text || '%')
`

type CountRAGFlowDocumentsByScopeParams struct {
	ScopeType   string      `db:"scope_type" json:"scope_type"`
	OrgID       pgtype.UUID `db:"org_id" json:"org_id"`
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ParseStatus pgtype.Text `db:"parse_status" json:"parse_status"`
	Keywords    pgtype.Text `db:"keywords" json:"keywords"`
}

// 统计扁平文件列表总数，过滤条件必须与 ListRAGFlowDocumentsByScope 保持一致。
func (q *Queries) CountRAGFlowDocumentsByScope(ctx context.Context, arg CountRAGFlowDocumentsByScopeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRAGFlowDocumentsByScope,
		arg.ScopeType,
		arg.OrgID,
		arg.AppID,
		arg.ParseStatus,
		arg.Keywords,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRAGFlowDatasetMapping = `-- name: CreateRAGFlowDatasetMapping :one
INSERT INTO ragflow_datasets (
    scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error, created_at, updated_at
`

type CreateRAGFlowDatasetMappingParams struct {
	ScopeType        string      `db:"scope_type" json:"scope_type"`
	OrgID            pgtype.UUID `db:"org_id" json:"org_id"`
	AppID            pgtype.UUID `db:"app_id" json:"app_id"`
	RagflowDatasetID pgtype.Text `db:"ragflow_dataset_id" json:"ragflow_dataset_id"`
	Name             string      `db:"name" json:"name"`
	Status           string      `db:"status" json:"status"`
	LastError        pgtype.Text `db:"last_error" json:"last_error"`
}

// 创建 manager scope 到 RAGFlow dataset 的本地映射，远端创建失败时可先记录 failed 状态便于排障。
func (q *Queries) CreateRAGFlowDatasetMapping(ctx context.Context, arg CreateRAGFlowDatasetMappingParams) (RagflowDataset, error) {
	row := q.db.QueryRow(ctx, createRAGFlowDatasetMapping,
		arg.ScopeType,
		arg.OrgID,
		arg.AppID,
		arg.RagflowDatasetID,
		arg.Name,
		arg.Status,
		arg.LastError,
	)
	var i RagflowDataset
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDatasetID,
		&i.Name,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRAGFlowDocument = `-- name: CreateRAGFlowDocument :one
INSERT INTO ragflow_documents (
    dataset_id, scope_type, org_id, app_id, ragflow_document_id, name,
    size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
`

type CreateRAGFlowDocumentParams struct {
	DatasetID         pgtype.UUID `db:"dataset_id" json:"dataset_id"`
	ScopeType         string      `db:"scope_type" json:"scope_type"`
	OrgID             pgtype.UUID `db:"org_id" json:"org_id"`
	AppID             pgtype.UUID `db:"app_id" json:"app_id"`
	RagflowDocumentID string      `db:"ragflow_document_id" json:"ragflow_document_id"`
	Name              string      `db:"name" json:"name"`
	SizeBytes         int64       `db:"size_bytes" json:"size_bytes"`
	MimeType          pgtype.Text `db:"mime_type" json:"mime_type"`
	Suffix            pgtype.Text `db:"suffix" json:"suffix"`
	ParseStatus       string      `db:"parse_status" json:"parse_status"`
	Progress          int32       `db:"progress" json:"progress"`
	LastError         pgtype.Text `db:"last_error" json:"last_error"`
	CreatedBy         string      `db:"created_by" json:"created_by"`
}

// 缓存 RAGFlow document 元数据，manager 不保存文件主副本。
func (q *Queries) CreateRAGFlowDocument(ctx context.Context, arg CreateRAGFlowDocumentParams) (RagflowDocument, error) {
	row := q.db.QueryRow(ctx, createRAGFlowDocument,
		arg.DatasetID,
		arg.ScopeType,
		arg.OrgID,
		arg.AppID,
		arg.RagflowDocumentID,
		arg.Name,
		arg.SizeBytes,
		arg.MimeType,
		arg.Suffix,
		arg.ParseStatus,
		arg.Progress,
		arg.LastError,
		arg.CreatedBy,
	)
	var i RagflowDocument
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDocumentID,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.Suffix,
		&i.ParseStatus,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRAGFlowDatasetMapping = `-- name: DeleteRAGFlowDatasetMapping :exec
DELETE FROM ragflow_datasets
WHERE id = $1
`

// 删除本地 dataset 映射；document 缓存通过外键级联清理。
func (q *Queries) DeleteRAGFlowDatasetMapping(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRAGFlowDatasetMapping, id)
	return err
}

const deleteRAGFlowDocumentMapping = `-- name: DeleteRAGFlowDocumentMapping :exec
DELETE FROM ragflow_documents
WHERE id = $1
`

// 删除本地 document 缓存；RAGFlow 远端删除由 service 在同一业务流程中处理。
func (q *Queries) DeleteRAGFlowDocumentMapping(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRAGFlowDocumentMapping, id)
	return err
}

const getRAGFlowAppDataset = `-- name: GetRAGFlowAppDataset :one
SELECT id, scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error, created_at, updated_at
FROM ragflow_datasets
WHERE scope_type = 'app' AND app_id = $1
`

// 读取实例知识库 dataset 映射，runtime 写入只能落到该 dataset。
func (q *Queries) GetRAGFlowAppDataset(ctx context.Context, appID pgtype.UUID) (RagflowDataset, error) {
	row := q.db.QueryRow(ctx, getRAGFlowAppDataset, appID)
	var i RagflowDataset
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDatasetID,
		&i.Name,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRAGFlowDocument = `-- name: GetRAGFlowDocument :one
SELECT id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
FROM ragflow_documents
WHERE id = $1
`

// 按 manager 本地 ID 读取 document 缓存，供下载和删除前做权限校验。
func (q *Queries) GetRAGFlowDocument(ctx context.Context, id pgtype.UUID) (RagflowDocument, error) {
	row := q.db.QueryRow(ctx, getRAGFlowDocument, id)
	var i RagflowDocument
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDocumentID,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.Suffix,
		&i.ParseStatus,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRAGFlowDocumentByRemoteID = `-- name: GetRAGFlowDocumentByRemoteID :one
SELECT id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
FROM ragflow_documents
WHERE dataset_id = $1 AND ragflow_document_id = $2
`

type GetRAGFlowDocumentByRemoteIDParams struct {
	DatasetID         pgtype.UUID `db:"dataset_id" json:"dataset_id"`
	RagflowDocumentID string      `db:"ragflow_document_id" json:"ragflow_document_id"`
}

// 按 RAGFlow document ID 读取缓存，用于解析状态回刷和幂等处理。
func (q *Queries) GetRAGFlowDocumentByRemoteID(ctx context.Context, arg GetRAGFlowDocumentByRemoteIDParams) (RagflowDocument, error) {
	row := q.db.QueryRow(ctx, getRAGFlowDocumentByRemoteID, arg.DatasetID, arg.RagflowDocumentID)
	var i RagflowDocument
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDocumentID,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.Suffix,
		&i.ParseStatus,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRAGFlowOrgDataset = `-- name: GetRAGFlowOrgDataset :one
SELECT id, scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error, created_at, updated_at
FROM ragflow_datasets
WHERE scope_type = 'org' AND org_id = $1
`

// 读取组织知识库 dataset 映射，供管理面列表和 runtime 检索使用。
func (q *Queries) GetRAGFlowOrgDataset(ctx context.Context, orgID pgtype.UUID) (RagflowDataset, error) {
	row := q.db.QueryRow(ctx, getRAGFlowOrgDataset, orgID)
	var i RagflowDataset
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDatasetID,
		&i.Name,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRAGFlowDocumentsByScope = `-- name: ListRAGFlowDocumentsByScope :many
SELECT id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
FROM ragflow_documents
WHERE scope_type = $1
  AND org_id = $2
  AND ($5::uuid IS NULL OR app_id = $5::uuid)
  AND ($6::text IS NULL OR parse_status = $6::text)
  AND ($7::text IS NULL OR name ILIKE '%' || $7::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListRAGFlowDocumentsByScopeParams struct {
	ScopeType   string      `db:"scope_type" json:"scope_type"`
	OrgID       pgtype.UUID `db:"org_id" json:"org_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
	AppID       pgtype.UUID `db:"app_id" json:"app_id"`
	ParseStatus pgtype.Text `db:"parse_status" json:"parse_status"`
	Keywords    pgtype.Text `db:"keywords" json:"keywords"`
}

// 扁平列出某个组织或实例知识库文件，支持按状态和文件名过滤。
func (q *Queries) ListRAGFlowDocumentsByScope(ctx context.Context, arg ListRAGFlowDocumentsByScopeParams) ([]RagflowDocument, error) {
	rows, err := q.db.Query(ctx, listRAGFlowDocumentsByScope,
		arg.ScopeType,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.AppID,
		arg.ParseStatus,
		arg.Keywords,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RagflowDocument{}
	for rows.Next() {
		var i RagflowDocument
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.ScopeType,
			&i.OrgID,
			&i.AppID,
			&i.RagflowDocumentID,
			&i.Name,
			&i.SizeBytes,
			&i.MimeType,
			&i.Suffix,
			&i.ParseStatus,
			&i.Progress,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRAGFlowDocumentsNeedingRefresh = `-- name: ListRAGFlowDocumentsNeedingRefresh :many
SELECT id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
FROM ragflow_documents
WHERE parse_status IN ('queued', 'running')
ORDER BY updated_at ASC
LIMIT $1
`

// 找出需要刷新解析状态的 document，按最久未更新优先。
func (q *Queries) ListRAGFlowDocumentsNeedingRefresh(ctx context.Context, limit int32) ([]RagflowDocument, error) {
	rows, err := q.db.Query(ctx, listRAGFlowDocumentsNeedingRefresh, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RagflowDocument{}
	for rows.Next() {
		var i RagflowDocument
		if err := rows.Scan(
			&i.ID,
			&i.DatasetID,
			&i.ScopeType,
			&i.OrgID,
			&i.AppID,
			&i.RagflowDocumentID,
			&i.Name,
			&i.SizeBytes,
			&i.MimeType,
			&i.Suffix,
			&i.ParseStatus,
			&i.Progress,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRAGFlowDatasetFailed = `-- name: MarkRAGFlowDatasetFailed :one
UPDATE ragflow_datasets
SET status = 'failed', last_error = $2, updated_at = now()
WHERE id = $1
RETURNING id, scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error, created_at, updated_at
`

type MarkRAGFlowDatasetFailedParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	LastError pgtype.Text `db:"last_error" json:"last_error"`
}

// 标记 dataset 生命周期失败，保留错误文本用于管理面排障。
func (q *Queries) MarkRAGFlowDatasetFailed(ctx context.Context, arg MarkRAGFlowDatasetFailedParams) (RagflowDataset, error) {
	row := q.db.QueryRow(ctx, markRAGFlowDatasetFailed, arg.ID, arg.LastError)
	var i RagflowDataset
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDatasetID,
		&i.Name,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRAGFlowDatasetActive = `-- name: SetRAGFlowDatasetActive :one
UPDATE ragflow_datasets
SET ragflow_dataset_id = $2,
    name = $3,
    status = 'active',
    last_error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, scope_type, org_id, app_id, ragflow_dataset_id, name, status, last_error, created_at, updated_at
`

type SetRAGFlowDatasetActiveParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	RagflowDatasetID pgtype.Text `db:"ragflow_dataset_id" json:"ragflow_dataset_id"`
	Name             string      `db:"name" json:"name"`
}

// 远端 dataset 创建成功后写入 RAGFlow ID，并清理上一轮生命周期错误。
func (q *Queries) SetRAGFlowDatasetActive(ctx context.Context, arg SetRAGFlowDatasetActiveParams) (RagflowDataset, error) {
	row := q.db.QueryRow(ctx, setRAGFlowDatasetActive, arg.ID, arg.RagflowDatasetID, arg.Name)
	var i RagflowDataset
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDatasetID,
		&i.Name,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRAGFlowDocumentParseStatus = `-- name: UpdateRAGFlowDocumentParseStatus :one
UPDATE ragflow_documents
SET parse_status = $2, progress = $3, last_error = $4, updated_at = now()
WHERE id = $1
RETURNING id, dataset_id, scope_type, org_id, app_id, ragflow_document_id, name, size_bytes, mime_type, suffix, parse_status, progress, last_error, created_by, created_at, updated_at
`

type UpdateRAGFlowDocumentParseStatusParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	ParseStatus string      `db:"parse_status" json:"parse_status"`
	Progress    int32       `db:"progress" json:"progress"`
	LastError   pgtype.Text `db:"last_error" json:"last_error"`
}

// 回写解析状态、进度和错误；状态值由 service 层从 RAGFlow run 值归一化。
func (q *Queries) UpdateRAGFlowDocumentParseStatus(ctx context.Context, arg UpdateRAGFlowDocumentParseStatusParams) (RagflowDocument, error) {
	row := q.db.QueryRow(ctx, updateRAGFlowDocumentParseStatus,
		arg.ID,
		arg.ParseStatus,
		arg.Progress,
		arg.LastError,
	)
	var i RagflowDocument
	err := row.Scan(
		&i.ID,
		&i.DatasetID,
		&i.ScopeType,
		&i.OrgID,
		&i.AppID,
		&i.RagflowDocumentID,
		&i.Name,
		&i.SizeBytes,
		&i.MimeType,
		&i.Suffix,
		&i.ParseStatus,
		&i.Progress,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
