// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recharge_records.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRechargeRecord = `-- name: CreateRechargeRecord :one
INSERT INTO recharge_records (
    org_id,
    operator_id,
    credit_amount,
    remark,
    newapi_ref_id,
    status,
    error_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, org_id, operator_id, credit_amount, remark, newapi_ref_id, status, error_message, created_at
`

type CreateRechargeRecordParams struct {
	OrgID        pgtype.UUID `db:"org_id" json:"org_id"`
	OperatorID   pgtype.UUID `db:"operator_id" json:"operator_id"`
	CreditAmount int64       `db:"credit_amount" json:"credit_amount"`
	Remark       pgtype.Text `db:"remark" json:"remark"`
	NewapiRefID  pgtype.Text `db:"newapi_ref_id" json:"newapi_ref_id"`
	Status       string      `db:"status" json:"status"`
	ErrorMessage pgtype.Text `db:"error_message" json:"error_message"`
}

func (q *Queries) CreateRechargeRecord(ctx context.Context, arg CreateRechargeRecordParams) (RechargeRecord, error) {
	row := q.db.QueryRow(ctx, createRechargeRecord,
		arg.OrgID,
		arg.OperatorID,
		arg.CreditAmount,
		arg.Remark,
		arg.NewapiRefID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i RechargeRecord
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OperatorID,
		&i.CreditAmount,
		&i.Remark,
		&i.NewapiRefID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listRechargeRecordsByOrg = `-- name: ListRechargeRecordsByOrg :many
SELECT id, org_id, operator_id, credit_amount, remark, newapi_ref_id, status, error_message, created_at
FROM recharge_records
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRechargeRecordsByOrgParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListRechargeRecordsByOrg(ctx context.Context, arg ListRechargeRecordsByOrgParams) ([]RechargeRecord, error) {
	rows, err := q.db.Query(ctx, listRechargeRecordsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RechargeRecord{}
	for rows.Next() {
		var i RechargeRecord
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OperatorID,
			&i.CreditAmount,
			&i.Remark,
			&i.NewapiRefID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
