// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_samples.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldInstanceResourceSamples = `-- name: DeleteOldInstanceResourceSamples :execrows
DELETE FROM instance_resource_samples
WHERE id IN (
    SELECT s.id
    FROM instance_resource_samples AS s
    WHERE s.sampled_at < $1
    ORDER BY s.sampled_at ASC
    LIMIT $2::integer
)
`

type DeleteOldInstanceResourceSamplesParams struct {
	CutoffSampledAt pgtype.Timestamptz `db:"cutoff_sampled_at" json:"cutoff_sampled_at"`
	BatchSize       int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) DeleteOldInstanceResourceSamples(ctx context.Context, arg DeleteOldInstanceResourceSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldInstanceResourceSamples, arg.CutoffSampledAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldNodeResourceSamples = `-- name: DeleteOldNodeResourceSamples :execrows
DELETE FROM node_resource_samples
WHERE id IN (
    SELECT s.id
    FROM node_resource_samples AS s
    WHERE s.sampled_at < $1
    ORDER BY s.sampled_at ASC
    LIMIT $2::integer
)
`

type DeleteOldNodeResourceSamplesParams struct {
	CutoffSampledAt pgtype.Timestamptz `db:"cutoff_sampled_at" json:"cutoff_sampled_at"`
	BatchSize       int32              `db:"batch_size" json:"batch_size"`
}

func (q *Queries) DeleteOldNodeResourceSamples(ctx context.Context, arg DeleteOldNodeResourceSamplesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNodeResourceSamples, arg.CutoffSampledAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestInstanceResourceSample = `-- name: GetLatestInstanceResourceSample :one
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE app_id = $1
ORDER BY sampled_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestInstanceResourceSample(ctx context.Context, appID pgtype.UUID) (InstanceResourceSample, error) {
	row := q.db.QueryRow(ctx, getLatestInstanceResourceSample, appID)
	var i InstanceResourceSample
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.RuntimeNodeID,
		&i.ContainerID,
		&i.SampledAt,
		&i.ContainerStatus,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryLimitBytes,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestNodeResourceSample = `-- name: GetLatestNodeResourceSample :one
SELECT id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
FROM node_resource_samples
WHERE runtime_node_id = $1
ORDER BY sampled_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestNodeResourceSample(ctx context.Context, runtimeNodeID pgtype.UUID) (NodeResourceSample, error) {
	row := q.db.QueryRow(ctx, getLatestNodeResourceSample, runtimeNodeID)
	var i NodeResourceSample
	err := row.Scan(
		&i.ID,
		&i.RuntimeNodeID,
		&i.SampledAt,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.InstanceCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstanceResourceSample = `-- name: InsertInstanceResourceSample :one
INSERT INTO instance_resource_samples (
    app_id, runtime_node_id, container_id, sampled_at, container_status,
    cpu_percent, memory_used_bytes, memory_limit_bytes,
    disk_read_bytes, disk_write_bytes,
    network_rx_bytes, network_tx_bytes, last_error
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12, $13
)
RETURNING id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
`

type InsertInstanceResourceSampleParams struct {
	AppID            pgtype.UUID        `db:"app_id" json:"app_id"`
	RuntimeNodeID    pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	ContainerID      string             `db:"container_id" json:"container_id"`
	SampledAt        pgtype.Timestamptz `db:"sampled_at" json:"sampled_at"`
	ContainerStatus  pgtype.Text        `db:"container_status" json:"container_status"`
	CpuPercent       pgtype.Float8      `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  pgtype.Int8        `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryLimitBytes pgtype.Int8        `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	DiskReadBytes    pgtype.Int8        `db:"disk_read_bytes" json:"disk_read_bytes"`
	DiskWriteBytes   pgtype.Int8        `db:"disk_write_bytes" json:"disk_write_bytes"`
	NetworkRxBytes   pgtype.Int8        `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   pgtype.Int8        `db:"network_tx_bytes" json:"network_tx_bytes"`
	LastError        pgtype.Text        `db:"last_error" json:"last_error"`
}

func (q *Queries) InsertInstanceResourceSample(ctx context.Context, arg InsertInstanceResourceSampleParams) (InstanceResourceSample, error) {
	row := q.db.QueryRow(ctx, insertInstanceResourceSample,
		arg.AppID,
		arg.RuntimeNodeID,
		arg.ContainerID,
		arg.SampledAt,
		arg.ContainerStatus,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryLimitBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.NetworkRxBytes,
		arg.NetworkTxBytes,
		arg.LastError,
	)
	var i InstanceResourceSample
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.RuntimeNodeID,
		&i.ContainerID,
		&i.SampledAt,
		&i.ContainerStatus,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryLimitBytes,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertNodeResourceSample = `-- name: InsertNodeResourceSample :one
INSERT INTO node_resource_samples (
    runtime_node_id, sampled_at, cpu_percent,
    memory_used_bytes, memory_total_bytes,
    disk_used_bytes, disk_total_bytes,
    network_rx_bytes, network_tx_bytes,
    instance_count, last_error
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8, $9,
    $10, $11
)
RETURNING id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
`

type InsertNodeResourceSampleParams struct {
	RuntimeNodeID    pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	SampledAt        pgtype.Timestamptz `db:"sampled_at" json:"sampled_at"`
	CpuPercent       pgtype.Float8      `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  pgtype.Int8        `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryTotalBytes pgtype.Int8        `db:"memory_total_bytes" json:"memory_total_bytes"`
	DiskUsedBytes    pgtype.Int8        `db:"disk_used_bytes" json:"disk_used_bytes"`
	DiskTotalBytes   pgtype.Int8        `db:"disk_total_bytes" json:"disk_total_bytes"`
	NetworkRxBytes   pgtype.Int8        `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   pgtype.Int8        `db:"network_tx_bytes" json:"network_tx_bytes"`
	InstanceCount    pgtype.Int4        `db:"instance_count" json:"instance_count"`
	LastError        pgtype.Text        `db:"last_error" json:"last_error"`
}

func (q *Queries) InsertNodeResourceSample(ctx context.Context, arg InsertNodeResourceSampleParams) (NodeResourceSample, error) {
	row := q.db.QueryRow(ctx, insertNodeResourceSample,
		arg.RuntimeNodeID,
		arg.SampledAt,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryTotalBytes,
		arg.DiskUsedBytes,
		arg.DiskTotalBytes,
		arg.NetworkRxBytes,
		arg.NetworkTxBytes,
		arg.InstanceCount,
		arg.LastError,
	)
	var i NodeResourceSample
	err := row.Scan(
		&i.ID,
		&i.RuntimeNodeID,
		&i.SampledAt,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.InstanceCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listInstanceResourceBuckets = `-- name: ListInstanceResourceBuckets :many
SELECT
    to_timestamp(floor(extract(epoch FROM sampled_at) / $2::integer)::bigint * $2::integer)::timestamptz AS sampled_at,
    COALESCE(((array_remove(array_agg(container_status ORDER BY sampled_at DESC), NULL))[1])::text, ''::text)::text AS container_status,
    count(container_status) > 0 AS has_container_status,
    COALESCE(avg(cpu_percent)::double precision, 0::double precision)::double precision AS cpu_percent,
    count(cpu_percent) > 0 AS has_cpu_percent,
    COALESCE(avg(memory_used_bytes)::bigint, 0::bigint)::bigint AS memory_used_bytes,
    count(memory_used_bytes) > 0 AS has_memory_used_bytes,
    COALESCE(max(memory_limit_bytes)::bigint, 0::bigint)::bigint AS memory_limit_bytes,
    count(memory_limit_bytes) > 0 AS has_memory_limit_bytes,
    COALESCE(min(disk_read_bytes)::bigint, 0::bigint)::bigint AS disk_read_bytes,
    count(disk_read_bytes) > 0 AS has_disk_read_bytes,
    COALESCE(min(disk_write_bytes)::bigint, 0::bigint)::bigint AS disk_write_bytes,
    count(disk_write_bytes) > 0 AS has_disk_write_bytes,
    COALESCE(min(network_rx_bytes)::bigint, 0::bigint)::bigint AS network_rx_bytes,
    count(network_rx_bytes) > 0 AS has_network_rx_bytes,
    COALESCE(min(network_tx_bytes)::bigint, 0::bigint)::bigint AS network_tx_bytes,
    count(network_tx_bytes) > 0 AS has_network_tx_bytes,
    COALESCE(((array_remove(array_agg(last_error ORDER BY sampled_at DESC), NULL))[1])::text, ''::text)::text AS last_error,
    count(last_error) > 0 AS has_last_error
FROM instance_resource_samples
WHERE app_id = $1
  AND sampled_at >= $3
  AND sampled_at <= $4
GROUP BY 1
ORDER BY 1 ASC
`

type ListInstanceResourceBucketsParams struct {
	AppID         pgtype.UUID        `db:"app_id" json:"app_id"`
	BucketSeconds int32              `db:"bucket_seconds" json:"bucket_seconds"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListInstanceResourceBucketsRow struct {
	SampledAt           pgtype.Timestamptz `db:"sampled_at" json:"sampled_at"`
	ContainerStatus     string             `db:"container_status" json:"container_status"`
	HasContainerStatus  bool               `db:"has_container_status" json:"has_container_status"`
	CpuPercent          float64            `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool               `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64              `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool               `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryLimitBytes    int64              `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	HasMemoryLimitBytes bool               `db:"has_memory_limit_bytes" json:"has_memory_limit_bytes"`
	DiskReadBytes       int64              `db:"disk_read_bytes" json:"disk_read_bytes"`
	HasDiskReadBytes    bool               `db:"has_disk_read_bytes" json:"has_disk_read_bytes"`
	DiskWriteBytes      int64              `db:"disk_write_bytes" json:"disk_write_bytes"`
	HasDiskWriteBytes   bool               `db:"has_disk_write_bytes" json:"has_disk_write_bytes"`
	NetworkRxBytes      int64              `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool               `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64              `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool               `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	LastError           string             `db:"last_error" json:"last_error"`
	HasLastError        bool               `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListInstanceResourceBuckets(ctx context.Context, arg ListInstanceResourceBucketsParams) ([]ListInstanceResourceBucketsRow, error) {
	rows, err := q.db.Query(ctx, listInstanceResourceBuckets,
		arg.AppID,
		arg.BucketSeconds,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceResourceBucketsRow{}
	for rows.Next() {
		var i ListInstanceResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.ContainerStatus,
			&i.HasContainerStatus,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.HasMemoryLimitBytes,
			&i.DiskReadBytes,
			&i.HasDiskReadBytes,
			&i.DiskWriteBytes,
			&i.HasDiskWriteBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceResourceSamples = `-- name: ListInstanceResourceSamples :many
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE app_id = $1
  AND sampled_at >= $2
  AND sampled_at <= $3
ORDER BY sampled_at ASC, id ASC
`

type ListInstanceResourceSamplesParams struct {
	AppID         pgtype.UUID        `db:"app_id" json:"app_id"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListInstanceResourceSamples(ctx context.Context, arg ListInstanceResourceSamplesParams) ([]InstanceResourceSample, error) {
	rows, err := q.db.Query(ctx, listInstanceResourceSamples, arg.AppID, arg.FromSampledAt, arg.ToSampledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestInstanceResourceSamplesByNode = `-- name: ListLatestInstanceResourceSamplesByNode :many
SELECT DISTINCT ON (app_id) id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE runtime_node_id = $1
ORDER BY app_id, sampled_at DESC, id DESC
`

func (q *Queries) ListLatestInstanceResourceSamplesByNode(ctx context.Context, runtimeNodeID pgtype.UUID) ([]InstanceResourceSample, error) {
	rows, err := q.db.Query(ctx, listLatestInstanceResourceSamplesByNode, runtimeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestNodeResourceSamples = `-- name: ListLatestNodeResourceSamples :many
SELECT DISTINCT ON (runtime_node_id) id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
FROM node_resource_samples
WHERE runtime_node_id = ANY($1::uuid[])
ORDER BY runtime_node_id, sampled_at DESC, id DESC
`

func (q *Queries) ListLatestNodeResourceSamples(ctx context.Context, runtimeNodeIds []pgtype.UUID) ([]NodeResourceSample, error) {
	rows, err := q.db.Query(ctx, listLatestNodeResourceSamples, runtimeNodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeResourceSample{}
	for rows.Next() {
		var i NodeResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeNodeID,
			&i.SampledAt,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.DiskTotalBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.InstanceCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceResourceBuckets = `-- name: ListNodeInstanceResourceBuckets :many
SELECT
    to_timestamp(floor(extract(epoch FROM sampled_at) / $3::integer)::bigint * $3::integer)::timestamptz AS sampled_at,
    COALESCE(((array_remove(array_agg(container_status ORDER BY sampled_at DESC), NULL))[1])::text, ''::text)::text AS container_status,
    count(container_status) > 0 AS has_container_status,
    COALESCE(avg(cpu_percent)::double precision, 0::double precision)::double precision AS cpu_percent,
    count(cpu_percent) > 0 AS has_cpu_percent,
    COALESCE(avg(memory_used_bytes)::bigint, 0::bigint)::bigint AS memory_used_bytes,
    count(memory_used_bytes) > 0 AS has_memory_used_bytes,
    COALESCE(max(memory_limit_bytes)::bigint, 0::bigint)::bigint AS memory_limit_bytes,
    count(memory_limit_bytes) > 0 AS has_memory_limit_bytes,
    COALESCE(min(disk_read_bytes)::bigint, 0::bigint)::bigint AS disk_read_bytes,
    count(disk_read_bytes) > 0 AS has_disk_read_bytes,
    COALESCE(min(disk_write_bytes)::bigint, 0::bigint)::bigint AS disk_write_bytes,
    count(disk_write_bytes) > 0 AS has_disk_write_bytes,
    COALESCE(min(network_rx_bytes)::bigint, 0::bigint)::bigint AS network_rx_bytes,
    count(network_rx_bytes) > 0 AS has_network_rx_bytes,
    COALESCE(min(network_tx_bytes)::bigint, 0::bigint)::bigint AS network_tx_bytes,
    count(network_tx_bytes) > 0 AS has_network_tx_bytes,
    COALESCE(((array_remove(array_agg(last_error ORDER BY sampled_at DESC), NULL))[1])::text, ''::text)::text AS last_error,
    count(last_error) > 0 AS has_last_error
FROM instance_resource_samples
WHERE runtime_node_id = $1
  AND app_id = $2
  AND sampled_at >= $4
  AND sampled_at <= $5
GROUP BY 1
ORDER BY 1 ASC
`

type ListNodeInstanceResourceBucketsParams struct {
	RuntimeNodeID pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	AppID         pgtype.UUID        `db:"app_id" json:"app_id"`
	BucketSeconds int32              `db:"bucket_seconds" json:"bucket_seconds"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListNodeInstanceResourceBucketsRow struct {
	SampledAt           pgtype.Timestamptz `db:"sampled_at" json:"sampled_at"`
	ContainerStatus     string             `db:"container_status" json:"container_status"`
	HasContainerStatus  bool               `db:"has_container_status" json:"has_container_status"`
	CpuPercent          float64            `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool               `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64              `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool               `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryLimitBytes    int64              `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	HasMemoryLimitBytes bool               `db:"has_memory_limit_bytes" json:"has_memory_limit_bytes"`
	DiskReadBytes       int64              `db:"disk_read_bytes" json:"disk_read_bytes"`
	HasDiskReadBytes    bool               `db:"has_disk_read_bytes" json:"has_disk_read_bytes"`
	DiskWriteBytes      int64              `db:"disk_write_bytes" json:"disk_write_bytes"`
	HasDiskWriteBytes   bool               `db:"has_disk_write_bytes" json:"has_disk_write_bytes"`
	NetworkRxBytes      int64              `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool               `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64              `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool               `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	LastError           string             `db:"last_error" json:"last_error"`
	HasLastError        bool               `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListNodeInstanceResourceBuckets(ctx context.Context, arg ListNodeInstanceResourceBucketsParams) ([]ListNodeInstanceResourceBucketsRow, error) {
	rows, err := q.db.Query(ctx, listNodeInstanceResourceBuckets,
		arg.RuntimeNodeID,
		arg.AppID,
		arg.BucketSeconds,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeInstanceResourceBucketsRow{}
	for rows.Next() {
		var i ListNodeInstanceResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.ContainerStatus,
			&i.HasContainerStatus,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.HasMemoryLimitBytes,
			&i.DiskReadBytes,
			&i.HasDiskReadBytes,
			&i.DiskWriteBytes,
			&i.HasDiskWriteBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceResourceSamples = `-- name: ListNodeInstanceResourceSamples :many
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE runtime_node_id = $1
  AND app_id = $2
  AND sampled_at >= $3
  AND sampled_at <= $4
ORDER BY sampled_at ASC, id ASC
`

type ListNodeInstanceResourceSamplesParams struct {
	RuntimeNodeID pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	AppID         pgtype.UUID        `db:"app_id" json:"app_id"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListNodeInstanceResourceSamples(ctx context.Context, arg ListNodeInstanceResourceSamplesParams) ([]InstanceResourceSample, error) {
	rows, err := q.db.Query(ctx, listNodeInstanceResourceSamples,
		arg.RuntimeNodeID,
		arg.AppID,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeResourceBuckets = `-- name: ListNodeResourceBuckets :many
SELECT
    to_timestamp(floor(extract(epoch FROM sampled_at) / $2::integer)::bigint * $2::integer)::timestamptz AS sampled_at,
    COALESCE(avg(cpu_percent)::double precision, 0::double precision)::double precision AS cpu_percent,
    count(cpu_percent) > 0 AS has_cpu_percent,
    COALESCE(avg(memory_used_bytes)::bigint, 0::bigint)::bigint AS memory_used_bytes,
    count(memory_used_bytes) > 0 AS has_memory_used_bytes,
    COALESCE(max(memory_total_bytes)::bigint, 0::bigint)::bigint AS memory_total_bytes,
    count(memory_total_bytes) > 0 AS has_memory_total_bytes,
    COALESCE(avg(disk_used_bytes)::bigint, 0::bigint)::bigint AS disk_used_bytes,
    count(disk_used_bytes) > 0 AS has_disk_used_bytes,
    COALESCE(max(disk_total_bytes)::bigint, 0::bigint)::bigint AS disk_total_bytes,
    count(disk_total_bytes) > 0 AS has_disk_total_bytes,
    COALESCE(min(network_rx_bytes)::bigint, 0::bigint)::bigint AS network_rx_bytes,
    count(network_rx_bytes) > 0 AS has_network_rx_bytes,
    COALESCE(min(network_tx_bytes)::bigint, 0::bigint)::bigint AS network_tx_bytes,
    count(network_tx_bytes) > 0 AS has_network_tx_bytes,
    COALESCE(avg(instance_count)::integer, 0::integer)::integer AS instance_count,
    count(instance_count) > 0 AS has_instance_count,
    COALESCE(((array_remove(array_agg(last_error ORDER BY sampled_at DESC), NULL))[1])::text, ''::text)::text AS last_error,
    count(last_error) > 0 AS has_last_error
FROM node_resource_samples
WHERE runtime_node_id = $1
  AND sampled_at >= $3
  AND sampled_at <= $4
GROUP BY 1
ORDER BY 1 ASC
`

type ListNodeResourceBucketsParams struct {
	RuntimeNodeID pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	BucketSeconds int32              `db:"bucket_seconds" json:"bucket_seconds"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListNodeResourceBucketsRow struct {
	SampledAt           pgtype.Timestamptz `db:"sampled_at" json:"sampled_at"`
	CpuPercent          float64            `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool               `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64              `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool               `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryTotalBytes    int64              `db:"memory_total_bytes" json:"memory_total_bytes"`
	HasMemoryTotalBytes bool               `db:"has_memory_total_bytes" json:"has_memory_total_bytes"`
	DiskUsedBytes       int64              `db:"disk_used_bytes" json:"disk_used_bytes"`
	HasDiskUsedBytes    bool               `db:"has_disk_used_bytes" json:"has_disk_used_bytes"`
	DiskTotalBytes      int64              `db:"disk_total_bytes" json:"disk_total_bytes"`
	HasDiskTotalBytes   bool               `db:"has_disk_total_bytes" json:"has_disk_total_bytes"`
	NetworkRxBytes      int64              `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool               `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64              `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool               `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	InstanceCount       int32              `db:"instance_count" json:"instance_count"`
	HasInstanceCount    bool               `db:"has_instance_count" json:"has_instance_count"`
	LastError           string             `db:"last_error" json:"last_error"`
	HasLastError        bool               `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListNodeResourceBuckets(ctx context.Context, arg ListNodeResourceBucketsParams) ([]ListNodeResourceBucketsRow, error) {
	rows, err := q.db.Query(ctx, listNodeResourceBuckets,
		arg.RuntimeNodeID,
		arg.BucketSeconds,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeResourceBucketsRow{}
	for rows.Next() {
		var i ListNodeResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.HasMemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.HasDiskUsedBytes,
			&i.DiskTotalBytes,
			&i.HasDiskTotalBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.InstanceCount,
			&i.HasInstanceCount,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeResourceSamples = `-- name: ListNodeResourceSamples :many
SELECT id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
FROM node_resource_samples
WHERE runtime_node_id = $1
  AND sampled_at >= $2
  AND sampled_at <= $3
ORDER BY sampled_at ASC, id ASC
`

type ListNodeResourceSamplesParams struct {
	RuntimeNodeID pgtype.UUID        `db:"runtime_node_id" json:"runtime_node_id"`
	FromSampledAt pgtype.Timestamptz `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   pgtype.Timestamptz `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListNodeResourceSamples(ctx context.Context, arg ListNodeResourceSamplesParams) ([]NodeResourceSample, error) {
	rows, err := q.db.Query(ctx, listNodeResourceSamples, arg.RuntimeNodeID, arg.FromSampledAt, arg.ToSampledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeResourceSample{}
	for rows.Next() {
		var i NodeResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeNodeID,
			&i.SampledAt,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.DiskTotalBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.InstanceCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
