// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_samples.sql

package sqlc

import (
	"context"
	"strings"
	"time"

	null "github.com/guregu/null/v5"
)

const deleteOldInstanceResourceSamples = `-- name: DeleteOldInstanceResourceSamples :execrows
DELETE FROM instance_resource_samples
WHERE id IN (
    SELECT id FROM (
        SELECT s.id
        FROM instance_resource_samples AS s
        WHERE s.sampled_at < ?
        ORDER BY s.sampled_at ASC
        LIMIT ?
    ) AS x
)
`

type DeleteOldInstanceResourceSamplesParams struct {
	CutoffSampledAt time.Time `db:"cutoff_sampled_at" json:"cutoff_sampled_at"`
	Limit           int32     `db:"limit" json:"limit"`
}

// 批量清理过期实例采样，避免全表 DELETE 锁争用；
// MySQL 不支持 LIMIT 直接用于 IN 子查询，故用双层派生表绕过限制。
func (q *Queries) DeleteOldInstanceResourceSamples(ctx context.Context, arg DeleteOldInstanceResourceSamplesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldInstanceResourceSamples, arg.CutoffSampledAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldNodeResourceSamples = `-- name: DeleteOldNodeResourceSamples :execrows
DELETE FROM node_resource_samples
WHERE id IN (
    SELECT id FROM (
        SELECT s.id
        FROM node_resource_samples AS s
        WHERE s.sampled_at < ?
        ORDER BY s.sampled_at ASC
        LIMIT ?
    ) AS x
)
`

type DeleteOldNodeResourceSamplesParams struct {
	CutoffSampledAt time.Time `db:"cutoff_sampled_at" json:"cutoff_sampled_at"`
	Limit           int32     `db:"limit" json:"limit"`
}

// 批量清理过期节点采样，避免全表 DELETE 锁争用；
// MySQL 不支持 LIMIT 直接用于 IN 子查询，故用双层派生表绕过限制。
func (q *Queries) DeleteOldNodeResourceSamples(ctx context.Context, arg DeleteOldNodeResourceSamplesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldNodeResourceSamples, arg.CutoffSampledAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestInstanceResourceSample = `-- name: GetLatestInstanceResourceSample :one
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE app_id = ?
ORDER BY sampled_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestInstanceResourceSample(ctx context.Context, appID string) (InstanceResourceSample, error) {
	row := q.db.QueryRowContext(ctx, getLatestInstanceResourceSample, appID)
	var i InstanceResourceSample
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.RuntimeNodeID,
		&i.ContainerID,
		&i.SampledAt,
		&i.ContainerStatus,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryLimitBytes,
		&i.DiskReadBytes,
		&i.DiskWriteBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestNodeResourceSample = `-- name: GetLatestNodeResourceSample :one
SELECT id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
FROM node_resource_samples
WHERE runtime_node_id = ?
ORDER BY sampled_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestNodeResourceSample(ctx context.Context, runtimeNodeID string) (NodeResourceSample, error) {
	row := q.db.QueryRowContext(ctx, getLatestNodeResourceSample, runtimeNodeID)
	var i NodeResourceSample
	err := row.Scan(
		&i.ID,
		&i.RuntimeNodeID,
		&i.SampledAt,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.MemoryTotalBytes,
		&i.DiskUsedBytes,
		&i.DiskTotalBytes,
		&i.NetworkRxBytes,
		&i.NetworkTxBytes,
		&i.InstanceCount,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertInstanceResourceSample = `-- name: InsertInstanceResourceSample :exec
INSERT INTO instance_resource_samples (
    id, app_id, runtime_node_id, container_id, sampled_at, container_status,
    cpu_percent, memory_used_bytes, memory_limit_bytes,
    disk_read_bytes, disk_write_bytes,
    network_rx_bytes, network_tx_bytes, last_error
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?, ?
)
`

type InsertInstanceResourceSampleParams struct {
	ID               string      `db:"id" json:"id"`
	AppID            string      `db:"app_id" json:"app_id"`
	RuntimeNodeID    string      `db:"runtime_node_id" json:"runtime_node_id"`
	ContainerID      string      `db:"container_id" json:"container_id"`
	SampledAt        time.Time   `db:"sampled_at" json:"sampled_at"`
	ContainerStatus  null.String `db:"container_status" json:"container_status"`
	CpuPercent       null.Float  `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  null.Int    `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryLimitBytes null.Int    `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	DiskReadBytes    null.Int    `db:"disk_read_bytes" json:"disk_read_bytes"`
	DiskWriteBytes   null.Int    `db:"disk_write_bytes" json:"disk_write_bytes"`
	NetworkRxBytes   null.Int    `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   null.Int    `db:"network_tx_bytes" json:"network_tx_bytes"`
	LastError        null.String `db:"last_error" json:"last_error"`
}

func (q *Queries) InsertInstanceResourceSample(ctx context.Context, arg InsertInstanceResourceSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertInstanceResourceSample,
		arg.ID,
		arg.AppID,
		arg.RuntimeNodeID,
		arg.ContainerID,
		arg.SampledAt,
		arg.ContainerStatus,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryLimitBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.NetworkRxBytes,
		arg.NetworkTxBytes,
		arg.LastError,
	)
	return err
}

const insertNodeResourceSample = `-- name: InsertNodeResourceSample :exec
INSERT INTO node_resource_samples (
    id, runtime_node_id, sampled_at, cpu_percent,
    memory_used_bytes, memory_total_bytes,
    disk_used_bytes, disk_total_bytes,
    network_rx_bytes, network_tx_bytes,
    instance_count, last_error
) VALUES (
    ?, ?, ?, ?,
    ?, ?,
    ?, ?,
    ?, ?,
    ?, ?
)
`

type InsertNodeResourceSampleParams struct {
	ID               string      `db:"id" json:"id"`
	RuntimeNodeID    string      `db:"runtime_node_id" json:"runtime_node_id"`
	SampledAt        time.Time   `db:"sampled_at" json:"sampled_at"`
	CpuPercent       null.Float  `db:"cpu_percent" json:"cpu_percent"`
	MemoryUsedBytes  null.Int    `db:"memory_used_bytes" json:"memory_used_bytes"`
	MemoryTotalBytes null.Int    `db:"memory_total_bytes" json:"memory_total_bytes"`
	DiskUsedBytes    null.Int    `db:"disk_used_bytes" json:"disk_used_bytes"`
	DiskTotalBytes   null.Int    `db:"disk_total_bytes" json:"disk_total_bytes"`
	NetworkRxBytes   null.Int    `db:"network_rx_bytes" json:"network_rx_bytes"`
	NetworkTxBytes   null.Int    `db:"network_tx_bytes" json:"network_tx_bytes"`
	InstanceCount    null.Int    `db:"instance_count" json:"instance_count"`
	LastError        null.String `db:"last_error" json:"last_error"`
}

func (q *Queries) InsertNodeResourceSample(ctx context.Context, arg InsertNodeResourceSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeResourceSample,
		arg.ID,
		arg.RuntimeNodeID,
		arg.SampledAt,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryTotalBytes,
		arg.DiskUsedBytes,
		arg.DiskTotalBytes,
		arg.NetworkRxBytes,
		arg.NetworkTxBytes,
		arg.InstanceCount,
		arg.LastError,
	)
	return err
}

const listInstanceResourceBuckets = `-- name: ListInstanceResourceBuckets :many
SELECT
    CAST(FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(sampled_at) / CAST(? AS SIGNED)) * CAST(? AS SIGNED)) AS DATETIME) AS sampled_at,
    COALESCE(SUBSTRING_INDEX(GROUP_CONCAT(container_status ORDER BY sampled_at DESC SEPARATOR '\x1e'), '\x1e', 1), '') AS container_status,
    COUNT(container_status) > 0 AS has_container_status,
    CAST(COALESCE(AVG(cpu_percent), 0) AS DOUBLE) AS cpu_percent,
    COUNT(cpu_percent) > 0 AS has_cpu_percent,
    CAST(COALESCE(AVG(memory_used_bytes), 0) AS SIGNED) AS memory_used_bytes,
    COUNT(memory_used_bytes) > 0 AS has_memory_used_bytes,
    CAST(COALESCE(MAX(memory_limit_bytes), 0) AS SIGNED) AS memory_limit_bytes,
    COUNT(memory_limit_bytes) > 0 AS has_memory_limit_bytes,
    CAST(COALESCE(MIN(disk_read_bytes), 0) AS SIGNED) AS disk_read_bytes,
    COUNT(disk_read_bytes) > 0 AS has_disk_read_bytes,
    CAST(COALESCE(MIN(disk_write_bytes), 0) AS SIGNED) AS disk_write_bytes,
    COUNT(disk_write_bytes) > 0 AS has_disk_write_bytes,
    CAST(COALESCE(MIN(network_rx_bytes), 0) AS SIGNED) AS network_rx_bytes,
    COUNT(network_rx_bytes) > 0 AS has_network_rx_bytes,
    CAST(COALESCE(MIN(network_tx_bytes), 0) AS SIGNED) AS network_tx_bytes,
    COUNT(network_tx_bytes) > 0 AS has_network_tx_bytes,
    COALESCE(SUBSTRING_INDEX(GROUP_CONCAT(last_error ORDER BY sampled_at DESC SEPARATOR '\x1e'), '\x1e', 1), '') AS last_error,
    COUNT(last_error) > 0 AS has_last_error
FROM instance_resource_samples
WHERE app_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
GROUP BY 1
ORDER BY 1 ASC
`

type ListInstanceResourceBucketsParams struct {
	BucketSeconds   int64     `db:"bucket_seconds" json:"bucket_seconds"`
	BucketSeconds_2 int64     `db:"bucket_seconds_2" json:"bucket_seconds_2"`
	AppID           string    `db:"app_id" json:"app_id"`
	FromSampledAt   time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt     time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListInstanceResourceBucketsRow struct {
	SampledAt           time.Time   `db:"sampled_at" json:"sampled_at"`
	ContainerStatus     interface{} `db:"container_status" json:"container_status"`
	HasContainerStatus  bool        `db:"has_container_status" json:"has_container_status"`
	CpuPercent          float64     `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool        `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64       `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool        `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryLimitBytes    int64       `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	HasMemoryLimitBytes bool        `db:"has_memory_limit_bytes" json:"has_memory_limit_bytes"`
	DiskReadBytes       int64       `db:"disk_read_bytes" json:"disk_read_bytes"`
	HasDiskReadBytes    bool        `db:"has_disk_read_bytes" json:"has_disk_read_bytes"`
	DiskWriteBytes      int64       `db:"disk_write_bytes" json:"disk_write_bytes"`
	HasDiskWriteBytes   bool        `db:"has_disk_write_bytes" json:"has_disk_write_bytes"`
	NetworkRxBytes      int64       `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool        `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64       `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool        `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	LastError           interface{} `db:"last_error" json:"last_error"`
	HasLastError        bool        `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListInstanceResourceBuckets(ctx context.Context, arg ListInstanceResourceBucketsParams) ([]ListInstanceResourceBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceResourceBuckets,
		arg.BucketSeconds,
		arg.BucketSeconds_2,
		arg.AppID,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceResourceBucketsRow{}
	for rows.Next() {
		var i ListInstanceResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.ContainerStatus,
			&i.HasContainerStatus,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.HasMemoryLimitBytes,
			&i.DiskReadBytes,
			&i.HasDiskReadBytes,
			&i.DiskWriteBytes,
			&i.HasDiskWriteBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceResourceSamples = `-- name: ListInstanceResourceSamples :many
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE app_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
ORDER BY sampled_at ASC, id ASC
`

type ListInstanceResourceSamplesParams struct {
	AppID         string    `db:"app_id" json:"app_id"`
	FromSampledAt time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListInstanceResourceSamples(ctx context.Context, arg ListInstanceResourceSamplesParams) ([]InstanceResourceSample, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceResourceSamples, arg.AppID, arg.FromSampledAt, arg.ToSampledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestInstanceResourceSamplesByNode = `-- name: ListLatestInstanceResourceSamplesByNode :many
SELECT s.id, s.app_id, s.runtime_node_id, s.container_id, s.sampled_at, s.container_status,
       s.cpu_percent, s.memory_used_bytes, s.memory_limit_bytes, s.disk_read_bytes,
       s.disk_write_bytes, s.network_rx_bytes, s.network_tx_bytes, s.last_error, s.created_at
FROM (
    SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at, ROW_NUMBER() OVER (PARTITION BY app_id ORDER BY sampled_at DESC, id DESC) AS rn
    FROM instance_resource_samples
    WHERE runtime_node_id = ?
) AS s
WHERE s.rn = 1
`

func (q *Queries) ListLatestInstanceResourceSamplesByNode(ctx context.Context, runtimeNodeID string) ([]InstanceResourceSample, error) {
	rows, err := q.db.QueryContext(ctx, listLatestInstanceResourceSamplesByNode, runtimeNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestNodeResourceSamples = `-- name: ListLatestNodeResourceSamples :many
SELECT s.id, s.runtime_node_id, s.sampled_at, s.cpu_percent, s.memory_used_bytes,
       s.memory_total_bytes, s.disk_used_bytes, s.disk_total_bytes,
       s.network_rx_bytes, s.network_tx_bytes, s.instance_count, s.last_error, s.created_at
FROM (
    SELECT id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at, ROW_NUMBER() OVER (PARTITION BY runtime_node_id ORDER BY sampled_at DESC, id DESC) AS rn
    FROM node_resource_samples
    WHERE runtime_node_id IN (/*SLICE:runtime_node_ids*/?)
) AS s
WHERE s.rn = 1
`

func (q *Queries) ListLatestNodeResourceSamples(ctx context.Context, runtimeNodeIds []string) ([]NodeResourceSample, error) {
	query := listLatestNodeResourceSamples
	var queryParams []interface{}
	if len(runtimeNodeIds) > 0 {
		for _, v := range runtimeNodeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:runtime_node_ids*/?", strings.Repeat(",?", len(runtimeNodeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:runtime_node_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeResourceSample{}
	for rows.Next() {
		var i NodeResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeNodeID,
			&i.SampledAt,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.DiskTotalBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.InstanceCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceResourceBuckets = `-- name: ListNodeInstanceResourceBuckets :many
SELECT
    CAST(FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(sampled_at) / CAST(? AS SIGNED)) * CAST(? AS SIGNED)) AS DATETIME) AS sampled_at,
    COALESCE(SUBSTRING_INDEX(GROUP_CONCAT(container_status ORDER BY sampled_at DESC SEPARATOR '\x1e'), '\x1e', 1), '') AS container_status,
    COUNT(container_status) > 0 AS has_container_status,
    CAST(COALESCE(AVG(cpu_percent), 0) AS DOUBLE) AS cpu_percent,
    COUNT(cpu_percent) > 0 AS has_cpu_percent,
    CAST(COALESCE(AVG(memory_used_bytes), 0) AS SIGNED) AS memory_used_bytes,
    COUNT(memory_used_bytes) > 0 AS has_memory_used_bytes,
    CAST(COALESCE(MAX(memory_limit_bytes), 0) AS SIGNED) AS memory_limit_bytes,
    COUNT(memory_limit_bytes) > 0 AS has_memory_limit_bytes,
    CAST(COALESCE(MIN(disk_read_bytes), 0) AS SIGNED) AS disk_read_bytes,
    COUNT(disk_read_bytes) > 0 AS has_disk_read_bytes,
    CAST(COALESCE(MIN(disk_write_bytes), 0) AS SIGNED) AS disk_write_bytes,
    COUNT(disk_write_bytes) > 0 AS has_disk_write_bytes,
    CAST(COALESCE(MIN(network_rx_bytes), 0) AS SIGNED) AS network_rx_bytes,
    COUNT(network_rx_bytes) > 0 AS has_network_rx_bytes,
    CAST(COALESCE(MIN(network_tx_bytes), 0) AS SIGNED) AS network_tx_bytes,
    COUNT(network_tx_bytes) > 0 AS has_network_tx_bytes,
    COALESCE(SUBSTRING_INDEX(GROUP_CONCAT(last_error ORDER BY sampled_at DESC SEPARATOR '\x1e'), '\x1e', 1), '') AS last_error,
    COUNT(last_error) > 0 AS has_last_error
FROM instance_resource_samples
WHERE runtime_node_id = ?
  AND app_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
GROUP BY 1
ORDER BY 1 ASC
`

type ListNodeInstanceResourceBucketsParams struct {
	BucketSeconds   int64     `db:"bucket_seconds" json:"bucket_seconds"`
	BucketSeconds_2 int64     `db:"bucket_seconds_2" json:"bucket_seconds_2"`
	RuntimeNodeID   string    `db:"runtime_node_id" json:"runtime_node_id"`
	AppID           string    `db:"app_id" json:"app_id"`
	FromSampledAt   time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt     time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListNodeInstanceResourceBucketsRow struct {
	SampledAt           time.Time   `db:"sampled_at" json:"sampled_at"`
	ContainerStatus     interface{} `db:"container_status" json:"container_status"`
	HasContainerStatus  bool        `db:"has_container_status" json:"has_container_status"`
	CpuPercent          float64     `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool        `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64       `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool        `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryLimitBytes    int64       `db:"memory_limit_bytes" json:"memory_limit_bytes"`
	HasMemoryLimitBytes bool        `db:"has_memory_limit_bytes" json:"has_memory_limit_bytes"`
	DiskReadBytes       int64       `db:"disk_read_bytes" json:"disk_read_bytes"`
	HasDiskReadBytes    bool        `db:"has_disk_read_bytes" json:"has_disk_read_bytes"`
	DiskWriteBytes      int64       `db:"disk_write_bytes" json:"disk_write_bytes"`
	HasDiskWriteBytes   bool        `db:"has_disk_write_bytes" json:"has_disk_write_bytes"`
	NetworkRxBytes      int64       `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool        `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64       `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool        `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	LastError           interface{} `db:"last_error" json:"last_error"`
	HasLastError        bool        `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListNodeInstanceResourceBuckets(ctx context.Context, arg ListNodeInstanceResourceBucketsParams) ([]ListNodeInstanceResourceBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInstanceResourceBuckets,
		arg.BucketSeconds,
		arg.BucketSeconds_2,
		arg.RuntimeNodeID,
		arg.AppID,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeInstanceResourceBucketsRow{}
	for rows.Next() {
		var i ListNodeInstanceResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.ContainerStatus,
			&i.HasContainerStatus,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.HasMemoryLimitBytes,
			&i.DiskReadBytes,
			&i.HasDiskReadBytes,
			&i.DiskWriteBytes,
			&i.HasDiskWriteBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeInstanceResourceSamples = `-- name: ListNodeInstanceResourceSamples :many
SELECT id, app_id, runtime_node_id, container_id, sampled_at, container_status, cpu_percent, memory_used_bytes, memory_limit_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, last_error, created_at
FROM instance_resource_samples
WHERE runtime_node_id = ?
  AND app_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
ORDER BY sampled_at ASC, id ASC
`

type ListNodeInstanceResourceSamplesParams struct {
	RuntimeNodeID string    `db:"runtime_node_id" json:"runtime_node_id"`
	AppID         string    `db:"app_id" json:"app_id"`
	FromSampledAt time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListNodeInstanceResourceSamples(ctx context.Context, arg ListNodeInstanceResourceSamplesParams) ([]InstanceResourceSample, error) {
	rows, err := q.db.QueryContext(ctx, listNodeInstanceResourceSamples,
		arg.RuntimeNodeID,
		arg.AppID,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceResourceSample{}
	for rows.Next() {
		var i InstanceResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.RuntimeNodeID,
			&i.ContainerID,
			&i.SampledAt,
			&i.ContainerStatus,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryLimitBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeResourceBuckets = `-- name: ListNodeResourceBuckets :many
SELECT
    CAST(FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(sampled_at) / CAST(? AS SIGNED)) * CAST(? AS SIGNED)) AS DATETIME) AS sampled_at,
    CAST(COALESCE(AVG(cpu_percent), 0) AS DOUBLE) AS cpu_percent,
    COUNT(cpu_percent) > 0 AS has_cpu_percent,
    CAST(COALESCE(AVG(memory_used_bytes), 0) AS SIGNED) AS memory_used_bytes,
    COUNT(memory_used_bytes) > 0 AS has_memory_used_bytes,
    CAST(COALESCE(MAX(memory_total_bytes), 0) AS SIGNED) AS memory_total_bytes,
    COUNT(memory_total_bytes) > 0 AS has_memory_total_bytes,
    CAST(COALESCE(AVG(disk_used_bytes), 0) AS SIGNED) AS disk_used_bytes,
    COUNT(disk_used_bytes) > 0 AS has_disk_used_bytes,
    CAST(COALESCE(MAX(disk_total_bytes), 0) AS SIGNED) AS disk_total_bytes,
    COUNT(disk_total_bytes) > 0 AS has_disk_total_bytes,
    CAST(COALESCE(MIN(network_rx_bytes), 0) AS SIGNED) AS network_rx_bytes,
    COUNT(network_rx_bytes) > 0 AS has_network_rx_bytes,
    CAST(COALESCE(MIN(network_tx_bytes), 0) AS SIGNED) AS network_tx_bytes,
    COUNT(network_tx_bytes) > 0 AS has_network_tx_bytes,
    CAST(COALESCE(AVG(instance_count), 0) AS SIGNED) AS instance_count,
    COUNT(instance_count) > 0 AS has_instance_count,
    COALESCE(SUBSTRING_INDEX(GROUP_CONCAT(last_error ORDER BY sampled_at DESC SEPARATOR '\x1e'), '\x1e', 1), '') AS last_error,
    COUNT(last_error) > 0 AS has_last_error
FROM node_resource_samples
WHERE runtime_node_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
GROUP BY 1
ORDER BY 1 ASC
`

type ListNodeResourceBucketsParams struct {
	BucketSeconds   int64     `db:"bucket_seconds" json:"bucket_seconds"`
	BucketSeconds_2 int64     `db:"bucket_seconds_2" json:"bucket_seconds_2"`
	RuntimeNodeID   string    `db:"runtime_node_id" json:"runtime_node_id"`
	FromSampledAt   time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt     time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

type ListNodeResourceBucketsRow struct {
	SampledAt           time.Time   `db:"sampled_at" json:"sampled_at"`
	CpuPercent          float64     `db:"cpu_percent" json:"cpu_percent"`
	HasCpuPercent       bool        `db:"has_cpu_percent" json:"has_cpu_percent"`
	MemoryUsedBytes     int64       `db:"memory_used_bytes" json:"memory_used_bytes"`
	HasMemoryUsedBytes  bool        `db:"has_memory_used_bytes" json:"has_memory_used_bytes"`
	MemoryTotalBytes    int64       `db:"memory_total_bytes" json:"memory_total_bytes"`
	HasMemoryTotalBytes bool        `db:"has_memory_total_bytes" json:"has_memory_total_bytes"`
	DiskUsedBytes       int64       `db:"disk_used_bytes" json:"disk_used_bytes"`
	HasDiskUsedBytes    bool        `db:"has_disk_used_bytes" json:"has_disk_used_bytes"`
	DiskTotalBytes      int64       `db:"disk_total_bytes" json:"disk_total_bytes"`
	HasDiskTotalBytes   bool        `db:"has_disk_total_bytes" json:"has_disk_total_bytes"`
	NetworkRxBytes      int64       `db:"network_rx_bytes" json:"network_rx_bytes"`
	HasNetworkRxBytes   bool        `db:"has_network_rx_bytes" json:"has_network_rx_bytes"`
	NetworkTxBytes      int64       `db:"network_tx_bytes" json:"network_tx_bytes"`
	HasNetworkTxBytes   bool        `db:"has_network_tx_bytes" json:"has_network_tx_bytes"`
	InstanceCount       int64       `db:"instance_count" json:"instance_count"`
	HasInstanceCount    bool        `db:"has_instance_count" json:"has_instance_count"`
	LastError           interface{} `db:"last_error" json:"last_error"`
	HasLastError        bool        `db:"has_last_error" json:"has_last_error"`
}

func (q *Queries) ListNodeResourceBuckets(ctx context.Context, arg ListNodeResourceBucketsParams) ([]ListNodeResourceBucketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodeResourceBuckets,
		arg.BucketSeconds,
		arg.BucketSeconds_2,
		arg.RuntimeNodeID,
		arg.FromSampledAt,
		arg.ToSampledAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeResourceBucketsRow{}
	for rows.Next() {
		var i ListNodeResourceBucketsRow
		if err := rows.Scan(
			&i.SampledAt,
			&i.CpuPercent,
			&i.HasCpuPercent,
			&i.MemoryUsedBytes,
			&i.HasMemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.HasMemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.HasDiskUsedBytes,
			&i.DiskTotalBytes,
			&i.HasDiskTotalBytes,
			&i.NetworkRxBytes,
			&i.HasNetworkRxBytes,
			&i.NetworkTxBytes,
			&i.HasNetworkTxBytes,
			&i.InstanceCount,
			&i.HasInstanceCount,
			&i.LastError,
			&i.HasLastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeResourceSamples = `-- name: ListNodeResourceSamples :many
SELECT id, runtime_node_id, sampled_at, cpu_percent, memory_used_bytes, memory_total_bytes, disk_used_bytes, disk_total_bytes, network_rx_bytes, network_tx_bytes, instance_count, last_error, created_at
FROM node_resource_samples
WHERE runtime_node_id = ?
  AND sampled_at >= ?
  AND sampled_at <= ?
ORDER BY sampled_at ASC, id ASC
`

type ListNodeResourceSamplesParams struct {
	RuntimeNodeID string    `db:"runtime_node_id" json:"runtime_node_id"`
	FromSampledAt time.Time `db:"from_sampled_at" json:"from_sampled_at"`
	ToSampledAt   time.Time `db:"to_sampled_at" json:"to_sampled_at"`
}

func (q *Queries) ListNodeResourceSamples(ctx context.Context, arg ListNodeResourceSamplesParams) ([]NodeResourceSample, error) {
	rows, err := q.db.QueryContext(ctx, listNodeResourceSamples, arg.RuntimeNodeID, arg.FromSampledAt, arg.ToSampledAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeResourceSample{}
	for rows.Next() {
		var i NodeResourceSample
		if err := rows.Scan(
			&i.ID,
			&i.RuntimeNodeID,
			&i.SampledAt,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryTotalBytes,
			&i.DiskUsedBytes,
			&i.DiskTotalBytes,
			&i.NetworkRxBytes,
			&i.NetworkTxBytes,
			&i.InstanceCount,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
