// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_nodes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enrollRuntimeNodeInsert = `-- name: EnrollRuntimeNodeInsert :one
INSERT INTO runtime_nodes (
    agent_id,
    name,
    status,
    max_apps,
    agent_docker_endpoint,
    agent_file_endpoint,
    agent_tls_ca_cert,
    agent_token_hash,
    heartbeat_interval_seconds,
    agent_version,
    node_data_root,
    registered_at,
    last_heartbeat_at,
    resource_snapshot_json,
    metadata_json,
    agent_token_ciphertext
) VALUES (
    $1, $2, 'active', $3, $4, $5, $6, $7, $8, $9, $10, now(), now(), $11, $12, $13
)
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type EnrollRuntimeNodeInsertParams struct {
	AgentID                  pgtype.Text `db:"agent_id" json:"agent_id"`
	Name                     string      `db:"name" json:"name"`
	MaxApps                  pgtype.Int4 `db:"max_apps" json:"max_apps"`
	AgentDockerEndpoint      pgtype.Text `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint        pgtype.Text `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert           pgtype.Text `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash           pgtype.Text `db:"agent_token_hash" json:"agent_token_hash"`
	HeartbeatIntervalSeconds int32       `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	AgentVersion             pgtype.Text `db:"agent_version" json:"agent_version"`
	NodeDataRoot             pgtype.Text `db:"node_data_root" json:"node_data_root"`
	ResourceSnapshotJson     []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson             []byte      `db:"metadata_json" json:"metadata_json"`
	AgentTokenCiphertext     pgtype.Text `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
}

func (q *Queries) EnrollRuntimeNodeInsert(ctx context.Context, arg EnrollRuntimeNodeInsertParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, enrollRuntimeNodeInsert,
		arg.AgentID,
		arg.Name,
		arg.MaxApps,
		arg.AgentDockerEndpoint,
		arg.AgentFileEndpoint,
		arg.AgentTlsCaCert,
		arg.AgentTokenHash,
		arg.HeartbeatIntervalSeconds,
		arg.AgentVersion,
		arg.NodeDataRoot,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
		arg.AgentTokenCiphertext,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const enrollRuntimeNodeUpdate = `-- name: EnrollRuntimeNodeUpdate :one
UPDATE runtime_nodes
SET
    name = $2,
    status = 'active',
    max_apps = $3,
    agent_docker_endpoint = $4,
    agent_file_endpoint = $5,
    agent_tls_ca_cert = $6,
    agent_token_hash = $7,
    agent_version = $8,
    node_data_root = $9,
    last_heartbeat_at = now(),
    resource_snapshot_json = $10,
    metadata_json = $11,
    agent_token_ciphertext = $12,
    probe_failure_streak = 0,
    probe_success_streak = 0,
    updated_at = now()
WHERE agent_id = $1
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type EnrollRuntimeNodeUpdateParams struct {
	AgentID              pgtype.Text `db:"agent_id" json:"agent_id"`
	Name                 string      `db:"name" json:"name"`
	MaxApps              pgtype.Int4 `db:"max_apps" json:"max_apps"`
	AgentDockerEndpoint  pgtype.Text `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint    pgtype.Text `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert       pgtype.Text `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash       pgtype.Text `db:"agent_token_hash" json:"agent_token_hash"`
	AgentVersion         pgtype.Text `db:"agent_version" json:"agent_version"`
	NodeDataRoot         pgtype.Text `db:"node_data_root" json:"node_data_root"`
	ResourceSnapshotJson []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson         []byte      `db:"metadata_json" json:"metadata_json"`
	AgentTokenCiphertext pgtype.Text `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
}

func (q *Queries) EnrollRuntimeNodeUpdate(ctx context.Context, arg EnrollRuntimeNodeUpdateParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, enrollRuntimeNodeUpdate,
		arg.AgentID,
		arg.Name,
		arg.MaxApps,
		arg.AgentDockerEndpoint,
		arg.AgentFileEndpoint,
		arg.AgentTlsCaCert,
		arg.AgentTokenHash,
		arg.AgentVersion,
		arg.NodeDataRoot,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
		arg.AgentTokenCiphertext,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const getRuntimeNode = `-- name: GetRuntimeNode :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
FROM runtime_nodes
WHERE id = $1
`

func (q *Queries) GetRuntimeNode(ctx context.Context, id pgtype.UUID) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, getRuntimeNode, id)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const getRuntimeNodeByAgentID = `-- name: GetRuntimeNodeByAgentID :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
FROM runtime_nodes
WHERE agent_id = $1
`

func (q *Queries) GetRuntimeNodeByAgentID(ctx context.Context, agentID pgtype.Text) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, getRuntimeNodeByAgentID, agentID)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const getRuntimeNodeByName = `-- name: GetRuntimeNodeByName :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
FROM runtime_nodes
WHERE name = $1
`

func (q *Queries) GetRuntimeNodeByName(ctx context.Context, name string) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, getRuntimeNodeByName, name)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const listActiveNodesWithAppCounts = `-- name: ListActiveNodesWithAppCounts :many
SELECT n.id, n.name, n.status, n.agent_docker_endpoint, n.agent_file_endpoint, n.agent_tls_ca_cert, n.agent_token_hash, n.agent_version, n.heartbeat_interval_seconds, n.last_heartbeat_at, n.resource_snapshot_json, n.metadata_json, n.node_data_root, n.registered_at, n.created_at, n.updated_at, n.agent_token_ciphertext, n.max_apps, n.agent_id, n.last_probe_attempted_at, n.last_probe_ok_at, n.last_probe_failed_at, n.last_probe_error, n.probe_failure_streak, n.probe_success_streak,
       COALESCE(c.app_count, 0)::bigint AS app_count
FROM runtime_nodes n
LEFT JOIN (
    SELECT runtime_node_id, COUNT(*) AS app_count
    FROM apps
    WHERE deleted_at IS NULL
    GROUP BY runtime_node_id
) c ON c.runtime_node_id = n.id
WHERE n.status = 'active'
ORDER BY n.name ASC
`

type ListActiveNodesWithAppCountsRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Name                     string             `db:"name" json:"name"`
	Status                   string             `db:"status" json:"status"`
	AgentDockerEndpoint      pgtype.Text        `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint        pgtype.Text        `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert           pgtype.Text        `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash           pgtype.Text        `db:"agent_token_hash" json:"agent_token_hash"`
	AgentVersion             pgtype.Text        `db:"agent_version" json:"agent_version"`
	HeartbeatIntervalSeconds int32              `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	LastHeartbeatAt          pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	ResourceSnapshotJson     []byte             `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson             []byte             `db:"metadata_json" json:"metadata_json"`
	NodeDataRoot             pgtype.Text        `db:"node_data_root" json:"node_data_root"`
	RegisteredAt             pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AgentTokenCiphertext     pgtype.Text        `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
	MaxApps                  pgtype.Int4        `db:"max_apps" json:"max_apps"`
	AgentID                  pgtype.Text        `db:"agent_id" json:"agent_id"`
	LastProbeAttemptedAt     pgtype.Timestamptz `db:"last_probe_attempted_at" json:"last_probe_attempted_at"`
	LastProbeOkAt            pgtype.Timestamptz `db:"last_probe_ok_at" json:"last_probe_ok_at"`
	LastProbeFailedAt        pgtype.Timestamptz `db:"last_probe_failed_at" json:"last_probe_failed_at"`
	LastProbeError           pgtype.Text        `db:"last_probe_error" json:"last_probe_error"`
	ProbeFailureStreak       int32              `db:"probe_failure_streak" json:"probe_failure_streak"`
	ProbeSuccessStreak       int32              `db:"probe_success_streak" json:"probe_success_streak"`
	AppCount                 int64              `db:"app_count" json:"app_count"`
}

// ListActiveNodesWithAppCounts 列出所有 active 节点并附带其当前未删除应用数量。
// OnboardingService 自动选节点时按剩余容量过滤；剩余容量 = max_apps - app_count，
// max_apps NULL 表示不限。degraded / unreachable / disabled 均不参与新应用调度。
func (q *Queries) ListActiveNodesWithAppCounts(ctx context.Context) ([]ListActiveNodesWithAppCountsRow, error) {
	rows, err := q.db.Query(ctx, listActiveNodesWithAppCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveNodesWithAppCountsRow{}
	for rows.Next() {
		var i ListActiveNodesWithAppCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AgentDockerEndpoint,
			&i.AgentFileEndpoint,
			&i.AgentTlsCaCert,
			&i.AgentTokenHash,
			&i.AgentVersion,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.ResourceSnapshotJson,
			&i.MetadataJson,
			&i.NodeDataRoot,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentTokenCiphertext,
			&i.MaxApps,
			&i.AgentID,
			&i.LastProbeAttemptedAt,
			&i.LastProbeOkAt,
			&i.LastProbeFailedAt,
			&i.LastProbeError,
			&i.ProbeFailureStreak,
			&i.ProbeSuccessStreak,
			&i.AppCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeNodes = `-- name: ListRuntimeNodes :many
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
FROM runtime_nodes
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListRuntimeNodesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRuntimeNodes(ctx context.Context, arg ListRuntimeNodesParams) ([]RuntimeNode, error) {
	rows, err := q.db.Query(ctx, listRuntimeNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeNode{}
	for rows.Next() {
		var i RuntimeNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AgentDockerEndpoint,
			&i.AgentFileEndpoint,
			&i.AgentTlsCaCert,
			&i.AgentTokenHash,
			&i.AgentVersion,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.ResourceSnapshotJson,
			&i.MetadataJson,
			&i.NodeDataRoot,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentTokenCiphertext,
			&i.MaxApps,
			&i.AgentID,
			&i.LastProbeAttemptedAt,
			&i.LastProbeOkAt,
			&i.LastProbeFailedAt,
			&i.LastProbeError,
			&i.ProbeFailureStreak,
			&i.ProbeSuccessStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRuntimeNodeStatus = `-- name: SetRuntimeNodeStatus :one
UPDATE runtime_nodes
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type SetRuntimeNodeStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

func (q *Queries) SetRuntimeNodeStatus(ctx context.Context, arg SetRuntimeNodeStatusParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, setRuntimeNodeStatus, arg.ID, arg.Status)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const updateRuntimeNodeHeartbeat = `-- name: UpdateRuntimeNodeHeartbeat :one
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'unreachable' THEN 'active'
        ELSE status
    END,
    agent_version = $2,
    last_heartbeat_at = now(),
    resource_snapshot_json = $3,
    metadata_json = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type UpdateRuntimeNodeHeartbeatParams struct {
	ID                   pgtype.UUID `db:"id" json:"id"`
	AgentVersion         pgtype.Text `db:"agent_version" json:"agent_version"`
	ResourceSnapshotJson []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson         []byte      `db:"metadata_json" json:"metadata_json"`
}

func (q *Queries) UpdateRuntimeNodeHeartbeat(ctx context.Context, arg UpdateRuntimeNodeHeartbeatParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, updateRuntimeNodeHeartbeat,
		arg.ID,
		arg.AgentVersion,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
	)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const updateRuntimeNodeProbeFailure = `-- name: UpdateRuntimeNodeProbeFailure :one
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'active' AND probe_failure_streak + 1 >= $2 THEN 'degraded'
        ELSE status
    END,
    last_probe_attempted_at = now(),
    last_probe_failed_at = now(),
    last_probe_error = $3,
    probe_failure_streak = probe_failure_streak + 1,
    probe_success_streak = 0,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type UpdateRuntimeNodeProbeFailureParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	ProbeFailureStreak int32       `db:"probe_failure_streak" json:"probe_failure_streak"`
	LastProbeError     pgtype.Text `db:"last_probe_error" json:"last_probe_error"`
}

func (q *Queries) UpdateRuntimeNodeProbeFailure(ctx context.Context, arg UpdateRuntimeNodeProbeFailureParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, updateRuntimeNodeProbeFailure, arg.ID, arg.ProbeFailureStreak, arg.LastProbeError)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}

const updateRuntimeNodeProbeSuccess = `-- name: UpdateRuntimeNodeProbeSuccess :one
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'degraded' AND probe_success_streak + 1 >= $2 THEN 'active'
        ELSE status
    END,
    last_probe_attempted_at = now(),
    last_probe_ok_at = now(),
    last_probe_error = NULL,
    probe_success_streak = probe_success_streak + 1,
    probe_failure_streak = 0,
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, created_at, updated_at, agent_token_ciphertext, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak
`

type UpdateRuntimeNodeProbeSuccessParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	ProbeSuccessStreak int32       `db:"probe_success_streak" json:"probe_success_streak"`
}

func (q *Queries) UpdateRuntimeNodeProbeSuccess(ctx context.Context, arg UpdateRuntimeNodeProbeSuccessParams) (RuntimeNode, error) {
	row := q.db.QueryRow(ctx, updateRuntimeNodeProbeSuccess, arg.ID, arg.ProbeSuccessStreak)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentTokenCiphertext,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
	)
	return i, err
}
