// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runtime_nodes.sql

package sqlc

import (
	"context"
	"time"

	null "github.com/guregu/null/v5"
)

const enrollRuntimeNodeInsert = `-- name: EnrollRuntimeNodeInsert :exec
INSERT INTO runtime_nodes (
    id,
    agent_id,
    name,
    status,
    max_apps,
    agent_docker_endpoint,
    agent_file_endpoint,
    agent_tls_ca_cert,
    agent_token_hash,
    heartbeat_interval_seconds,
    agent_version,
    node_data_root,
    registered_at,
    last_heartbeat_at,
    resource_snapshot_json,
    metadata_json,
    agent_token_ciphertext
) VALUES (
    ?, ?, ?, 'active', ?, ?, ?, ?, ?, ?, ?, ?, now(), now(), ?, ?, ?
)
`

type EnrollRuntimeNodeInsertParams struct {
	ID                       string      `db:"id" json:"id"`
	AgentID                  null.String `db:"agent_id" json:"agent_id"`
	Name                     string      `db:"name" json:"name"`
	MaxApps                  null.Int    `db:"max_apps" json:"max_apps"`
	AgentDockerEndpoint      null.String `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint        null.String `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert           null.String `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash           null.String `db:"agent_token_hash" json:"agent_token_hash"`
	HeartbeatIntervalSeconds int32       `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	AgentVersion             null.String `db:"agent_version" json:"agent_version"`
	NodeDataRoot             null.String `db:"node_data_root" json:"node_data_root"`
	ResourceSnapshotJson     []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson             []byte      `db:"metadata_json" json:"metadata_json"`
	AgentTokenCiphertext     null.String `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
}

func (q *Queries) EnrollRuntimeNodeInsert(ctx context.Context, arg EnrollRuntimeNodeInsertParams) error {
	_, err := q.db.ExecContext(ctx, enrollRuntimeNodeInsert,
		arg.ID,
		arg.AgentID,
		arg.Name,
		arg.MaxApps,
		arg.AgentDockerEndpoint,
		arg.AgentFileEndpoint,
		arg.AgentTlsCaCert,
		arg.AgentTokenHash,
		arg.HeartbeatIntervalSeconds,
		arg.AgentVersion,
		arg.NodeDataRoot,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
		arg.AgentTokenCiphertext,
	)
	return err
}

const enrollRuntimeNodeUpdate = `-- name: EnrollRuntimeNodeUpdate :exec
UPDATE runtime_nodes
SET
    name = ?,
    status = 'active',
    max_apps = ?,
    agent_docker_endpoint = ?,
    agent_file_endpoint = ?,
    agent_tls_ca_cert = ?,
    agent_token_hash = ?,
    agent_version = ?,
    node_data_root = ?,
    last_heartbeat_at = now(),
    resource_snapshot_json = ?,
    metadata_json = ?,
    agent_token_ciphertext = ?,
    probe_failure_streak = 0,
    probe_success_streak = 0,
    updated_at = now()
WHERE agent_id = ?
`

type EnrollRuntimeNodeUpdateParams struct {
	Name                 string      `db:"name" json:"name"`
	MaxApps              null.Int    `db:"max_apps" json:"max_apps"`
	AgentDockerEndpoint  null.String `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint    null.String `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert       null.String `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash       null.String `db:"agent_token_hash" json:"agent_token_hash"`
	AgentVersion         null.String `db:"agent_version" json:"agent_version"`
	NodeDataRoot         null.String `db:"node_data_root" json:"node_data_root"`
	ResourceSnapshotJson []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson         []byte      `db:"metadata_json" json:"metadata_json"`
	AgentTokenCiphertext null.String `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
	AgentID              null.String `db:"agent_id" json:"agent_id"`
}

func (q *Queries) EnrollRuntimeNodeUpdate(ctx context.Context, arg EnrollRuntimeNodeUpdateParams) error {
	_, err := q.db.ExecContext(ctx, enrollRuntimeNodeUpdate,
		arg.Name,
		arg.MaxApps,
		arg.AgentDockerEndpoint,
		arg.AgentFileEndpoint,
		arg.AgentTlsCaCert,
		arg.AgentTokenHash,
		arg.AgentVersion,
		arg.NodeDataRoot,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
		arg.AgentTokenCiphertext,
		arg.AgentID,
	)
	return err
}

const getRuntimeNode = `-- name: GetRuntimeNode :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_token_ciphertext, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak, created_at, updated_at
FROM runtime_nodes
WHERE id = ?
`

func (q *Queries) GetRuntimeNode(ctx context.Context, id string) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeNode, id)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentTokenCiphertext,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeNodeByAgentID = `-- name: GetRuntimeNodeByAgentID :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_token_ciphertext, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak, created_at, updated_at
FROM runtime_nodes
WHERE agent_id = ?
`

func (q *Queries) GetRuntimeNodeByAgentID(ctx context.Context, agentID null.String) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeNodeByAgentID, agentID)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentTokenCiphertext,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeNodeByName = `-- name: GetRuntimeNodeByName :one
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_token_ciphertext, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak, created_at, updated_at
FROM runtime_nodes
WHERE name = ?
`

func (q *Queries) GetRuntimeNodeByName(ctx context.Context, name string) (RuntimeNode, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeNodeByName, name)
	var i RuntimeNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.AgentDockerEndpoint,
		&i.AgentFileEndpoint,
		&i.AgentTlsCaCert,
		&i.AgentTokenHash,
		&i.AgentTokenCiphertext,
		&i.AgentVersion,
		&i.HeartbeatIntervalSeconds,
		&i.LastHeartbeatAt,
		&i.ResourceSnapshotJson,
		&i.MetadataJson,
		&i.NodeDataRoot,
		&i.RegisteredAt,
		&i.MaxApps,
		&i.AgentID,
		&i.LastProbeAttemptedAt,
		&i.LastProbeOkAt,
		&i.LastProbeFailedAt,
		&i.LastProbeError,
		&i.ProbeFailureStreak,
		&i.ProbeSuccessStreak,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNodesWithAppCounts = `-- name: ListActiveNodesWithAppCounts :many
SELECT n.id, n.name, n.status, n.agent_docker_endpoint, n.agent_file_endpoint, n.agent_tls_ca_cert, n.agent_token_hash, n.agent_token_ciphertext, n.agent_version, n.heartbeat_interval_seconds, n.last_heartbeat_at, n.resource_snapshot_json, n.metadata_json, n.node_data_root, n.registered_at, n.max_apps, n.agent_id, n.last_probe_attempted_at, n.last_probe_ok_at, n.last_probe_failed_at, n.last_probe_error, n.probe_failure_streak, n.probe_success_streak, n.created_at, n.updated_at,
       COALESCE(c.app_count, 0) AS app_count
FROM runtime_nodes n
LEFT JOIN (
    SELECT runtime_node_id, COUNT(*) AS app_count
    FROM apps
    WHERE deleted_at IS NULL
    GROUP BY runtime_node_id
) c ON c.runtime_node_id = n.id
WHERE n.status = 'active'
ORDER BY n.name ASC
`

type ListActiveNodesWithAppCountsRow struct {
	ID                       string      `db:"id" json:"id"`
	Name                     string      `db:"name" json:"name"`
	Status                   string      `db:"status" json:"status"`
	AgentDockerEndpoint      null.String `db:"agent_docker_endpoint" json:"agent_docker_endpoint"`
	AgentFileEndpoint        null.String `db:"agent_file_endpoint" json:"agent_file_endpoint"`
	AgentTlsCaCert           null.String `db:"agent_tls_ca_cert" json:"agent_tls_ca_cert"`
	AgentTokenHash           null.String `db:"agent_token_hash" json:"agent_token_hash"`
	AgentTokenCiphertext     null.String `db:"agent_token_ciphertext" json:"agent_token_ciphertext"`
	AgentVersion             null.String `db:"agent_version" json:"agent_version"`
	HeartbeatIntervalSeconds int32       `db:"heartbeat_interval_seconds" json:"heartbeat_interval_seconds"`
	LastHeartbeatAt          null.Time   `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	ResourceSnapshotJson     []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson             []byte      `db:"metadata_json" json:"metadata_json"`
	NodeDataRoot             null.String `db:"node_data_root" json:"node_data_root"`
	RegisteredAt             null.Time   `db:"registered_at" json:"registered_at"`
	MaxApps                  null.Int    `db:"max_apps" json:"max_apps"`
	AgentID                  null.String `db:"agent_id" json:"agent_id"`
	LastProbeAttemptedAt     null.Time   `db:"last_probe_attempted_at" json:"last_probe_attempted_at"`
	LastProbeOkAt            null.Time   `db:"last_probe_ok_at" json:"last_probe_ok_at"`
	LastProbeFailedAt        null.Time   `db:"last_probe_failed_at" json:"last_probe_failed_at"`
	LastProbeError           null.String `db:"last_probe_error" json:"last_probe_error"`
	ProbeFailureStreak       int32       `db:"probe_failure_streak" json:"probe_failure_streak"`
	ProbeSuccessStreak       int32       `db:"probe_success_streak" json:"probe_success_streak"`
	CreatedAt                time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time   `db:"updated_at" json:"updated_at"`
	AppCount                 int64       `db:"app_count" json:"app_count"`
}

// ListActiveNodesWithAppCounts 列出所有 active 节点并附带其当前未删除应用数量。
// OnboardingService 自动选节点时按剩余容量过滤；剩余容量 = max_apps - app_count，
// max_apps NULL 表示不限。degraded / unreachable / disabled 均不参与新应用调度。
func (q *Queries) ListActiveNodesWithAppCounts(ctx context.Context) ([]ListActiveNodesWithAppCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNodesWithAppCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveNodesWithAppCountsRow{}
	for rows.Next() {
		var i ListActiveNodesWithAppCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AgentDockerEndpoint,
			&i.AgentFileEndpoint,
			&i.AgentTlsCaCert,
			&i.AgentTokenHash,
			&i.AgentTokenCiphertext,
			&i.AgentVersion,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.ResourceSnapshotJson,
			&i.MetadataJson,
			&i.NodeDataRoot,
			&i.RegisteredAt,
			&i.MaxApps,
			&i.AgentID,
			&i.LastProbeAttemptedAt,
			&i.LastProbeOkAt,
			&i.LastProbeFailedAt,
			&i.LastProbeError,
			&i.ProbeFailureStreak,
			&i.ProbeSuccessStreak,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AppCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeNodes = `-- name: ListRuntimeNodes :many
SELECT id, name, status, agent_docker_endpoint, agent_file_endpoint, agent_tls_ca_cert, agent_token_hash, agent_token_ciphertext, agent_version, heartbeat_interval_seconds, last_heartbeat_at, resource_snapshot_json, metadata_json, node_data_root, registered_at, max_apps, agent_id, last_probe_attempted_at, last_probe_ok_at, last_probe_failed_at, last_probe_error, probe_failure_streak, probe_success_streak, created_at, updated_at
FROM runtime_nodes
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type ListRuntimeNodesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListRuntimeNodes(ctx context.Context, arg ListRuntimeNodesParams) ([]RuntimeNode, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuntimeNode{}
	for rows.Next() {
		var i RuntimeNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AgentDockerEndpoint,
			&i.AgentFileEndpoint,
			&i.AgentTlsCaCert,
			&i.AgentTokenHash,
			&i.AgentTokenCiphertext,
			&i.AgentVersion,
			&i.HeartbeatIntervalSeconds,
			&i.LastHeartbeatAt,
			&i.ResourceSnapshotJson,
			&i.MetadataJson,
			&i.NodeDataRoot,
			&i.RegisteredAt,
			&i.MaxApps,
			&i.AgentID,
			&i.LastProbeAttemptedAt,
			&i.LastProbeOkAt,
			&i.LastProbeFailedAt,
			&i.LastProbeError,
			&i.ProbeFailureStreak,
			&i.ProbeSuccessStreak,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRuntimeNodeStatus = `-- name: SetRuntimeNodeStatus :exec
UPDATE runtime_nodes
SET status = ?, updated_at = now()
WHERE id = ?
`

type SetRuntimeNodeStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) SetRuntimeNodeStatus(ctx context.Context, arg SetRuntimeNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, setRuntimeNodeStatus, arg.Status, arg.ID)
	return err
}

const updateRuntimeNodeHeartbeat = `-- name: UpdateRuntimeNodeHeartbeat :exec
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'unreachable' THEN 'active'
        ELSE status
    END,
    agent_version = ?,
    last_heartbeat_at = now(),
    resource_snapshot_json = ?,
    metadata_json = ?,
    updated_at = now()
WHERE id = ?
`

type UpdateRuntimeNodeHeartbeatParams struct {
	AgentVersion         null.String `db:"agent_version" json:"agent_version"`
	ResourceSnapshotJson []byte      `db:"resource_snapshot_json" json:"resource_snapshot_json"`
	MetadataJson         []byte      `db:"metadata_json" json:"metadata_json"`
	ID                   string      `db:"id" json:"id"`
}

func (q *Queries) UpdateRuntimeNodeHeartbeat(ctx context.Context, arg UpdateRuntimeNodeHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, updateRuntimeNodeHeartbeat,
		arg.AgentVersion,
		arg.ResourceSnapshotJson,
		arg.MetadataJson,
		arg.ID,
	)
	return err
}

const updateRuntimeNodeProbeFailure = `-- name: UpdateRuntimeNodeProbeFailure :exec
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'active' AND probe_failure_streak + 1 >= ? THEN 'degraded'
        ELSE status
    END,
    last_probe_attempted_at = now(),
    last_probe_failed_at = now(),
    last_probe_error = ?,
    probe_failure_streak = probe_failure_streak + 1,
    probe_success_streak = 0,
    updated_at = now()
WHERE id = ?
`

type UpdateRuntimeNodeProbeFailureParams struct {
	ProbeFailureStreak int32       `db:"probe_failure_streak" json:"probe_failure_streak"`
	LastProbeError     null.String `db:"last_probe_error" json:"last_probe_error"`
	ID                 string      `db:"id" json:"id"`
}

func (q *Queries) UpdateRuntimeNodeProbeFailure(ctx context.Context, arg UpdateRuntimeNodeProbeFailureParams) error {
	_, err := q.db.ExecContext(ctx, updateRuntimeNodeProbeFailure, arg.ProbeFailureStreak, arg.LastProbeError, arg.ID)
	return err
}

const updateRuntimeNodeProbeSuccess = `-- name: UpdateRuntimeNodeProbeSuccess :exec
UPDATE runtime_nodes
SET
    status = CASE
        WHEN status = 'degraded' AND probe_success_streak + 1 >= ? THEN 'active'
        ELSE status
    END,
    last_probe_attempted_at = now(),
    last_probe_ok_at = now(),
    last_probe_error = NULL,
    probe_success_streak = probe_success_streak + 1,
    probe_failure_streak = 0,
    updated_at = now()
WHERE id = ?
`

type UpdateRuntimeNodeProbeSuccessParams struct {
	ProbeSuccessStreak int32  `db:"probe_success_streak" json:"probe_success_streak"`
	ID                 string `db:"id" json:"id"`
}

func (q *Queries) UpdateRuntimeNodeProbeSuccess(ctx context.Context, arg UpdateRuntimeNodeProbeSuccessParams) error {
	_, err := q.db.ExecContext(ctx, updateRuntimeNodeProbeSuccess, arg.ProbeSuccessStreak, arg.ID)
	return err
}
