// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill_tickets.sql

package sqlc

import (
	"context"

	null "github.com/guregu/null/v5"
)

const countPendingSkillTickets = `-- name: CountPendingSkillTickets :one
SELECT COUNT(*) FROM skill_tickets WHERE status = 'pending'
`

func (q *Queries) CountPendingSkillTickets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingSkillTickets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkillTicket = `-- name: CreateSkillTicket :exec
INSERT INTO skill_tickets (
    id, org_id, requester_user_id, requester_role, title, description, status
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillTicketParams struct {
	ID              string `db:"id" json:"id"`
	OrgID           string `db:"org_id" json:"org_id"`
	RequesterUserID string `db:"requester_user_id" json:"requester_user_id"`
	RequesterRole   string `db:"requester_role" json:"requester_role"`
	Title           string `db:"title" json:"title"`
	Description     string `db:"description" json:"description"`
	Status          string `db:"status" json:"status"`
}

func (q *Queries) CreateSkillTicket(ctx context.Context, arg CreateSkillTicketParams) error {
	_, err := q.db.ExecContext(ctx, createSkillTicket,
		arg.ID,
		arg.OrgID,
		arg.RequesterUserID,
		arg.RequesterRole,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	return err
}

const createSkillTicketComment = `-- name: CreateSkillTicketComment :exec
INSERT INTO skill_ticket_comments (id, ticket_id, author_user_id, body) VALUES (?, ?, ?, ?)
`

type CreateSkillTicketCommentParams struct {
	ID           string `db:"id" json:"id"`
	TicketID     string `db:"ticket_id" json:"ticket_id"`
	AuthorUserID string `db:"author_user_id" json:"author_user_id"`
	Body         string `db:"body" json:"body"`
}

func (q *Queries) CreateSkillTicketComment(ctx context.Context, arg CreateSkillTicketCommentParams) error {
	_, err := q.db.ExecContext(ctx, createSkillTicketComment,
		arg.ID,
		arg.TicketID,
		arg.AuthorUserID,
		arg.Body,
	)
	return err
}

const getSkillTicket = `-- name: GetSkillTicket :one
SELECT id, org_id, requester_user_id, requester_role, title, description, status, quote_amount_cents, custom_skill_name, reject_reason, created_at, updated_at FROM skill_tickets WHERE id = ?
`

func (q *Queries) GetSkillTicket(ctx context.Context, id string) (SkillTicket, error) {
	row := q.db.QueryRowContext(ctx, getSkillTicket, id)
	var i SkillTicket
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequesterUserID,
		&i.RequesterRole,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.QuoteAmountCents,
		&i.CustomSkillName,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSkillTickets = `-- name: ListAllSkillTickets :many
SELECT id, org_id, requester_user_id, requester_role, title, description, status, quote_amount_cents, custom_skill_name, reject_reason, created_at, updated_at FROM skill_tickets ORDER BY (status = 'pending') DESC, updated_at DESC, id DESC
`

func (q *Queries) ListAllSkillTickets(ctx context.Context) ([]SkillTicket, error) {
	rows, err := q.db.QueryContext(ctx, listAllSkillTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillTicket{}
	for rows.Next() {
		var i SkillTicket
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequesterUserID,
			&i.RequesterRole,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.QuoteAmountCents,
			&i.CustomSkillName,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillTicketComments = `-- name: ListSkillTicketComments :many
SELECT id, ticket_id, author_user_id, body, created_at FROM skill_ticket_comments WHERE ticket_id = ? ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSkillTicketComments(ctx context.Context, ticketID string) ([]SkillTicketComment, error) {
	rows, err := q.db.QueryContext(ctx, listSkillTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillTicketComment{}
	for rows.Next() {
		var i SkillTicketComment
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorUserID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillTicketsByRequester = `-- name: ListSkillTicketsByRequester :many
SELECT id, org_id, requester_user_id, requester_role, title, description, status, quote_amount_cents, custom_skill_name, reject_reason, created_at, updated_at FROM skill_tickets WHERE requester_user_id = ? ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListSkillTicketsByRequester(ctx context.Context, requesterUserID string) ([]SkillTicket, error) {
	rows, err := q.db.QueryContext(ctx, listSkillTicketsByRequester, requesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillTicket{}
	for rows.Next() {
		var i SkillTicket
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequesterUserID,
			&i.RequesterRole,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.QuoteAmountCents,
			&i.CustomSkillName,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectSkillTicket = `-- name: RejectSkillTicket :exec
UPDATE skill_tickets SET status = 'rejected', reject_reason = ? WHERE id = ?
`

type RejectSkillTicketParams struct {
	RejectReason null.String `db:"reject_reason" json:"reject_reason"`
	ID           string      `db:"id" json:"id"`
}

func (q *Queries) RejectSkillTicket(ctx context.Context, arg RejectSkillTicketParams) error {
	_, err := q.db.ExecContext(ctx, rejectSkillTicket, arg.RejectReason, arg.ID)
	return err
}

const setSkillTicketQuote = `-- name: SetSkillTicketQuote :exec
UPDATE skill_tickets SET quote_amount_cents = ? WHERE id = ?
`

type SetSkillTicketQuoteParams struct {
	QuoteAmountCents null.Int `db:"quote_amount_cents" json:"quote_amount_cents"`
	ID               string   `db:"id" json:"id"`
}

func (q *Queries) SetSkillTicketQuote(ctx context.Context, arg SetSkillTicketQuoteParams) error {
	_, err := q.db.ExecContext(ctx, setSkillTicketQuote, arg.QuoteAmountCents, arg.ID)
	return err
}

const touchSkillTicket = `-- name: TouchSkillTicket :exec
UPDATE skill_tickets SET updated_at = CURRENT_TIMESTAMP(6) WHERE id = ?
`

func (q *Queries) TouchSkillTicket(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSkillTicket, id)
	return err
}

const updateSkillTicketStatus = `-- name: UpdateSkillTicketStatus :exec
UPDATE skill_tickets SET status = ? WHERE id = ?
`

type UpdateSkillTicketStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     string `db:"id" json:"id"`
}

func (q *Queries) UpdateSkillTicketStatus(ctx context.Context, arg UpdateSkillTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSkillTicketStatus, arg.Status, arg.ID)
	return err
}
