// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    org_id,
    username,
    password_hash,
    display_name,
    role,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	OrgID        pgtype.UUID `db:"org_id" json:"org_id"`
	Username     string      `db:"username" json:"username"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	DisplayName  string      `db:"display_name" json:"display_name"`
	Role         string      `db:"role" json:"role"`
	Status       string      `db:"status" json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrgID,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgAdminByOrg = `-- name: GetOrgAdminByOrg :one
SELECT id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE org_id = $1
  AND role = 'org_admin'
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
LIMIT 1
`

// 组织列表复制登录信息时只需要一个可登录的组织管理员用户名。
// 密码明文不落库，因此这里只返回账号名，密码提示由调用方生成。
func (q *Queries) GetOrgAdminByOrg(ctx context.Context, orgID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getOrgAdminByOrg, orgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByOrgAndUsername = `-- name: GetUserByOrgAndUsername :one
SELECT id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE org_id = $1 AND username = $2
`

type GetUserByOrgAndUsernameParams struct {
	OrgID    pgtype.UUID `db:"org_id" json:"org_id"`
	Username string      `db:"username" json:"username"`
}

func (q *Queries) GetUserByOrgAndUsername(ctx context.Context, arg GetUserByOrgAndUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOrgAndUsername, arg.OrgID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE org_id IS NULL AND username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListUsersByOrgParams struct {
	OrgID  pgtype.UUID `db:"org_id" json:"org_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListUsersByOrg(ctx context.Context, arg ListUsersByOrgParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserLoggedIn = `-- name: MarkUserLoggedIn :one
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
`

func (q *Queries) MarkUserLoggedIn(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserLoggedIn, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE users
SET status = $2,
    deleted_at = CASE WHEN $2 = 'disabled' THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
`

type SetUserStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status string      `db:"status" json:"status"`
}

// disabled 时同步写 deleted_at（下线时间戳）；enabled 时清空，让重启用户能恢复。
func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// 真软删除：仅设置 deleted_at（不动 status）；status 与 deleted_at 语义独立。
func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, role = $3, updated_at = now()
WHERE id = $1
RETURNING id, org_id, username, password_hash, display_name, role, status, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	DisplayName string      `db:"display_name" json:"display_name"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
