// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web_publish_config.sql

package sqlc

import (
	"context"

	null "github.com/guregu/null/v5"
)

const getWebPublishConfig = `-- name: GetWebPublishConfig :one
SELECT org_id, enabled, base_domain, dns_provider, dns_credentials_ciphertext, site_ttl_days, max_sites, provisioning_status, provisioning_message, cert_secret_name, cert_status, cert_not_after, cert_last_issued_at, cert_last_renewed_at, cert_message, created_at, updated_at FROM org_web_publish_config WHERE org_id = ?
`

// 按企业取发布能力配置；不存在返回 sql.ErrNoRows（视为未开通）。
func (q *Queries) GetWebPublishConfig(ctx context.Context, orgID string) (OrgWebPublishConfig, error) {
	row := q.db.QueryRowContext(ctx, getWebPublishConfig, orgID)
	var i OrgWebPublishConfig
	err := row.Scan(
		&i.OrgID,
		&i.Enabled,
		&i.BaseDomain,
		&i.DnsProvider,
		&i.DnsCredentialsCiphertext,
		&i.SiteTtlDays,
		&i.MaxSites,
		&i.ProvisioningStatus,
		&i.ProvisioningMessage,
		&i.CertSecretName,
		&i.CertStatus,
		&i.CertNotAfter,
		&i.CertLastIssuedAt,
		&i.CertLastRenewedAt,
		&i.CertMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigsCertExpiringBefore = `-- name: ListConfigsCertExpiringBefore :many
SELECT org_id, enabled, base_domain, dns_provider, dns_credentials_ciphertext, site_ttl_days, max_sites, provisioning_status, provisioning_message, cert_secret_name, cert_status, cert_not_after, cert_last_issued_at, cert_last_renewed_at, cert_message, created_at, updated_at FROM org_web_publish_config
WHERE enabled = 1
  AND provisioning_status = 'ready'
  AND cert_status = 'issued'
  AND cert_not_after IS NOT NULL
  AND cert_not_after < ?
`

// 证书续签巡检：列出已签发且 cert_not_after 早于阈值的企业配置（需续签）。
func (q *Queries) ListConfigsCertExpiringBefore(ctx context.Context, certNotAfter null.Time) ([]OrgWebPublishConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfigsCertExpiringBefore, certNotAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgWebPublishConfig{}
	for rows.Next() {
		var i OrgWebPublishConfig
		if err := rows.Scan(
			&i.OrgID,
			&i.Enabled,
			&i.BaseDomain,
			&i.DnsProvider,
			&i.DnsCredentialsCiphertext,
			&i.SiteTtlDays,
			&i.MaxSites,
			&i.ProvisioningStatus,
			&i.ProvisioningMessage,
			&i.CertSecretName,
			&i.CertStatus,
			&i.CertNotAfter,
			&i.CertLastIssuedAt,
			&i.CertLastRenewedAt,
			&i.CertMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebPublishConfigs = `-- name: ListWebPublishConfigs :many
SELECT org_id, enabled, base_domain, dns_provider, dns_credentials_ciphertext, site_ttl_days, max_sites, provisioning_status, provisioning_message, cert_secret_name, cert_status, cert_not_after, cert_last_issued_at, cert_last_renewed_at, cert_message, created_at, updated_at FROM org_web_publish_config ORDER BY updated_at DESC
`

// 平台管理员全局视图：列出所有企业的发布能力配置。
func (q *Queries) ListWebPublishConfigs(ctx context.Context) ([]OrgWebPublishConfig, error) {
	rows, err := q.db.QueryContext(ctx, listWebPublishConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgWebPublishConfig{}
	for rows.Next() {
		var i OrgWebPublishConfig
		if err := rows.Scan(
			&i.OrgID,
			&i.Enabled,
			&i.BaseDomain,
			&i.DnsProvider,
			&i.DnsCredentialsCiphertext,
			&i.SiteTtlDays,
			&i.MaxSites,
			&i.ProvisioningStatus,
			&i.ProvisioningMessage,
			&i.CertSecretName,
			&i.CertStatus,
			&i.CertNotAfter,
			&i.CertLastIssuedAt,
			&i.CertLastRenewedAt,
			&i.CertMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWebPublishCertStatus = `-- name: SetWebPublishCertStatus :exec
UPDATE org_web_publish_config
SET cert_status = ?, cert_not_after = ?, cert_last_issued_at = ?, cert_last_renewed_at = COALESCE(?, cert_last_renewed_at), cert_message = ?, updated_at = now()
WHERE org_id = ?
`

type SetWebPublishCertStatusParams struct {
	CertStatus        string      `db:"cert_status" json:"cert_status"`
	CertNotAfter      null.Time   `db:"cert_not_after" json:"cert_not_after"`
	CertLastIssuedAt  null.Time   `db:"cert_last_issued_at" json:"cert_last_issued_at"`
	CertLastRenewedAt null.Time   `db:"cert_last_renewed_at" json:"cert_last_renewed_at"`
	CertMessage       null.String `db:"cert_message" json:"cert_message"`
	OrgID             string      `db:"org_id" json:"org_id"`
}

// 状态机/巡检更新证书状态：状态 + 到期 + 最近签发时间 + 最近续签时间 + 摘要。
// cert_last_renewed_at 用 COALESCE 跳过传 NULL 的场景（首签只更新 issued_at，续签更新 renewed_at）。
func (q *Queries) SetWebPublishCertStatus(ctx context.Context, arg SetWebPublishCertStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWebPublishCertStatus,
		arg.CertStatus,
		arg.CertNotAfter,
		arg.CertLastIssuedAt,
		arg.CertLastRenewedAt,
		arg.CertMessage,
		arg.OrgID,
	)
	return err
}

const setWebPublishEnabled = `-- name: SetWebPublishEnabled :exec
UPDATE org_web_publish_config
SET enabled = ?, provisioning_status = ?, updated_at = now()
WHERE org_id = ?
`

type SetWebPublishEnabledParams struct {
	Enabled            bool   `db:"enabled" json:"enabled"`
	ProvisioningStatus string `db:"provisioning_status" json:"provisioning_status"`
	OrgID              string `db:"org_id" json:"org_id"`
}

// 开通/停用：置 enabled 与 provisioning_status（开通时由 service 传 'provisioning'）。
func (q *Queries) SetWebPublishEnabled(ctx context.Context, arg SetWebPublishEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setWebPublishEnabled, arg.Enabled, arg.ProvisioningStatus, arg.OrgID)
	return err
}

const setWebPublishProvisioning = `-- name: SetWebPublishProvisioning :exec
UPDATE org_web_publish_config
SET provisioning_status = ?, provisioning_message = ?, cert_secret_name = ?, updated_at = now()
WHERE org_id = ?
`

type SetWebPublishProvisioningParams struct {
	ProvisioningStatus  string      `db:"provisioning_status" json:"provisioning_status"`
	ProvisioningMessage null.String `db:"provisioning_message" json:"provisioning_message"`
	CertSecretName      string      `db:"cert_secret_name" json:"cert_secret_name"`
	OrgID               string      `db:"org_id" json:"org_id"`
}

// 状态机更新 provisioning 结果：状态 + 摘要 + 证书 Secret 名。
func (q *Queries) SetWebPublishProvisioning(ctx context.Context, arg SetWebPublishProvisioningParams) error {
	_, err := q.db.ExecContext(ctx, setWebPublishProvisioning,
		arg.ProvisioningStatus,
		arg.ProvisioningMessage,
		arg.CertSecretName,
		arg.OrgID,
	)
	return err
}

const upsertWebPublishConfig = `-- name: UpsertWebPublishConfig :exec
INSERT INTO org_web_publish_config (
    org_id, base_domain, dns_provider, dns_credentials_ciphertext, site_ttl_days, max_sites
) VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    base_domain                = VALUES(base_domain),
    dns_provider               = VALUES(dns_provider),
    dns_credentials_ciphertext = VALUES(dns_credentials_ciphertext),
    site_ttl_days              = VALUES(site_ttl_days),
    max_sites                  = VALUES(max_sites),
    updated_at                 = now()
`

type UpsertWebPublishConfigParams struct {
	OrgID                    string      `db:"org_id" json:"org_id"`
	BaseDomain               string      `db:"base_domain" json:"base_domain"`
	DnsProvider              string      `db:"dns_provider" json:"dns_provider"`
	DnsCredentialsCiphertext null.String `db:"dns_credentials_ciphertext" json:"dns_credentials_ciphertext"`
	SiteTtlDays              int32       `db:"site_ttl_days" json:"site_ttl_days"`
	MaxSites                 int32       `db:"max_sites" json:"max_sites"`
}

// 平台管理员配置/改配置：写基础域名 / provider / 凭证密文 / 配额。
// 不触碰 provisioning_status 与 cert_* 状态（那由状态机维护），首插时取列默认值。
func (q *Queries) UpsertWebPublishConfig(ctx context.Context, arg UpsertWebPublishConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertWebPublishConfig,
		arg.OrgID,
		arg.BaseDomain,
		arg.DnsProvider,
		arg.DnsCredentialsCiphertext,
		arg.SiteTtlDays,
		arg.MaxSites,
	)
	return err
}
